### ISSUE TITLE
Error through web installer

### ISSUE THREAD

**Issue by maximuml** [xiaomlove/nexusphp#10]
`Error: can't not make symbolic link: /home/wwwroot/public/bitbucket -> /home/wwwroot/bitbucket`
On step 4

**Comment by xiaomlove** [comment]
May be php does not have the permission.
find out php user,  such as : www-data, then try this: `chown -R www-data:www-data  /home/wwwroot`
If you don't know the php user, try this: `chmod -R 777 /home/wwwroot`

**Comment by maximuml** [comment]
I change permission but no luck (
How to make symbolic link in command line?
