### ISSUE TITLE
[Request] Seedbox icon in torrents page

### ISSUE THREAD

**Issue by LuciuzHQ** [xiaomlove/nexusphp#100]
Hello,

Is it possible to show the seedbox icon in the torrents page beside the approbation icon ?

Thanks.

**Comment by xiaomlove** [comment]
Please take a screenshot to illustrate

**Comment by LuciuzHQ** [comment]
![seed_icon](https://user-images.githubusercontent.com/90622803/187988885-42530f3b-2d44-47f2-8acb-0b52bf164244.png)

**Comment by xiaomlove** [comment]
If uploader is using seedBox, show this icon ?

**Comment by LuciuzHQ** [comment]
Yes show this icon please.

**Comment by xiaomlove** [comment]
got it, I will take a look first.

**Comment by Stargaterom** [comment]
hello @xiaomlove  ,

I added ip seedbox to two users.

when uploading a torrent with the first seed-box icon displayed on the torrent page.

here is my problem when I download the torrent of the first user with the second user who also has a seed-box register and authorize, they seed myself my seedbox icon on the torrent page disappears for the time the 2 users have a seed-box therefore re-register in logic if there is a user on seed-box icon of should not disappear when a person shares my second

**Comment by xiaomlove** [comment]
@Stargaterom Sorry ,I don't understand, you can show some screen shoot maybe .

**Comment by Stargaterom** [comment]
here is screenshot that shows torrent.php and detail.php page peers.

![page torrent](https://user-images.githubusercontent.com/107837857/189537173-8b9d88de-6126-4ff6-9140-1edab5c0e144.png)
![peers du torrent](https://user-images.githubusercontent.com/107837857/189537182-a417644f-44d3-4d3e-b125-c6772fa2546c.png)
there is indeed a seed-box in the peers my icon displays more

**Comment by xiaomlove** [comment]
The current logic is that only uploader who are seedbox users will be displayed. Do you want to show it whenever any seeder uses the seed box?

**Comment by Stargaterom** [comment]
yes I would like to have an icon if a user in peers has a seed-box because it shows that the torrent is fast even if uploading and more on it so if its possible added its would be really good

**Comment by xiaomlove** [comment]
OK，I will change it later

**Comment by Stargaterom** [comment]
ok thank you very much i can't wait to see the change

**Comment by xiaomlove** [comment]
You can update to the latest commit to confirm if it is OK now
@Stargaterom

**Comment by Stargaterom** [comment]
Hello,

I did the update. my icons have disappeared and to display them I have to enter the description click on peers to see the users in seed and the icon appears on the torrent page

**Comment by Stargaterom** [comment]
here is what i have on the torrent page
![page torrent](https://user-images.githubusercontent.com/107837857/189700388-73d2abe6-4eed-48b0-89eb-b58c303565f9.png)
in the description of the torrent I click on peers to open the table and I click on icon.
![peers](https://user-images.githubusercontent.com/107837857/189700868-a09a5285-2679-4b55-9ff2-13b192251d94.png)
![tableau peers](https://user-images.githubusercontent.com/107837857/189700892-d6566159-72a0-41f5-b072-c48ef60de330.png)
and when I return to the torrent page icon and display:

![icone afficher](https://user-images.githubusercontent.com/107837857/189701043-64f079a6-1071-400c-bba7-ab7de7a57c88.png)
do I have to delete the seedboxes and add them again, maybe a problem with the old parameters?

if I change page and return to the torrent page icon has disappeared

**Comment by xiaomlove** [comment]
Got it

**Comment by Stargaterom** [comment]
you had understood where could come the problem related to your change ?

**Comment by xiaomlove** [comment]
Fixed, just upgrade to the latest commit.

**Comment by Stargaterom** [comment]
ok I'll make the changes and I'll come back to you thank you

**Comment by Stargaterom** [comment]
I modified the ad file and icon still does not appear automatically, I have to go to the description, open the peers so that the icon displays. 

unless it takes time before detecting to add them to the torrent page

thank you for the modification I will do some tests to see if there is no need for a certain time for the function

**Comment by xiaomlove** [comment]
the peer seedbox status will be update when view peer list or BT client sent a report

**Comment by Stargaterom** [comment]
thank you very much for your answer so you associated with the bt client so I understand better than its not instantaneous
