### ISSUE TITLE
[Request] Modification authkey of .torrent

### ISSUE THREAD

**Issue by Skyline-007** [xiaomlove/nexusphp#104]
Hello

I would like to know if it would be possible to simplify the authkey ?

Because here is the current format of the authkey:
https://hulk.jk/announce.php?authkey=12000|6|yeahhh

Inside is the ID number of the torrent page (12000)
If we change the domain name of the site. It will be necessary to modify all the torrents one by one of each .torrent in our torrent client.
As there is the torrent ID number and the authkey which are different each time.

I would like to know if it would be possible to simplify the authkey by deleting the ID number of the torrent and for the authkey always remains the same authkey number ? (so that there is no link with the ID number of the torrent page and that the authkey always remains the same number)

Because currently the authkey changes number all the time when you take a .torrent

The day when it is necessary to change the domain name of the site, we select all the .torrents and we change the authkey set of all the .torrents at once in the torrent client.

Example new authkey without the torrent ID number and the authkey with always the same number:

https://hulk.jk/announce.php?authkey=|6|yeahhh

Where

http://hulk.jk/announce.php?passkey=f4xxxxxxxxxxxxxxxxxxxxxxxb

Thank you in advance for your answer

Best regards

Skyline-007

**Comment by xiaomlove** [comment]
The domain names are unified, and modifying them has nothing to do with this.

**Comment by Skyline-007** [comment]
@xiaomlove 

The day I migrate my domain name, I will have to edit all my torrents one by one.

Because the ad authkey and all the time different.

When I go to my torrent client the current announce is: 
![1111](https://user-images.githubusercontent.com/108820368/189359402-18503483-17b3-4eff-92d2-66ea99b10f82.png)



And it possible to have an ad with a passkey like this that is linked to the username ?
(The passkey never changes, compared to the authkey which changes all the time)


Example of the new announce: 
![222222](https://user-images.githubusercontent.com/108820368/189359456-55df73ff-286b-4a7c-9ca5-fee4966aeca8.png)

The day I migrate my domain name, I could select all my .torrents in my torrent client and edit all my .torrents at once.
Because the announce passkey ad will always be the same on all .torrents.

**Comment by xiaomlove** [comment]
This issue has been received.
Older torrents can be reported using passkey, change the tracker URL of existing torrents in the BT client to: `https://your-domain.com/announce.php?passkey=<user passkey>`
This change is designed to protect passkey and will be optimized later.

**Comment by Skyline-007** [comment]
Ok thank you very much.

Can't wait to see it in future updates

**Comment by xiaomlove** [comment]
Now you can change the tracker URL of existing torrents in the BT client to: 
`https://your-domain.com/announce.php?passkey=<user passkey>`

It is always working, no needs any updates.

**Comment by Skyline-007** [comment]
OK
Thank you, I just tested it and it works fine.

Thanks again for your work.
