### ISSUE TITLE
[Request] [img] [/img] tag button not functional on the "upload" page

### ISSUE THREAD

**Issue by Skyline-007** [xiaomlove/nexusphp#106]
Hello

I wanted to use the tag button [img] [/img] but the ![img1](https://user-images.githubusercontent.com/108820368/189399274-ab8ada3a-9d4c-4408-a99a-4bd77254c769.png) button does not work

![img](https://user-images.githubusercontent.com/108820368/189399578-354067cf-61ae-4f56-aaf2-6beca0a6a832.png)

Can you see on your side why the [img] [/img] tag is not working ?

Thank you in advance for your answer

Best regards

Skyline-007

**Comment by xiaomlove** [comment]
Click to enter the image address in the pop-up window, is able to display correctly

**Comment by Skyline-007** [comment]
@xiaomlove 

When I click on the img tag button it doesn't work.

I have no pop-up window that appears on the screen, to offer me to enter an image link.

Even on a fresh install of nexusphp 1.7.24 it doesn't work. I have no pop-up window that appears on the screen, to offer me to enter an image link.

**Comment by xiaomlove** [comment]
This function has been working fine, you can go to the [demo site](https://demo.nexusphp.org/) to see it.

**Comment by Skyline-007** [comment]
@xiaomlove I just tried on your demo site the IMG tag button works.

I would like to know where did you enter the lines and in which file ? To add the IMG tag button

So that I compare against my version if there is not a line missing in the file.

Thank you in advance for your answer

**Comment by Skyline-007** [comment]
Ok, I fixed the problem.

I found where the problem is.

**Comment by LuciuzHQ** [comment]
@Skyline-007 What was the problem please ? I have exactly the same.
