### ISSUE TITLE
Recommended Movie: class moderator ?

### ISSUE THREAD

**Issue by Stargaterom** [xiaomlove/nexusphp#107]
hello @xiaomlove  ,

only the leader and sysop have access to the movie recommended on the edit.php page.

here is the leader staff and  sysop:
![edit torrent pick grade leader staff sysop](https://user-images.githubusercontent.com/107837857/189528364-fd586169-57f7-4285-8bfb-5dd4e0c5e236.png)

here the administrator and moderator: 
![edit torrent pick moderator](https://user-images.githubusercontent.com/107837857/189528462-64142c8d-f506-4d72-adaa-c0223d03fd88.png)

I want to be able to modify the Recommended Movies
would it be possible to have access from the class moderator.

because I even changed the promotion permissions in Website Settings and I still don't see Recommended Movie: 

![authority setting](https://user-images.githubusercontent.com/107837857/189528700-c3b10b24-1df1-4913-b03a-f8a9157c8da4.png)

could help you to modify this authorization by indicating where I can change the class cordially

**Comment by Stargaterom** [comment]
its good i solved the problem the change is done on takeedit.php and edit.php see the file App\Models\User for the class. 

edit.php = 
![edit php](https://user-images.githubusercontent.com/107837857/189532164-c9612aa0-b577-4b91-af20-2159ffddd155.png)

takeedit.php : 

![takeedit](https://user-images.githubusercontent.com/107837857/189532189-7f63337b-302c-49df-8add-f6bc8aa8d330.png)

**Comment by xiaomlove** [comment]
It turns out that users who have torrent management permission and are pickers have permission to set it.
![Picker](https://user-images.githubusercontent.com/8530353/189535438-6f0ddd40-75f7-4275-a996-ea2b22cf02e6.png)

Later, for convenience, it was added that sysop also has privileges

**Comment by Stargaterom** [comment]
okay hadn't seen this option in userdetail of user because my translation was not good so I just reset to original state and set to yes and yes it works it displays well on the edit.php page thank you for your help on this subject
