### ISSUE TITLE
[Request] Add Online Users

### ISSUE THREAD

**Issue by Skyline-007** [xiaomlove/nexusphp#108]
Hello

I would like to know if it would be possible to add online Shoutbox Users below the Shoutbox in a window ?
And when the user is offline on the Shoutbox, they no longer appear in the list of Online Users in the Shoutbox.

(I am talking about showing online shoutbox users, when he writes on shoutbox and if the user does not write on shoutbox he disappears from online shoutbox users after 10 minutes of inactivity when he does not wrote more on the shoutbox.)

It allows you to really see who is talking on the shoutbox.

Example :
![Shoutbox online users](https://user-images.githubusercontent.com/108820368/189749700-1d8fe964-3b85-47f8-a523-9bbb643e6334.jpg)

And is it also possible to add a second window for Online Users on the site ?
At the bottom of the Home page.
And when the user is offline on the site, he no longer appears in the list of Online Users of the site.

Example :
![Online users](https://user-images.githubusercontent.com/108820368/189749845-e8aa5034-588a-4499-ac41-dcb0757d664d.jpg)

Thank you in advance for your answer.

Thanks again for all the work you've done for nexusphp.

Best regards

Have a good day

Skyline-007

**Comment by maximuml** [comment]
I think it's pointless to add chat online users separate from online users. If user online he is online in chat either.
I think useful will be Users active in the past 24 hrs block somewhere around trackers stats on index page.

**Comment by Stargaterom** [comment]
yes it could be interesting to see which users are connected to the shootbox

**Comment by Skyline-007** [comment]
For online users of the Shoutbox.

I am talking about showing online shoutbox users, when he writes on shoutbox and if the user does not write on shoutbox he disappears from online shoutbox users after 10 minutes of inactivity when he does not wrote more on the shoutbox.

It allows you to really see who is talking on the shoutbox.

**Comment by Skyline-007** [comment]
@xiaomlove can we get an answer from you ?
Know if we will be able to see this option in a future update ?
