### ISSUE TITLE
[Request] NFO opens with "Windows-vy" for default view

### ISSUE THREAD

**Issue by Skyline-007** [xiaomlove/nexusphp#109]
Hello

I want to change the default NFO display order.

By default the NFO opens with "DOS-vy".

I would like the NFO to open with "Windows-vy" for default display

Here is a screenshot:
![nfo](https://user-images.githubusercontent.com/108820368/191535398-e9519e5a-8c6d-47d6-91c7-e5034e533369.png)

![NFO Windows-vy](https://user-images.githubusercontent.com/108820368/191535425-79bd35a7-003c-4131-b82b-3073cf665e33.png)

I would like the NFO to open with "Windows-vy" for default display

Where are the files and what are the lines to modify ?

Thanks in advance for your response and help.

Best regards

Skyline-007

**Comment by Stargaterom** [comment]
if I understood correctly you want to change by default the nfo mode on the detail.php page.
![dos-vy](https://user-images.githubusercontent.com/107837857/191548577-8048f5ec-64ff-47e0-aaac-4ec33090b7ea.png)

in windows-vy by default:
![default windows-vy](https://user-images.githubusercontent.com/107837857/191548809-d97f0906-1c28-4a80-830f-08e36faecd0f.png)

without having to click on all mode ?

unfortunately I'm also looking for a solution because I can't pass it to windows-vy on the dedail.php file, we have the code: $nfo = code($row["nfo"], $view == "magic");

I can change to latin-1 but it doesn't work so if our friends @xiaomlove can help us it would be nice of him because I'm dry

**Comment by xiaomlove** [comment]
Can't see any difference between the different models, can you provide a copy of what looks different in the different models?

**Comment by Stargaterom** [comment]
on the detail page when pressing the + it displays the distorted text in dos-vy my I want to have it displayed directly in windows-vy to avoid the distortion of all nfo of the same type so as on my second picture we can see that in windows-vy it is not distorted compared to the first picture.

my second picture is a montage that I made to show you what I'm trying to do.

I can't find in the code or modify to display in windows-vy on the detail.php page

**Comment by xiaomlove** [comment]
In the next version I'll provide a configuration to determine which display style to use by default

**Comment by Stargaterom** [comment]
okay thank you very much it would be more visual for my info.
Cordially

**Comment by Skyline-007** [comment]
Thank you to @Stargaterom , I see that you were able to explain my problem to @xiaomlove 

Thanks again @xiaomlove for the option that you will add in the next update.

**Comment by Stargaterom** [comment]
@Skyline-007 if I can help it is with pleasure !!! @xiaomlove does all the work

**Comment by Skyline-007** [comment]
@xiaomlove  did you finish fix suggest xss + nfo view style default ?


Here is what I have in torrent settings :
![Screenshot_3](https://user-images.githubusercontent.com/108820368/192769029-9d46b353-223f-4390-89cc-e59c700b3b8b.png)


Here is the NFO from the Details.php page :
![nfo1](https://user-images.githubusercontent.com/108820368/192769138-9bc36791-19e3-4782-846d-4f7efacc25c9.png)



And here is the NFO from the viewnfo.php page :
![nfo2](https://user-images.githubusercontent.com/108820368/192769175-7a19f3f5-9b5c-43d1-8f08-c17b8586827d.png)



Image is always distorted


Thank you in advance for your answer

**Comment by xiaomlove** [comment]
It turns out that there are only these two modes, I don't know which one can be displayed properly, so can you upload a copy of the nfo file up?

**Comment by Skyline-007** [comment]
@xiaomlove here is the link of the NFO which appears distorted.

The NFO is in "ANSI" encoding.

https://uptobox.com/ch4pgigukzth

**Comment by xiaomlove** [comment]
Made a commit with reference to UNIT3D, updated to the latest and have a look.

**Comment by Skyline-007** [comment]
@xiaomlove Thanks for the corrections you made.
This fixes the display problem of this type of NFO format.

**Comment by Stargaterom** [comment]
hello @xiaomlove , thank you for this modification for the nfo
