### ISSUE TITLE
problem display result testip.php

### ISSUE THREAD

**Issue by Stargaterom** [xiaomlove/nexusphp#110]
hello @xiaomlove  I just see a problem linking to the testip.php page

here all and ok
![191945162-5c7e2140-ff46-4d2c-88a4-4a8a03067db5](https://user-images.githubusercontent.com/107837857/191993287-64880178-ab6f-4815-9f6e-c5690b1c0e4e.png)

when we do ok here is the result
![191945577-e024e2c2-39b6-443f-8976-7b017ec4b197](https://user-images.githubusercontent.com/107837857/191972102-cb2dc66c-22b7-4307-9367-dc94c29337ec.png)

where could the problem come from?

**Comment by xiaomlove** [comment]
Next release will fix this.

**Comment by Stargaterom** [comment]
thank you for fixing
