### ISSUE TITLE
[Request] Option of automatic approval of torrents according to the Minimum Class chosen

### ISSUE THREAD

**Issue by Skyline-007** [xiaomlove/nexusphp#111]
While wishing to keep the approval system.

I would like to know if you can add an option in "site settings/Authority Settings" to select a Minimum Class that will allow torrents to be Automatically Approved ?

Minimum and Higher Class will no longer go through torrent approval.
They will be in Automatic Approval.

Here is the example for you in "site settings/Authority Settings" :
![Screenshot_2](https://user-images.githubusercontent.com/108820368/192546501-5d6099df-6e7f-494b-b2fa-882ec02ec2be.png)

**Comment by xiaomlove** [comment]
can be possible

**Comment by Stargaterom** [comment]
hello, @xiaomlove  @Skyline-007 

yes it would not be a bad idea for example if we choose the class min uploader everything below will be subject to approval by the staff and the class to select and above will be added automatically

**Comment by Skyline-007** [comment]
> can be possible

@xiaomlove thank you for your reply.

Do you have a chance to see this option in a future update ?

**Comment by xiaomlove** [comment]
Yes, will add it soon

**Comment by xiaomlove** [comment]
added, upgrade to the latest commit.

**Comment by Stargaterom** [comment]
congratulations @xiaomlove  for this very useful option to lighten the pending torrent thank you

**Comment by Skyline-007** [comment]
@xiaomlove Thank you for adding option which works very well.
Thanks again for all the work you have done.
