### ISSUE TITLE
Show/Hide raw MediaInfo

### ISSUE THREAD

**Issue by Stargaterom** [xiaomlove/nexusphp#112]
Hello,

following your last update we can no longer unroll Show/Hide raw MediaInfo in technical info its normal ?

page detail.php

![hide raw media info](https://user-images.githubusercontent.com/107837857/193400903-fc200f07-6580-4554-9bb9-9de7f647b89a.png)

**Comment by xiaomlove** [comment]
Demo is good, check the page for errors and so on, and look at the logs.

**Comment by Stargaterom** [comment]
thank you for your answer so I have no log error, I noticed that technical info in my torrent uploader before update of Commits on Sep 30, 2022 it is all a problem, if technical info is added to a torrent where it was not present my drop down works

detail page on a torrent where there was already a technical info added:
![info technique ajouté avant](https://user-images.githubusercontent.com/107837857/193406156-4dccde5f-8279-429d-b189-09312d3b6933.png)

detail page on a torrent where I added technical info after update : 

![infotechinque ajouter  sur  un upload  qui en avais pas avant](https://user-images.githubusercontent.com/107837857/193406198-32f4cea2-de4e-4dc4-b1c3-2564c58c5279.png)

so all my torrents where there is technical info put before update!! the drop-down does not work, I click on it nothing happens.

For other torrents that have no technical information and that I added after update, there is no problem, the process works


are you or can come bug?

**Comment by Stargaterom** [comment]
it seems to me that your last fix has corrected my problem
