### ISSUE TITLE
[Request] Added "Manual Shoutbox Cleanup" in the "staffpanel.php"

### ISSUE THREAD

**Issue by Skyline-007** [xiaomlove/nexusphp#115]
I would like to know if it would be possible to add a shoutbox cleaning "button" ?
(This will erase all shoutbox messages including history)

The "Clean Shoutbox" button would be available from the "moderator" class.

Example:
![clean shoutbox](https://user-images.githubusercontent.com/108820368/194702013-05fb03c9-ff5a-4d5b-abe3-2089bfe86385.png)

![1clean shoutbox](https://user-images.githubusercontent.com/108820368/194702018-ebe0d16d-682b-49e7-b9fa-49835a59c90b.png)

Thanks in advance for your response and help.

Best regards

Skyline-007

**Comment by xiaomlove** [comment]
Currently automatically cleaned up six months ago

**Comment by Skyline-007** [comment]
OK.
Thank you for your reply.

An "Automatic Shoutbox Cleaning" every 6 Months is really long.

Here what I'm asking would be the possibility of doing a "Manual Shoutbox Cleaning" when you want by clicking on the button "Clean Shoutbox"

Either from the Shoutbox with a button "Clean Shoutbox" like my example:
![button clean shoutbox](https://user-images.githubusercontent.com/108820368/194770853-543cee22-c886-4d00-bd39-638acf1a5c77.png)


Or add "Manual Shoutbox Cleanup" option from "staffpanel.php"

The "Clean Shoutbox" button would be available from the "moderator" class.

**Comment by Skyline-007** [comment]
@xiaomlove can we get an answer from you ?
Will this option be available in a future nexusphp update ?

**Comment by xiaomlove** [comment]
yes

**Comment by Skyline-007** [comment]
@xiaomlove thank you for the implementation of the manual Shoutbox cleaning button it works very well
