### ISSUE TITLE
please help me added torrent client Freebox bittorrent 2.0

### ISSUE THREAD

**Issue by Stargaterom** [xiaomlove/nexusphp#116]
hello, I would like to be able to add the Freebox bittorrent 2.0 torrent client but I don't understand how the Agent Allow system works and its not necessarily what needs to be added, I've tried a lot of things my I have a 500 server error.
![Screenshot_2](https://user-images.githubusercontent.com/107837857/194895043-50d75509-2d83-4e47-b400-43ef38e3f807.png)
![Screenshot_3](https://user-images.githubusercontent.com/107837857/194895267-68a6f8f7-b50a-4d2f-b9ac-d29804fd0ceb.png)

see the error message on the client torrent= "connection failed" and then "unable to register on the tracker"

here is error in my log = production.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1048.

**Comment by Stargaterom** [comment]
for error I understood it was just that I enter no comment (cannot be null) so all and ok for addition parconte I still do not understand how to add torrent clients

**Comment by xiaomlove** [comment]
OK, I'll have  a look

**Comment by Stargaterom** [comment]
thank you very much if you can help to find the info of the freebox Bittorrent 2.0 client.

**Comment by Stargaterom** [comment]
hello @xiaomlove , I solved my problem after several tests with the machine in question.

all and ok the customer and well accept.

thank you for all your help and the time you give me.

here is what must be put to agent for the person wishing to be added:

Peer ID start = -FX0200-
Peer ID pattern = /^-FX([0-9])([0-9])([0-9])([0-9])-/
Agent start = Freebox BitTorrent 2.0
Agent pattern = /^Freebox BitTorrent 2\.([0-9])/
