### ISSUE TITLE
not calculate downloaded functionality from a minimum class

### ISSUE THREAD

**Issue by Stargaterom** [xiaomlove/nexusphp#118]
hello, 
I wanted to know if it would be possible to add the not calculate downloaded functionality from a minimum class defined
because currently this function and use only for the VIP class.
![Screenshot_4](https://user-images.githubusercontent.com/107837857/195807419-3a9d5040-16f7-4eb3-8560-cdd02d4ec77f.png)
thank you in advance

**Comment by xiaomlove** [comment]
OK, it will be added soon.

**Comment by Stargaterom** [comment]
thank you very much for your answer its great

**Comment by Stargaterom** [comment]
Hello @xiaomlove , have you heard about the addition of this functionality in authorization settings to be able to choose from which class we wish to choose not to calculate the download cordially

**Comment by xiaomlove** [comment]
This feature needs a closer look

**Comment by Stargaterom** [comment]
ok very good thank you for your answer I let you work
