### ISSUE TITLE
上传头像会报错.

### ISSUE THREAD

**Issue by Mr-ByeBye** [xiaomlove/nexusphp#12]
Notice: Undefined index: public in /www/wwwroot/***/public/bitbucket-upload.php on line 57

![QQ截图20210421030915.png](https://i.loli.net/2021/04/21/ZEQDxjlTtAo4K8n.png)

之前还在其他地方遇到,我当时太忙没截图,也忘记是哪个界面了,我回头再找找.

环境是Nginx 1.13.6.2 |PHP 7.3|

另外方便留个更加方便的联系方式不,比如QQ或者Telegram之类的!

**Comment by xiaomlove** [comment]
新版中报错级别为 E_ALL，旧代码很多地方不严谨不判断变量是否存在直接使用。应该不是严重错误，不影响使用。
后续版本会修正，感谢反馈。
PS：博客上有联系方式。
