### ISSUE TITLE
.png in avatar upload = invalid extension error

### ISSUE THREAD

**Issue by LuciuzHQ** [xiaomlove/nexusphp#122]
Hi,

In the bitbucket-upload.php I have this line :
`$imgtypes = array (null,'gif','jpg','jpeg','png');`

But when I try to upload a .png picture, this error is showed:
**Invalid extension: gif, jpg or png only!**

Thanks.

**Comment by xiaomlove** [comment]
It's OK, you can check on demo site.

**Comment by LuciuzHQ** [comment]
I had to remove the . jpeg extension here :

` $imgtypes = array (null,'gif','jpg','jpeg','png');`
is now:
` $imgtypes = array (null,'gif','jpg','png');`

Now the .png extension is accepted.
Do you know why?

**Comment by xiaomlove** [comment]
please upload the same png image on demo site, is the problem exists?

**Comment by LuciuzHQ** [comment]
On demo site it works, but you probably don’t have the . jpeg extension in the bitbucket-upload.php code because it’s not normally there.
