### ISSUE TITLE
imdb info problem

### ISSUE THREAD

**Issue by Stargaterom** [xiaomlove/nexusphp#123]
hello @xiaomlove , after several months of testing on the latest version, on 6 uploads the imdb information is automatically reset every 7 days and left for 7 days without deleting the info, so I migrated from version 1.7.30 for our community and necessarily the upload number and not 6 since its 7 days I added the imdb to all the uploads in manual 1 by 1 and today the 7th day on an upload here is what the sie does to me.
![Screenshot_4](https://user-images.githubusercontent.com/107837857/198591283-54828c12-f94f-438b-a6f4-3a506273b74e.png)
when I click on this upload here is the imdb information which and display.
![Screenshot_5](https://user-images.githubusercontent.com/107837857/198592027-975c72b2-290e-448c-8b51-c3d40112c038.png)
we can see that the imdb info and always there with the poster and the update date and 2022-10-21 so it will be 7 days.

for some imdb releases still display my more cover and rating on the torrents page and for others of the same day the system has completely removed all the information.

I had made a return to you some months ago on this subject, the problem and surely due to a very large number of imdb and torrent.

because when I only had 6 torrents on my current development version, I didn't have a problem, do you have any idea what could be the problem and why it all wanted to purge or refresh the info every 7 days?

if for example if I but rather this configuraton: $this->outdate_time = 60*60*24*365; it would prevent the system from purging the info and not recovering the new info. 

in imdb_config.php I saw his lines his speaks of 7 days my I do not understand because it seems to me that the configuration and over a year

// out dated time for retrived info, (7 days for default)
    $this->outdate_time = 60*60*24*7;

**Comment by Stargaterom** [comment]
on the first image and the second the system, imdb information and arrive at 7 days the system therefore tried to update it and to purge my where it had to retrieve the new info a bug this product and therefore does not end and lets display the imdb info of image 2 mes for the time in the cache the files ttxxxxxx and no longer present and after what time it removes the info that is on the page because they are no longer in the cache.

**Comment by Skyline-007** [comment]
I have exactly the same problems.

@xiaomlove  do you have a solution to our problem ?

Will there be a fix in a future nexusphp update ?

**Comment by xiaomlove** [comment]
The imdb configuration has been set to cache without expiration, test if it works. Download [this file](https://github.com/xiaomlove/nexusphp/blob/1.7/nexus/Imdb/Imdb.php#L32) from the 1.7 branch to overwrite it.

**Comment by Stargaterom** [comment]
hello @xiaomlove , thank you for this modification I add them to my file, I also tested certain things on my side and had succeeded in blocking the purge like this. 

![Screenshot_1](https://user-images.githubusercontent.com/107837857/202122379-113c5a29-6043-4cc2-8fd9-affe5934268b.png)

my morning looking at it was not purged my date and time had to change so the system my updated the imdb information automatically when the date and exceed ?
