### ISSUE TITLE
新人考核被封日志加详情

### ISSUE THREAD

**Issue by cwinu** [xiaomlove/nexusphp#127]
如这样： 因考核不成功而被禁用，详细 下载不足: 3.766 GB (要求 50GB) 魔力值不足: 38.9 (要求 6000)

不是这样：未完成考核：新人考核(2022-10-06 12:00:06 ~ 2022-11-05 12:00:06)

**Comment by xiaomlove** [comment]
意义不大，告知是因为考核不通过已经足够。
