### ISSUE TITLE
user用户可以添加种子标签，设置了标签权限也没用

### ISSUE THREAD

**Issue by Howardnm** [xiaomlove/nexusphp#129]
![image](https://user-images.githubusercontent.com/55622355/200757365-f4ff65a0-c77f-422d-bd50-6be2318547db.png)

**Comment by Howardnm** [comment]
bug：没有办法限制user用户添加标签

**Comment by xiaomlove** [comment]
只有特殊标签（官方标签和零魔标签）可以设定权限。

**Comment by Howardnm** [comment]
设置了特殊标签，user用户还是可以选择：官方和禁转。
是我设置有问题吗？感谢指点【抱拳】
![image](https://user-images.githubusercontent.com/55622355/200905329-3133b5ae-519d-4264-b6e7-392b7afac408.png)
![image](https://user-images.githubusercontent.com/55622355/200905712-be585b7e-111c-47fc-a57e-0cdfc98d4d6e.png)

**Comment by xiaomlove** [comment]
权限设定里设定特殊标签分配的什么等级可以？

**Comment by xiaomlove** [comment]
权限设定里设定特殊标签分配的什么等级可以？好的我看下

**Comment by xiaomlove** [comment]
更新此文件至此 [版本](https://github.com/xiaomlove/nexusphp/blob/1.7/app/Models/Tag.php) 即可。

**Comment by Howardnm** [comment]
可以了，非常感谢！！
