### ISSUE TITLE
CSS searchsuggest.php

### ISSUE THREAD

**Issue by slrslr** [xiaomlove/nexusphp#13]
Hello,
OWASP ZAP reported CSS issue:

![https://i.postimg.cc/TddHbPNm/css-searchsuggest.webp](https://i.postimg.cc/TddHbPNm/css-searchsuggest.webp)

**Comment by xiaomlove** [comment]
Thanks for the feedback. After the investigation found that this URL has not been visited, and, what is the problem exactly?

**Comment by slrslr** [comment]
I do not know what is the problem, or if there is any. If yes, maybe it is about the searchsuggest.php q URL parameter to accept special characters/CSS:
`your-demo-domain.tld/searchsuggest.php?q=<img src="random.gif" onerror=alert(1)>`

**Comment by Rhilip** [comment]
`searchsuggest.php` is used by https://github.com/xiaomlove/nexusphp/blob/ba7e5030e994d5723d3fd5cf6a9fdfe48b8b522f/public/opensearch.php#L34
which is a Web technology for browser search.
You can get it's document from:
 - https://developer.mozilla.org/en-US/docs/Web/OpenSearch
 - https://github.com/dewitt/opensearch 

The example response are like this:

```json5
[
   "sea",  // search string
   [
      "sears",
      "search engines",
      "search engine",
      "search",
      "sears.com",
      "seattle times"
   ],  // search item which hit search string
   [
      "7,390,000 results",
      "17,900,000 results",
      "25,700,000 results",
      "1,220,000,000 results",
      "1 result",
      "17,600,000 results"
   ],  // search count for each item
   [
      "http://example.com?q=sears",
      "http://example.com?q=search+engines",
      "http://example.com?q=search+engine",
      "http://example.com?q=search",
      "http://example.com?q=sears.com",
      "http://example.com?q=seattle+times"
   ]  // link for each item
]
```

However NexusPHP only response the first three item of this array.

--------------------

I think this commit https://github.com/xiaomlove/nexusphp/commit/dfaf0a9015b6e592648abac645a8577bec1b9fd9#diff-b330f125d9de403e5952b9ae598dbd85822d497128d13187e07015a6ae27f8c8R9 fixed this issue for CSS attack, and this issue can be closed.

**Comment by Oha-you** [comment]
@slrslr is this another issue of the old NexusPHP codebase, similar to #23?
You should really stop wasting other people's time by creating issues unrelated to this project.
Consider closing both issues by yourself.
