### ISSUE TITLE
自定义字段类型为 checkbox 时，无法正确将数据储存至数据库

### ISSUE THREAD

**Issue by tanapok** [xiaomlove/nexusphp#130]
当自定义字段的**类型**设置为**checkbox**时，在使用该字段的种子的详情页（details.php）的自定义字段的位置，右侧列显示为空。

![图片](https://user-images.githubusercontent.com/25226381/202025151-a8104802-4f2d-484e-8e5d-d231974140b3.png)

排查之后发现，有问题的数据位于数据库的 `torrents_custom_field_values` 表中。相关数据的 `custom_field_value` 字段值为纯文本 Array。

![图片](https://user-images.githubusercontent.com/25226381/202025376-c164232d-db9c-4840-9a31-5995b4962091.png)

猜测原因可能是处理 checkbox 的数组时，对数组的处理有问题，将数组未经转换直接存入数据库了。而后因对应的数据库字段类型为 `mediumtext`，所以变成了纯文本 Array。

### 相关设置

fields.php
![图片](https://user-images.githubusercontent.com/25226381/202026253-fe5b4286-ec82-4231-81df-0066a3847202.png)

catmanage.php
![catmanage.php](https://user-images.githubusercontent.com/25226381/202026303-79265f34-7e24-4a46-bfe1-04e6598132b8.png)

settings.php
![settings.php](https://user-images.githubusercontent.com/25226381/202026397-25ec74cb-d767-4322-9f62-b582d0278e5f.png)

**Comment by xiaomlove** [comment]
更新 [此文件](https://github.com/xiaomlove/nexusphp/blob/1.7/nexus/Field/Field.php) 即可。
