### ISSUE TITLE
建议：将自定义字段中的选项调整为三个字段

### ISSUE THREAD

**Issue by tanapok** [xiaomlove/nexusphp#132]
![图片](https://user-images.githubusercontent.com/25226381/202253405-59706fbd-2726-48ed-9bf5-531a80e96100.png)

如图所示，自定义字段中的选项的设置中，每行只能设置**选项值**和**选项描述文本**。建议更改为三个字段：

- 选项值：可用作主键。
- 在种子上传页/种子编辑页的展示（upload.php / edit.php）：用于上传页/编辑页的展示。
- 在种子详情页的展示（details.php）：用于种子详情页的展示。

原因：

当自定义字段设置为图片时，大量图片的加载可能造成页面加载缓慢。如果根据上述建议作出修改后，我可以在编辑页面以文本代替图片供用户选择，可降低服务器负载，提升用户体验。

另一种典型的情况是当选项中包含图片，且自定义展示中的 CSS 对图片的展示方式进行了限制时（如，加圆角、对图片高度进行限制等）。如图所示。

![图片](https://user-images.githubusercontent.com/25226381/202255038-19276ce7-f607-4b26-94c2-93d00ad5ba49.png)

此时种子详情页的展示效果没有什么问题，图片对 CSS 作出了良好的响应。但在种子上传页/种子编辑页时，因为没有自定义展示中的 CSS 代码对图片的限制，图片的尺寸不受控制，也没有任何样式，可能导致布局混乱，且对用户来说也不是所见即所得的，对用户体验影响较为严重。

当然此种情况下，我可以在全局引入 CSS 对图片进行限制解决此问题。但若是作出上述的修改，可能会更好。

**Comment by xiaomlove** [comment]
你想实现什么样的效果？
自定义字段不宜搞得太复杂，它只是一个通用的辅助功能，也不能用于筛选。
