### ISSUE TITLE
topic_reply & hr_reached notification configurable 

### ISSUE THREAD

**Issue by Stargaterom** [xiaomlove/nexusphp#137]
hello, I have added your modifications to my box so as not to receive a notification from the forum remains checked after having unchecked and saved for the hr no problem the box is unchecked and its settings are kept I understand where the problem may come.
![Screenshot_1](https://user-images.githubusercontent.com/107837857/204039051-00743a1a-6a11-42d1-86f7-b87eee132611.png)

on another user the 2 boxes are unchecked my if I validate it and save after impossible to leave it unchecked

**Comment by xiaomlove** [comment]
Sorry, I don't understand.

**Comment by Stargaterom** [comment]
once activate the function I can no longer deactivate it by unchecking it and saving it

![Screenshot_4](https://user-images.githubusercontent.com/107837857/204043319-f7b4958a-ca66-4d2f-b2ae-f85bae091979.png)

for Notify me when H&R reaches target no problem I can activate and deactivate it the system saves my modification well each time

Is there an addition to make to the database because I stopped at version 1.7.30 and therefore I hope that its not linked to it otherwise it will be annoying

on another user the 2 options are not activated my if active Notify me when there are new replies to forum posts I can no longer remove.

![Screenshot_3](https://user-images.githubusercontent.com/107837857/204043173-b2d83af0-a287-4ab8-935f-51b07d02a471.png)

I unchecked all then saved my I still have (Notify me when there are new replies to forum posts) which remains checked

![Screenshot_5](https://user-images.githubusercontent.com/107837857/204043628-33db1fd4-5952-4ff2-9cc4-ac577ed6b046.png)
