### ISSUE TITLE
希望能倡导使用更新的Pt客户端

### ISSUE THREAD

**Issue by Jonnes** [xiaomlove/nexusphp#138]
现在pt站普遍支持的客户端，像Transmission，现在的稳定版3.0也是几年前的产品，编译常常报错，因为现在系统的依赖包版本太新，只有4.0可以正常安装。很多pt站长还是要求用老版本的程序，也跟不上时代，其实他们很多也不懂这方面的问题。如果nexusphp这边能做一些努力，在新的版本里鼓励他们支持更新的客户端，我想能够帮助很多。

**Comment by xiaomlove** [comment]
后台可以自己加，后续出个文章

**Comment by xiaomlove** [comment]
参考 [此文章](https://nexusphp.org/2023/03/06/add-allow-deny-clients/) 即可。
