### ISSUE TITLE
addition problem stylesheets 

### ISSUE THREAD

**Issue by Stargaterom** [xiaomlove/nexusphp#140]
hello, had deleted the styles from the database that did not need to display the problem when I wanted to put them back it no longer works. here is my page.

![Screenshot_1](https://user-images.githubusercontent.com/107837857/204618137-17a080a3-f270-4872-a60b-8c72b8a71d2f.png)

in domain error log i have this line : 

PHP Warning:  Undefined array key 7 in /xxxxx/xxxxx/xxxxx/include/functions.php on line 2368PHP message: 

PHP Warning:  Trying to access array offset on value of type null in /xxxxx/xxxxxxx/xxxxxx/include/functions.php on line 2396PHP 

PHP Warning:  Undefined variable $defcss in /home/weshmygood/tctg.pm/include/functions.php on line 2375" while reading response header from upstream.

so I don't know at all what I have to do to be able to remove this error linked to my creation of new styles.

![Screenshot_2](https://user-images.githubusercontent.com/107837857/204617335-4e4c2e84-561f-4a38-9dad-7023b14def9a.png)

![Screenshot_3](https://user-images.githubusercontent.com/107837857/204617355-e2db07ea-3a15-45e0-8df2-dd3e8b3743ef.png)

I want to make a style on halloween hihih so if you can help to be able to display it I could work on the css thank you in advance.

**Comment by xiaomlove** [comment]
default records: 
```
INSERT INTO `stylesheets` VALUES (2,'styles/BlueGene/','Blue Gene','','Zantetsu','HDBits clone'),(3,'styles/BlasphemyOrange/','Blasphemy Orange','','Zantetsu','Bit-HDTV clone'),(4,'styles/Classic/','Classic','','Zantetsu','TBSource original mod'),(6,'styles/DarkPassion/','Dark Passion','','Zantetsu',''),(7,'styles/BambooGreen/','Bamboo Green','','Xia Zuojie','Baidu Hi clone');
```

**Comment by Stargaterom** [comment]
hello, I put your line back in sql in the database my themes that were deleted the first time are not displayed correctly

is there something else to do because in the database they are well recorded in stylesheet and in the public/styles folder all the folders are there in chmod 777 or do you have to restart the total server to take the styles into account
![Screenshot_1](https://user-images.githubusercontent.com/107837857/204747458-5ab49dbf-c8d9-43ca-a3fe-84f7f098e959.png)

here are the errors that domain log gives me : 

PHP Warning:  Trying to access array offset on value of type null in /include/functions.php on line 2373PHP message:
PHP Warning:  Undefined variable $defcss in /include/functions.php on line 2375
GET /usercp.php?action=tracker&type=saved HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "tctg.pm", referrer: "https://xxxxxxx/usercp.php?action=tracker"

![Screenshot_3](https://user-images.githubusercontent.com/107837857/204754224-7a0d0b02-006f-41bf-96f1-6e97b4fbb622.png)
