### ISSUE TITLE
bug：注册后未邮箱验证的账号不能自动删除

### ISSUE THREAD

**Issue by 404reposter** [xiaomlove/nexusphp#149]
看到有**注册超时**功能，但是不知道是不是发挥上述作用的，如果是的话这个功能没法正常工作，如果不是麻烦加一个**注册后未邮箱验证的账号超过N天后自动删除**的功能，谢谢

**Comment by xiaomlove** [comment]
已收到。感谢反馈。

**Comment by xiaomlove** [comment]
1.7.34 已修复。
