### ISSUE TITLE
bug：建议添加超“非 SeedBox 最高限速”的家宽/校园网用户的白名单规则

### ISSUE THREAD

**Issue by 404reposter** [xiaomlove/nexusphp#153]
部分高校使用的中国科技网、中国教育和科研计算机网等运营商提供的校园网为上下对等，上传速度可以达到100MB/s；
部分地区运营商提供直播宽带，即便是家宽土豪也可以使用钞能力提升上传速度。

如果站点制定的规则是非 SeedBox 最高限速为50MB/s等低于100MB/s的规则，以上校园网、家宽用户将会被取消下载权限。各站做法为论坛区备案帖--家宽/校园网超站点限速的用户回帖备案--管理员根据提供的IP建立白名单。而v1.8无此功能，即便与管理备案，管理也只能选择1.放弃这些用户或者2.被迫修改站点规则。

因此，建议添加超“非 SeedBox 最高限速”的家宽/校园网用户的白名单规则

**Comment by xiaomlove** [comment]
白名单可以有，会考虑增加

**Comment by xiaomlove** [comment]
1.8 最新版已经添加
