### ISSUE TITLE
anyway to convert this website to public torrent tracker ?

### ISSUE THREAD

**Issue by trexw0w** [xiaomlove/nexusphp#156]
title.

**Comment by xiaomlove** [comment]
this is design for private tracker, you can open registration and close disable account function when low ratio.

**Comment by trexw0w** [comment]
I want to open up UDP in torrent files. can you just tell me which files to edit ?

**Comment by xiaomlove** [comment]
> I want to open up UDP in torrent files. can you just tell me which files to edit ?

not support
