### ISSUE TITLE
how can i get script to scrape stats of UDP tracker.

### ISSUE THREAD

**Issue by jatinchkumar** [xiaomlove/nexusphp#159]
Can you tell me which file to edit for UDP scraping. I can probably use $httpSeeds = $torrent->getHttpSeeds(); to get seeds using info hash.

**Comment by xiaomlove** [comment]
Not support, Only http

**Comment by jatinchkumar** [comment]
can you tell me which file to edit ? to allow multi tracker scraping.
edit: multi tracker

**Comment by xiaomlove** [comment]
PT always use one tracker
