### ISSUE TITLE
HTML description

### ISSUE THREAD

**Issue by SAGOnly** [xiaomlove/nexusphp#160]
NexusPHP can't create torrent descriptions in HTML?
I tried it here ... https://demo.nexusphp.org/details.php?id=51&hit=1
Thanks for info.

**Comment by xiaomlove** [comment]
Not support , use bbcode

**Comment by SAGOnly** [comment]
And do you plan to include and integrate this option in other new issued versions? Or should I look for a different solution? I have seen this option partially support for example XBTIT or UNIT3D Community Edition. In the 21st century of modern technologies, creating and displaying descriptions only through "BBCODE" is insufficient. In addition, when someone needs to insert extra HTML, JS or CSS elements in the description. You can check it yourself in HTML test page, for example here https://www.w3schools.com/html/tryit.asp?filename=tryhtml_intro
and insert my description "torrent_descripiton_html"
[torrent_description_html.txt](https://github.com/xiaomlove/nexusphp/files/10720625/torrent_description_html.txt)

**Comment by xiaomlove** [comment]
Currently do not consider modifying this piece, use the default bbcode that can be.
First, in order to maintain compatibility between various sites, mutual reproduction convenience.
Second, most of the descriptions are text, simple color bold, etc. has been met.

**Comment by SAGOnly** [comment]
Hello,
here's a preview of my adjustment

Custom modification of HTML Torrent description via iframe (bbcode EMBED), support HTML files includes CSS and JS or HTML files with external CSS and JS.
Files that you have stored on another storage, for example, a web cloud (**at your sole discretion**).
**Warning: This modification will disable all other BBcode**

Demonstration of HTML description on torrent
https://fmcloud.pro/managerfiles/lucifeeer.666/MyTorrents/ViveLaFrance/vlffinal.html

**open file include/functions.php**
**find row**
`345 $s = $text;`
**add after**
```
// Basic safety
	$text = htmlspecialchars($text);
	$text = str_replace("\n", "<br>", $text);

// [embed]URL[/embed] only for .html files and allowed domains
	$text = preg_replace_callback("/\[embed\](https?:\/\/[^\s\"'\[\]]+)\[\/embed\]/i", function($matches) {
	$url = $matches[1];
	$allowed_domains = ['example.com', 'example1.com']; // <- Modified as needed

	$log_file = __DIR__ . '/../embed_log.txt'; // Path to logging file (default location is "nexusphp" folder)

// Auxiliary function for logging
        function log_embed_error($reason, $url, $log_file) {
        $time = date("Y-m-d H:i:s");
        $ip = $_SERVER['REMOTE_ADDR'] ?? 'unknown';
        $log = "[$time] [$ip] $reason: $url" . PHP_EOL;
        file_put_contents($log_file, $log, FILE_APPEND);
        }


// Extract the domain
	$host = parse_url($url, PHP_URL_HOST);
        if (!$host) {
	log_embed_error('Invalid URL', $url, $log_file);        
	return '<div style="color:crimson; text-align:center;font-weight: bold;font-size: 14px;font-family: arial black;background-color: #f4e48d;">🔴 Invalid URL</div>';
        }

// Cut subdomains (eg. www.example.com -> example.com)
	$host_parts = explode('.', $host);
	$domain = implode('.', array_slice($host_parts, -2));

// Verify the domain
	if (!in_array($domain, $allowed_domains)) {
	log_embed_error('Domain (' . $domain . ') it is not allowed for external descriptions.', $url, $log_file);	
	return '<div style="color:crimson; text-align:center;font-weight: bold;font-size: 14px;font-family: arial black;background-color: #f4e48d;">🔴 Domain ' . htmlspecialchars($domain) . ' it is not allowed for external descriptions.</div>';
        }

// Verify the extension .html or .htm
	$path = parse_url($url, PHP_URL_PATH);
	if (!preg_match('/\.html?$/i', $path)) {
	log_embed_error('Unsupported format (only HTML files are enabled)', $url, $log_file);	
	return '<div style="color:crimson; text-align:center;font-weight: bold;font-size: 14px;font-family: arial black;background-color: #f4e48d;">🔴 Unsupported format - only HTML files are enabled<br>CSS and JavaScript can be inserted directly into HTML or externally.</div>';
        }

// Everything is fine - Iframe is inserted
	return "<iframe src=\"$url\" width=\"100%\" height=\"768\" frameborder=\"0\" allowfullscreen></iframe>"; // <- Width and height can be set manually
	}, $text);
	return $text;
```

**find row**
`821 var html_open = 0;`
**add after**
`var embed_open = 0;`

**find row**
`1127 </select></td></tr>`
**and replace for**
`</select></td><td class="embedded"><input class="codebuttons" type="button" name="embed" value="EMBED" onclick="javascript: simpletag('embed')" /></td></tr>`

**Demonstration**
```
allowed [embed]https://example.com/page.html[/embed] - ✅ Iframe appears
allowed [embed]https://example.com/page.xhtml[/embed] - ✅ Iframe appears
denied  [embed]https://example.com/file.pdf[/embed] - ❌ Error message: "Unsupported format"
denied  [embed]https://evil.com/page.html[/embed] - ❌ Error message: "Domain it is not allowed"
```

**What will be logged in to the file (last 100 records)**
⛔ **Each unsuccessful attempt to insert [Embed] if:**
+ Used an unauthorized domain
+ Used an unsupported format (not html)
+ Invalid URL is used
 
🧾 **The log file is written and stored:**
+ Time and date
+ User IP address (if available)
+ Reason for error
+ Original URL

🔍 Search in logs (text, IP, domain, error type)
🧹 Clear log button
🔐 Admin-only access (get_user_class())
🏠 Return to main admin panel button (e.g., index.php)

The embed_log.txt log setting file will be stored in the same folder as the include/functions.php (unless another way is defined).
Log sample:
```
[2025-10-15 12:34:56] [192.168.1.5] Invalid URL (malicious.com): https://malicious.com/fake.html
[2025-10-15 12:35:02] [192.168.1.5] Unsupported format (only HTML files are enabled): https://example.com/script.php
```

Make sure PHP has the right to write to the embed_log.txt file.
If it does not exist, PHP creates it - otherwise set rights manually permission:
chmod 664 embed_log.txt or chown www-data:www-data embed_log.txt  // According to the server

**SysOp (administrator) show log file and clear records** 
create file "**admin_embed_log.php**" and upload to dir "public"

```
<?php
// ----------------------
// ADMIN EMBED LOG TOOL
// ----------------------

require_once(__DIR__ . '/../include/bittorrent.php');
dbconn();
loggedinorreturn();

// 🔐 Only SysOps can access
	if (get_user_class() < UC_SYSOP) {
    	stderr("Access Denied", "You do not have permission to access this tool.");
    	exit;
	}

	$log_file = __DIR__ . '/../embed_log.txt';
	$message = "";

// 🧹 Clear the log
	if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['clear_log'])) {
    	if (file_exists($log_file)) {
        file_put_contents($log_file, '');
        $message = "Log has been successfully cleared.";
    }
}

// 🔎 Get filters from URL
	$search_term    = trim($_GET['search'] ?? '');
	$filter_ip      = trim($_GET['ip'] ?? '');
	$filter_domain  = trim($_GET['domain'] ?? '');
	$filter_error   = trim($_GET['error'] ?? '');

// 📥 Read log entries
	$log_entries = [];
	if (file_exists($log_file)) {
    	$log_entries = file($log_file, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
    	$log_entries = array_reverse($log_entries); // Latest first

// 🔍 Apply filters
        $log_entries = array_filter($log_entries, function ($line) use ($search_term, $filter_ip, $filter_domain, $filter_error) {
        $match = true;

        if ($search_term && stripos($line, $search_term) === false)
            $match = false;

        if ($filter_ip && stripos($line, $filter_ip) === false)
            $match = false;

        if ($filter_domain && stripos($line, $filter_domain) === false)
            $match = false;

        if ($filter_error && stripos($line, $filter_error) === false)
            $match = false;

        return $match;
    });
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Embed Log – Admin Panel</title>
    <style>
        body { font-family: Arial, sans-serif; background: #f9f9f9; padding: 20px; }
        h1 { color: #333; }
        .log-box {
            background: #fff;
            border: 1px solid #ccc;
            padding: 15px;
            max-height: 500px;
            overflow-y: auto;
            font-family: monospace;
            white-space: pre-wrap;
            margin-top: 15px;
        }
        .btn {
            display: inline-block;
            padding: 8px 12px;
            background: #d9534f;
            color: white;
            border: none;
            cursor: pointer;
            border-radius: 3px;
            text-decoration: none;
        }
        .btn-blue {
            background: #5bc0de;
        }
        .btn-green {
            background: #5cb85c;
        }
        .message {
            padding: 10px;
            background: #dff0d8;
            color: #3c763d;
            border: 1px solid #d6e9c6;
            margin-bottom: 15px;
            border-radius: 3px;
        }
        form.filter-form input {
            margin: 5px;
            padding: 6px;
        }
        form.filter-form {
            background: #eee;
            padding: 10px;
            border-radius: 5px;
        }
        .button-row {
            margin-top: 20px;
        }
    </style>
</head>
<body>

    <h1>📋 Embed Log – Admin Tool</h1>

    <?php if (!empty($message)): ?>
        <div class="message"><?= htmlspecialchars($message) ?></div>
    <?php endif; ?>

    <!-- 🔍 Filter Form -->
    <form method="get" class="filter-form">
        <input type="text" name="search" placeholder="Search text..." value="<?= htmlspecialchars($search_term) ?>">
        <input type="text" name="ip" placeholder="Filter by IP" value="<?= htmlspecialchars($filter_ip) ?>">
        <input type="text" name="domain" placeholder="Filter by domain" value="<?= htmlspecialchars($filter_domain) ?>">
        <input type="text" name="error" placeholder="Filter by error type" value="<?= htmlspecialchars($filter_error) ?>">
        <button type="submit" class="btn btn-green">🔍 Filter</button>
        <a href="admin_embed_log.php" class="btn btn-blue">🔄 Reset</a>
    </form>

    <!-- 📄 Log Output -->
    <?php if (!empty($log_entries)): ?>
        <div class="log-box">
            <?= htmlspecialchars(implode("\n", array_slice($log_entries, 0, 100))) ?>
        </div>
    <?php else: ?>
        <p>❗ No log entries match your filters.</p>
    <?php endif; ?>

    <!-- 🧹 & 🏠 Action Buttons -->
    <div class="button-row">
        <form method="post" style="display:inline;" onsubmit="return confirm('Are you sure you want to clear the entire log?');">
            <button class="btn" name="clear_log" type="submit">🧹 Clear Log</button>
        </form>
        <a href="index.php" class="btn btn-blue">🏠 Return to the main page</a>
    </div>

</body>
</html>
```

**Button second navbar**
**open file include/functions.php
find row 2723**
`<?php if(get_user_class() >= \App\Models\User::getAccessAdminClassMin()) printf('[<a href="%s" target="_blank">%s</a>]', nexus_env('FILAMENT_PATH', 'nexusphp'), $lang_functions['text_management_system'])?>`
**add after**
`<?php if (get_user_class() >= UC_SYSOP): ?><a href="./admin_embed_log.php" style="color:crimson;">EL</a><?php endif; ?>`

Screens
https://fmcloud.pro/managerfiles/lucifeeer.666/MyTorrents/ViveLaFrance/sc1.jpg
https://fmcloud.pro/managerfiles/lucifeeer.666/MyTorrents/ViveLaFrance/sc2.jpg
https://fmcloud.pro/managerfiles/lucifeeer.666/MyTorrents/ViveLaFrance/sc3.jpg
https://fmcloud.pro/managerfiles/lucifeeer.666/MyTorrents/ViveLaFrance/sc4.jpg

Best Regards
SAGOnly

**Comment by SAGOnly** [comment]
Hello,
**updating the complete functions.php file** (at your sole discretion)
Custom modification of HTML Torrent description via iframe (bbcode EMBED), support HTML files includes CSS and JS or HTML files with external CSS and JS. Files that you have stored on another storage (you can manually set which domains will be allowed), for example, a web cloud.
**Notice: BBcode should be functional and usable, including newly added ones (I have tested).** 

[en_functions_final.php](https://github.com/user-attachments/files/22977514/en_functions_final.php)

Best Regards
SAGOnly
