### ISSUE TITLE
BUG: 管理界面关于HR免除/删除失效的问题

### ISSUE THREAD

**Issue by baozaodetudou** [xiaomlove/nexusphp#162]
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/37683726/220036196-36691308-90a7-4657-82bc-f09202f1fc59.png">
如图，两个按钮均不生效，但是在列表页多选可以进行删除或者免除
账号等级：维护开发员
HR状态为： 未达标

**Comment by xiaomlove** [comment]
经测试，未达标的是可以正常免罪和删除的。
