### ISSUE TITLE
能修复一下对宝塔自建邮局的支持吗？

### ISSUE THREAD

**Issue by ArthurHDF** [xiaomlove/nexusphp#164]
目前1.7.33或者1.8版本中，使用QQ邮箱发邀请或者其他站点邮件会在邮件详情那里暴露站点IP。

而使用其他网易邮箱、google邮箱、QQ企业邮箱都会有一些不便或者限制。

另外，使用自建邮局可以使用一个单独的VPS来建立，不暴露源站IP，还可以有admin@XXX.org的命名，比较正式。

希望可以修复一下。

**Comment by xiaomlove** [comment]
IP 这个是邮件服务商的原因，跟代码无关

**Comment by ArthurHDF** [comment]
我做了几个步骤来验证，1、宝塔邮局重新安装4.9版本。2。CF的关于邮局的设置按照新装的宝塔邮局来设置，原来的全部删除了。3、测试了宝塔自带的发送功能，正常。4、使用foxmail建立宝塔的账号发送邮件正常，5、网站主要设置已经使用宝塔自建的邮箱，SMTP也设置了，加密选none。6、使用NP自带的邮件测试还是显示无法发送邮件。

**Comment by xiaomlove** [comment]
正确设置好加密方式，有错误看日志才能针对性解决。
