### ISSUE TITLE
SearchBox Panel

### ISSUE THREAD

**Issue by SAGOnly** [xiaomlove/nexusphp#165]
In the Torrent search panel, it is currently possible to search for
Source, Media, Codec, Audiocodec, Standard, Processing, Team.
It would still like to add a search option ...
**Movies and TV series, (for example: english dub, spain titles)**
**... according to the language of dubbing and language subtitles**
**Software and Games (for example: windows,linux,english,spain)**
**... according to the operating system and the language of the game**
They are going to make classic Tags or Custom Fields.
👎 But according to the Tags it is search for it in all categories at once
👎 According to Custom Fields it does not search at all.
Thank you for the info.

**Comment by xiaomlove** [comment]
In 1.8, the 7 fields Source, Media, Codec, Audiocodec, Standard, Processing, Team are customizable with names and options, for example you can use the Source field for Platform and configure Windows/Linux options for it.

**Comment by SAGOnly** [comment]
Of course I know that it is possible to rename or add other items, I tried to rename it, but it has not changed in the URL.
The names still appear the same. So will you also need to edit PHP files?
domain.tld/torrents.php?**medium**=1
domain.tld/torrents.php?**codec**=1
domain.tld/torrents.php?**standard**=1
domain.tld/torrents.php?**team**=1

**Comment by xiaomlove** [comment]
It's okay to appear in the URL, you don't have to dwell on this
