### ISSUE TITLE
Chronicle log

### ISSUE THREAD

**Issue by SAGOnly** [xiaomlove/nexusphp#171]
After adding the event to the Chronicle log, it is no longer possible to work with this notes, when clicking on the "Edit" or "Delete" buttons to see "Error Invalid Action" appears. The only option to remove or editing an event is directly in the SQL database.
![chro1](https://user-images.githubusercontent.com/90079674/225284204-925f7ba0-c513-4418-ad39-8f19a67f47e4.png)
![chro2](https://user-images.githubusercontent.com/90079674/225284220-0a8d259e-b761-4b9a-9631-d70151a37f80.png)

**Comment by xiaomlove** [comment]
Which URL ?

**Comment by SAGOnly** [comment]
https://torr.live

**Comment by xiaomlove** [comment]
I said which path are you using for this page, something like details.php. Are you sure you're using my program? I don't think I've seen this page before.

**Comment by SAGOnly** [comment]
log.php?action=chronicle
log.php?action=chronicle?action=chronicle&do=edit&id=
log.php?action=chronicle?action=chronicle&do=del&id=

**Comment by xiaomlove** [comment]
Got it

**Comment by xiaomlove** [comment]
latest commit fixed.

**Comment by SAGOnly** [comment]
Thank you very much for your willingness and help 💯 👍
