### ISSUE TITLE
抽中7天VIP后，再手动赋予发布员级别会有小BUG

### ISSUE THREAD

**Issue by ArthurHDF** [xiaomlove/nexusphp#178]
有网友反馈，原级别是VU，在2023年4月3日通过幸运大抽奖抽中7天VIP，接着在2023年4月6日被管理员手动提升至发布员级别，到了4月10日，7天VIP到期后，该网友的级别降到了普通的VU，发布员的级别没有保留。

**Comment by ArthurHDF** [comment]
补充一个同类问题，有会员在2022年获得管理员手动提升至UU级别，抽中7天VIP并过期后，级别只会恢复到满足升级条件的IU，而非管路员手动提升的UU级别。

**Comment by xiaomlove** [comment]
问题1已修复，VIP 以上不会再降级。
问题2无法解决，VIP 以下等级是跟随数据变动的，不能手动调整等级。
