### ISSUE TITLE
有计划做个对接steam的插件吗？

### ISSUE THREAD

**Issue by pks1999666** [xiaomlove/nexusphp#179]
就是和豆瓣那样，对接steam，这样对做游戏站的有很大作用，谢谢

**Comment by xiaomlove** [comment]
请查看ptgen的支持

**Comment by xiaomlove** [comment]
https://github.com/Rhilip/pt-gen-cfworker

**Comment by pks1999666** [comment]
大佬，这个好像失效了？

**Comment by xiaomlove** [comment]
你可以找一些第三方的信息来源，或者官方的 [这个](https://steamcommunity.com/dev/apikey)。
有来源才可以做，你调研一下。
来源搞得定可以考虑做个插件，但是是收费的。
