### ISSUE TITLE
关于隐私论坛版块引用导致原帖内容暴露的问题

### ISSUE THREAD

**Issue by ArthurHDF** [xiaomlove/nexusphp#182]
Nexusphp将某个版块设置成只有楼主、回帖层主本人、管理员及以上人员可以查看后，非拥有查看权限的其他人，引用帖子内容后可以将原来的帖子内容呈现在发帖框，从而形成了原帖内容暴露的情况。

**Comment by xiaomlove** [comment]
v1.8.1 已修复
