### ISSUE TITLE
Category icons disappear when choosing not to use icons

### ISSUE THREAD

**Issue by MasterPlebien** [xiaomlove/nexusphp#185]
Hello, I have been looking for a way for the categories to just be in text but it cannot be done in management as icon has to be selected. So, I tried other methods but I am unable to get it to work. Is there anyway to disable icons and just use text instead?

![image](https://user-images.githubusercontent.com/131825512/234417783-6cdb887f-ec17-4ea2-a960-998be21a226d.png)

I'm trying to get the "Category" to appear similar to the others.

**Comment by xiaomlove** [comment]
Because the leftmost part of the torrent list needs to display the category, the category needs to bring an icon, currently does not support not to display this icon, the beginning of the design is this
