### ISSUE TITLE
Custom field enable checkbox missing ?

### ISSUE THREAD

**Issue by LuciuzHQ** [xiaomlove/nexusphp#200]
Hello,

Is it not need to have a checkbox to enable the custom field option in the dashboard ?

![field](https://github.com/xiaomlove/nexusphp/assets/90622803/ac2f3ef9-eb78-45ec-9433-1c551a36feb2)

Thanks

**Comment by xiaomlove** [comment]
don't understand, more screenshot and detail description please

**Comment by LuciuzHQ** [comment]
![YT](https://github.com/xiaomlove/nexusphp/assets/90622803/618b26b7-f75c-4caf-8e45-f35a49cae8bd)

This checkbox is not existing in the new dashboard, in the search box section.

**Comment by xiaomlove** [comment]
in the new dashboard, in the search box section. screenshot please

**Comment by LuciuzHQ** [comment]
![check](https://github.com/xiaomlove/nexusphp/assets/90622803/17400637-d9dd-44c2-be7e-c9398b338d8e)

No checkbox about it.

**Comment by xiaomlove** [comment]
You need to create custom fields first

**Comment by xiaomlove** [comment]
anything else?
