### ISSUE TITLE
Spoiler bbcode换行失效

### ISSUE THREAD

**Issue by 2427768286** [xiaomlove/nexusphp#209]
![image](https://github.com/xiaomlove/nexusphp/assets/74432624/0b4dcfb1-c8b5-47ea-b32d-99ee0193681e)
![image](https://github.com/xiaomlove/nexusphp/assets/74432624/a9e1ef1e-cd44-4347-b769-457460f5ddd4)

**Comment by xiaomlove** [comment]
1.8.4 已经解决，你看一下
