### ISSUE TITLE
关于1.5版本如何在新建的1.8版本直接导入数据库文件

### ISSUE THREAD

**Issue by teolinkiat** [xiaomlove/nexusphp#210]
请问如果已安装1.8版本，如何导入1.5版本的数据库文件，我试了直接导入是不行的。

**Comment by xiaomlove** [comment]
参考升级 1.6 的文档，适用于直接升级最新版。只是到最后一步(step 4 Perform updates)时，不要点击 Next 了 ，务必通过执行命令行完成：
```
php artisan nexus:update
```
如果搞不定，可以联系我，各种修改版本不太一样，有可能还得修改代码以适配。

**Comment by xiaomlove** [comment]
还有，升级后，务必把 peers 等大表改为 InnoDB 引擎，具体参考 [博客文章](https://nexusphp.org/2022/04/22/peers-engine-memory-to-innodb/)。

**Comment by teolinkiat** [comment]
谢谢大佬回复，还有就是如果有两个1.5的数据库需要合并在一起然后导入1.8里应该如何操作？麻烦大佬了。

**Comment by xiaomlove** [comment]
不可以。只能手工而且非常麻烦，建议只留一个。
