### ISSUE TITLE
管理系统权限打不开，报错！

### ISSUE THREAD

**Issue by huguangjun580** [xiaomlove/nexusphp#214]
![30e9e9b209fdd1aff8a01d529745991](https://github.com/xiaomlove/nexusphp/assets/14951832/0a2a7c9a-bd3c-4c19-8a55-af8ebc2a585a)

搭建成功后，登录后台，点击操作，跳转页面报500错误。v:1.8.4版本。
备注：关于是不是环境问题，我想不至于，如果环境有问题那么一开始就应该搭建失败，连首页都打开不了，为此还专门又重新部署安装了一次，结果还是如此。

**Comment by huguangjun580** [comment]
隔了一晚上，第二天可以正常打开了。就很神奇。

**Comment by xiaomlove** [comment]
先把文档和博客全看一遍。https://doc.nexusphp.org/faq.html#%E7%AE%A1%E7%90%86%E5%90%8E%E5%8F%B0-500-%E9%94%99%E8%AF%AF

**Comment by huguangjun580** [comment]
@xiaomlove 1、隔了一晚上，第二天可以正常打开了，就很神奇。2、网站正常打开后，关闭系统开放注册，然后只允许邀请才可以注册，新用户怎么才能拥有邀请资格呢？在哪里设置阿，这个我在文档里面没找到。3、我想知道如何手动给某个用户去充值魔力值（如何设置）。

**Comment by xiaomlove** [comment]
日志按天生成的，第二天生成的没有权限问题。这里不是讨论这些问题的地方，建议加群讨论。
