### ISSUE TITLE
[code] bbcode 换行失效

### ISSUE THREAD

**Issue by 2427768286** [xiaomlove/nexusphp#215]
![image](https://github.com/xiaomlove/nexusphp/assets/74432624/d8cf51c9-e7f1-49f5-acf8-cdaf7e373505)

![image](https://github.com/xiaomlove/nexusphp/assets/74432624/c4c806af-ca08-4c09-948a-71bf5c6aaaaa)

**Comment by xiaomlove** [comment]
之前不是提过一次吗？

**Comment by xiaomlove** [comment]
最新提交已处理
