### ISSUE TITLE
我建的pt站上的东西，下载没速度

### ISSUE THREAD

**Issue by yyhjop** [xiaomlove/nexusphp#217]
为啥我发在我建的pt站上的东西下载没速度，而别人有的人可以

**Comment by yyhjop** [comment]
Banned Client, Please goto https://00gi.com/faq.php#id29 for a list of acceptable clients

**Comment by yyhjop** [comment]
我用的是qb客户端可是显示没速度，Banned Client, Please goto https://00gi.com/faq.php#id29 for a list of acceptable clients然后显示

**Comment by xiaomlove** [comment]
这里只讨论功能需求，bug反馈，不要发布这类基本的使用问题。百度搜索或者相关社区，讨论群等都能找到答案。
