### ISSUE TITLE
IMDb no poster

### ISSUE THREAD

**Issue by maximuml** [xiaomlove/nexusphp#22]
![IMG_20210714_224118](https://user-images.githubusercontent.com/9083083/125682931-e63110d5-f78e-4c47-954f-bf82ac661555.jpg)
Can't parse poster for torrent from IMDb
Also got this error 
```pic/nophoto.gif"` failed (2: No such file or directory), client: 192.168.1.1, server: test.host, request: "GET /pic/nophoto.gif```

**Comment by lioumin1** [comment]
composer update
