### ISSUE TITLE
建议增加因盒子超速被取消下载权限的期限

### ISSUE THREAD

**Issue by ArthurHDF** [xiaomlove/nexusphp#220]
目前，由于用户使用盒子不当导致被系统自动取消下载权限的情况需要管理员手动解封，这增加了管理工作，希望能增加自动取消下载权限的时间限制，变成在后台如同HR一样可以全局设置多少天后自动解封。

**Comment by xiaomlove** [comment]
- 过早的解除可能用户无感知，用户可能十天半个月看一次，可能没看到权限被取消又恢复了
- 开发角度也不好实现，当前标记是否有下载权限是在用户表，该表为大表字段也已经很多，为这个功能增加字段没必要
