### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by xqw8889** [xiaomlove/nexusphp#223]
建议记录汇报客户端的一些基本信息
修复越权清空邮箱地址问题

**Comment by xiaomlove** [comment]
第2点实测无此问题。当管理员无查看用户机密档案权限时，警告用户不会清空用户邮箱。

**Comment by xiaomlove** [comment]
第1点没有想到什么好方案，汇报数据较多，如何记录以及记录哪些数据请给出方案探讨。
