### ISSUE TITLE
建议增加升级等级时发种数量要求

### ISSUE THREAD

**Issue by xzygreen** [xiaomlove/nexusphp#225]
建议增加升级等级时发种数量要求， 有些用户直接用盒子刷完流以后，不做种就直接删除做种，建议可以增加一个上传种子的等级要求

**Comment by xiaomlove** [comment]
发种一直可以设置一定等级才可以发

**Comment by xzygreen** [comment]
我意思是升级等级加一个发种要求

猫的   POWER USER | 加菲猫 | 注册时间大于 5 周，下载量大于 50 GB，分享率大于 1.05，做种积分大于10,000且**_发布种子数大于10_**
※只统计审核通过并且存活的种子，下同。

**Comment by xiaomlove** [comment]
这容易出现当初“变脸空”的状况，你得想个方案避免。
