### ISSUE TITLE
bug: 签到日期错位

### ISSUE THREAD

**Issue by k3-cat** [xiaomlove/nexusphp#228]
似乎补签功能依赖用户浏览器端的本地时间  如果用户本地时区和服务器时区不一致就会导致补签的错位
建议在渲染时把日期硬编码到按钮上  或者在两端都使用UTC时间戳

**Comment by xiaomlove** [comment]
详细截图说明

**Comment by k3-cat** [comment]
举例来讲
服务器的时区是UTC+8北京时间  我的时区是UTC+10
如果我点下图的这个按钮
<img width="563" alt="image" src="https://github.com/xiaomlove/nexusphp/assets/15878537/425b0d72-90d7-41e3-a5fe-caace7aa2c14">
期待的行为是补签在9月16日  而实际情况是会补签在9月15日

我判断的依据是console里log的object  如下图
<img width="646" alt="image" src="https://github.com/xiaomlove/nexusphp/assets/15878537/e0a7c5eb-83e8-401c-a7c8-a148c1dd5793">
这个start的时间点  是我本地时区的9月16日0点  但是在北京时间下的日期刚好是9月15日
也就对应上了签到错位的现象

**Comment by xiaomlove** [comment]
好的，后面修复一下

**Comment by xiaomlove** [comment]
最新提交已处理此问题，看看是否已经可以了。
