### ISSUE TITLE
文档建议

### ISSUE THREAD

**Issue by RebornForPower** [xiaomlove/nexusphp#229]
建议文档中增加一些分布式和集群部署的内容。

如果改成集群部署，直接修改NGINX的下面挂的主机就行？或者说程序支持分布式部署吗？会不会存在分布式事务的一些问题（如没有加分布式锁之类的问题）？

感谢支持~

**Comment by xiaomlove** [comment]
目前没有相关实践。上个配置好点的单机100w同伴是可以的，绝大部分站点到不了这个数据。另外 ，你说的分布式部署是指什么样的？希望具体一点。
