### ISSUE TITLE
[Request] Added [img] [/img] tag button for the shoutbox ?

### ISSUE THREAD

**Issue by Skyline-007** [xiaomlove/nexusphp#231]
Good morning

I would like to know if it would be possible to add a "button" with the [img] [/img] tag to the shoutbox ?

To view external link images from the shoutbox.

Example :
![Shoutbox](https://github.com/xiaomlove/nexusphp/assets/108820368/402232c9-df41-4004-bfb8-62737e343ebf)

If we click on the "IMG" button this opens a window to add the link to the external image
![link](https://github.com/xiaomlove/nexusphp/assets/108820368/d89b2de7-eff1-4c1b-bbf4-f2cd58e7c4f7)

Or

If we click on the "IMG" button, this puts the [img] [/img] tags on the shoutbox and all we have to do is paste the link of the external image between the two tags.
![shoutbox1](https://github.com/xiaomlove/nexusphp/assets/108820368/4687e77e-d11c-495a-a952-af091f227f94)

This will make the external image visible on the shoutbox.
Example :
![Shoutbox2](https://github.com/xiaomlove/nexusphp/assets/108820368/ffd51b0d-51e6-4595-acdb-85b825937cc8)

Thank you in advance for your answers and all the work you do.

**Comment by Skyline-007** [comment]
@xiaomlove can we get an answer from you ?
Will this option be available in a future nexusphp update ?

**Comment by xiaomlove** [comment]
There will be security issues
