### ISSUE TITLE
[help]I have a problem with the cleanup crontab

### ISSUE THREAD

**Issue by Stargaterom** [xiaomlove/nexusphp#232]
the site works very well, until I faced a problem with apt update and apt upgrade, it updated my ubuntu 20.02 to 20.04.

well the site is still running but the cleanup no longer works, I have my cron created in user www-data with the following line : 
* * * * * cd /xxxxxx/xxxxxxxx/xxxxx && php artisan schedule:run >> /tmp/schedule_DOMAIN.log
* * * * * cd /xxxxxx/xxxxxxxx/xxxxx && php include/cleanup_cli.php >> /tmp/cleanup_cli_DOMAIN.log

my syslog file indicates the cron task : 

Oct 20 14:07:01 sr CRON[53306]: (www-data) CMD (cd /xxxxxx/xxxxxxxx/xxxxxxx && php include/cleanup_cli.php >> /tmp/cleanup_cli_DOMAIN.log)
Oct 20 14:07:01 sr CRON[53307]: (www-data) CMD (cd /xxxxxx/xxxxxxx/xxxxxxx&& php artisan schedule:run >> /tmp/schedule_DOMAIN.log)

in the file:
/tmp/cleanup_cli_DOMAIN.log
it remains empty no stain and add

if I do the manual cleanup by not passing the staff panel no problem the cleanup executes my more avac the automatic task could help you to resolve the problem .

the problem may be with php artisan schedule ?

Thank you Best regards

**Comment by xiaomlove** [comment]
is your cron runs OK ?  try run: `service cron status`

**Comment by Stargaterom** [comment]
here is what the command gives me

● cron.service - Regular background program processing daemon
     Loaded: loaded (/lib/systemd/system/cron.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2023-10-20 15:12:46 CEST; 2s ago
       Docs: man:cron(8)
   Main PID: 83731 (cron)
      Tasks: 1 (limit: 38291)
     Memory: 328.0K
     CGroup: /system.slice/cron.service
             └─83731 /usr/sbin/cron -f

Oct 20 15:12:46 sr systemd[1]: Started Regular background program processing daemon.
Oct 20 15:12:46 sr cron[83731]: (CRON) INFO (pidfile fd = 3)
Oct 20 15:12:46 sr cron[83731]: (CRON) INFO (Skipping @reboot jobs -- not system startup)

**Comment by xiaomlove** [comment]
It looks well, you can add a simple task to check if runs well, such as ` * * * * * echo "test \n" >> /tmp/test.log`

**Comment by Stargaterom** [comment]
here is the path to the crontab: 
/var/spool/cron/crontabs/www-data

I added your line and I got the following error: 

Oct 20 15:22:10 sr systemd[1]: Started Regular background program processing daemon.
Oct 20 15:22:10 sr cron[86559]: (CRON) INFO (pidfile fd = 3)
Oct 20 15:22:10 sr cron[86559]: (www-data) ERROR (Missing newline before EOF, this crontab file will be ignored)
Oct 20 15:22:10 sr cron[86559]: (CRON) INFO (Skipping @reboot jobs -- not system startup)

**Comment by Stargaterom** [comment]
I removed my lines and added your test line and it was created and inside there was a test written:

Oct 20 15:41:58 sr cron[112278]: (CRON) INFO (pidfile fd = 3)
Oct 20 15:41:58 sr cron[112278]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 20 15:42:02 sr CRON[112289]: pam_unix(cron:session): session opened for user www-data by (uid=0)
Oct 20 15:42:02 sr CRON[112290]: (www-data) CMD (echo "test \n" >> /tmp/test.log)
Oct 20 15:42:02 sr CRON[112289]: pam_unix(cron:session): session closed for user www-data

**Comment by Stargaterom** [comment]
I put the following lines back and save

* * * * * cd /var/site/xxxx.com && php artisan schedule:run >> /tmp/schedule_DOMAIN.log
* * * * * cd /var/site/xxxx.com && php include/cleanup_cli.php >> /tmp/cleanup_cli_DOMAIN.log

the status displays this: 

Oct 20 15:53:51 sr systemd[1]: Started Regular background program processing daemon.
Oct 20 15:53:51 sr cron[134391]: (CRON) INFO (pidfile fd = 3)
Oct 20 15:53:51 sr cron[134391]: (CRON) INFO (Skipping @reboot jobs -- not system startup)

my nothing concerning my order add in the www-data should I add include in the redirection or php include does it directly because my direction I stop at my nexus folder.

**Comment by Stargaterom** [comment]
in schedule_DOMAIN.log I have this error but I don't know how to resolve it and link it to Laravel if I understood correctly

  TypeError 

  Carbon\Carbon::setLastErrors(): Argument #1 ($lastErrors) must be of type array, bool given, called in /xxxxx/xxxxxxxx/xxxxx/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php on line 98

  at vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:928
    924▕      * @param array $lastErrors
    925▕      *
    926▕      * @return void
    927▕      */
  ➜ 928▕     private static function setLastErrors(array $lastErrors)
    929▕     {
    930▕         static::$lastErrors = $lastErrors;
    931▕     }
    932▕

      [2m+10 vendor frames [22m
  11  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}()

      [2m+5 vendor frames [22m
  17  artisan:34
      Illuminate\Foundation\Console\Kernel::handle()

**Comment by Stargaterom** [comment]
could you provide me with the nexus vendor for php 8.1 my nexus version and 1.30 because I can't do it through the command line and the last time I did it the site no longer works.

if I understood correctly it comes from nesbot/carbon and the web says to do a composer update

 the system runs on ubuntu 20.04

**Comment by Stargaterom** [comment]
I switched to php8.2 and updated the composition and everything and put it in order everything works correctly again and the site is even more fluid and consumes less memory thank you for your help you are very kind

**Comment by Stargaterom** [comment]
I have a problem I no longer have access to the nexus.php panel manager I have 500
Could Server Error help?

since my vendor update and my move to php8.2

**Comment by xiaomlove** [comment]
try to delete the log files at /tmp

**Comment by Stargaterom** [comment]
I deleted and still nothing I just did composer update and put the extension to php8.2 I didn't touch the site file or the database so I can't find any more where to look for it I can't find an error in the logs
![Screenshot_1](https://github.com/xiaomlove/nexusphp/assets/107837857/35d96113-482e-49a0-a1de-f17354694ac6)

**Comment by xiaomlove** [comment]
try to find something at nginx error log

**Comment by Stargaterom** [comment]
/var/log/nginx 

I have no error which displays I am very annoyed I do not want to reinstall everything knowing that everything works fine and we have a nice little community

**Comment by Stargaterom** [comment]
when I put back the php8.1 vendor the panel management nexuxphp system works again when I am in php8.2 with the vendor associated with php8.2 I have error 500 could you tell me where the problem with this could come from

**Comment by xiaomlove** [comment]
When a problem occurs, the error log must be used to locate the problem.
The logs written by NexusPHP are located in the /tmp directory, it is best to set the permissions of the /tmp directory to 777.
You can also check the error logs of PHP and Nginx.
If you can't find it, you can output the logs to a page (it's risky, so you'd better change the password afterward), refer to [Doc.](https://doc.nexusphp.org/en/faq.html#how-to-see-the-logs)

**Comment by Stargaterom** [comment]
hello, I deleted the nexux file in /tmp then I executed the nexusphp page and in the file that is recreated I have this line which comes back in error could it be the problem and especially how to resolve the vendor problem, I already have did a composer update I don't see what I can do I'm very annoyed because you had coded a beautiful page which was very useful and it's the only choose which doesn't work on the site.


error:

production.ERROR: Declaration of Filament\Support\Components\ViewComponent::view(string $view): static must be compatible with Illuminate\View\Component::view($view, $data = [], $mergeData = []) {"userId":2,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Declaration of Filament\\Support\\Components\\ViewComponent::view(string $view): static must be compatible with Illuminate\\View\\Component::view($view, $data = [], $mergeData = []) at /xxx/xxxx/site.com/vendor/filament/support/src/Components/ViewComponent.php:25)

**Comment by xiaomlove** [comment]
If you don't have the plugin installed, you can remove composer.lock and re-execute `composer install`

**Comment by Stargaterom** [comment]
when I put ini_set('display_errors', 1); in core.php I don't have the errors that display on the page, for the vendor it's been 3 times that I reinstall it and I always worry a priori that the problem comes from my composer.json of my version 1.7.30 ?

in ViewComponent.php line 25 I have this line public function view(string $view): static error would come from the

**Comment by Stargaterom** [comment]
in another log file in var/log/nginx /DOMAIN.error.log I have a fatal error.


PHP message: PHP Fatal error:  Declaration of Filament\Support\Components\ViewComponent::view(string $view): static must be compatible with Illuminate\View\Component::view($view, $data = [], $mergeData = []) in /xxxxx/xxxxxx/site.com/vendor/filament/support/src/Components/ViewComponent.php on line 25" while reading response header from upstream, client: xx.xx.xx.xx.xx, server: site.com, request: "GET /nexusphp HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm.sock:", host: "site.com", referrer: "https://site.com/torrents.php"

**Comment by Stargaterom** [comment]
I would like to thank you for your help once again, you are really super nice, to solve the problem it was good in the vendor, I recovered the composer.json from version 1.8 which I replaced my old one then deleted the composer .lock and in ssh I executed composer install and the dashboard is displayed correctly.

**Comment by xiaomlove** [comment]
The level of php support varies from version to version, so if you're on version 1.7.30, you should use php 8.0. see [README](https://github.com/xiaomlove/nexusphp/blob/v1.7.30/README.md)

**Comment by Stargaterom** [comment]
currently in nexus 1.7.30 custom with php8.2 and the composer.json of 1.8 to have the composer installed the site runs perfectly without too many errors thanks to php8.2 we gain in memory performance because php8.1 it there was a memory leak again thank you I will close the subject my nexus and not the cake to install it has been done since 2022 that I have been on your project and it is not easy in case of a problem
