### ISSUE TITLE
安全设定页面会自动填充两部验证，导致重设密码时自动验证开启了

### ISSUE THREAD

**Issue by longdoer** [xiaomlove/nexusphp#233]
好多用户安全设定页面重设密码时会，Chrome等自动填充两部验证，导致重设密码时自动验证开启了
<img width="825" alt="1698067307503" src="https://github.com/xiaomlove/nexusphp/assets/16441085/b18caaf6-9572-4be6-989c-471d2290770d">
建议加上readonly="" onfocus="this.removeAttribute('readonly')"
防止此问题出现
<input type="text" name="two_step_code" readonly="" onfocus="this.removeAttribute('readonly')">

**Comment by xiaomlove** [comment]
已经加上

**Comment by Rhilip** [comment]
这么用这么ugly的方式来关闭 autocomplete 的，多看看文档不好吗？
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

**Comment by xiaomlove** [comment]
@Rhilip 这个有看过，实际测试无效果
