### ISSUE TITLE
关于管理系统允许客户端Agent匹配次数

### ISSUE THREAD

**Issue by bestzyq** [xiaomlove/nexusphp#236]
想问问管理系统允许客户端Agent匹配次数是什么？是不是就是短时间内允许匹配的最多次数？

**Comment by xiaomlove** [comment]
看博客











发自我的iPhone

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月5日(周日) 下午3:35
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [xiaomlove/nexusphp] 关于管理系统允许客户端Agent匹配次数 (Issue #236)




 
想问问管理系统允许客户端Agent匹配次数是什么？是不是就是短时间内允许匹配的最多次数？

**Comment by bestzyq** [comment]
https://nexusphp.org/2023/03/06/add-allow-deny-clients/
看到了，非常感谢
