### ISSUE TITLE
MySQL down after clean job?

### ISSUE THREAD

**Issue by ballonnetje** [xiaomlove/nexusphp#237]
Is it possible that MySQL went down after a clean job?

the log was in /tmp, but after a server wide restart it worked again but the log disappeared..

**Comment by xiaomlove** [comment]
you should see mysql error log

**Comment by IITII** [comment]
**Change your log location.** All files in /tmp will lost after Operation System Reboot @ballonnetje

**Comment by xiaomlove** [comment]
The cleanup will consume a lot of memory, so please give it enough in the php cli mode configuration file.
