### ISSUE TITLE
是不是忘了1.8.9的release了

### ISSUE THREAD

**Issue by bestzyq** [xiaomlove/nexusphp#238]
是不是忘了1.8.9的release了

**Comment by xiaomlove** [comment]
不是。
博客是提前写好更新内容，以免过后忘记细节。
如果你想提前体验，可以群里问是否可以更新，如果回复可以就更新最新开发代码即可体验。

注意：不正式 release 不要用于生产环境，仅用于测试。

另：issue 不要提此类问题。

**Comment by bestzyq** [comment]
好的，非常感谢
