### ISSUE TITLE
BitTorrent v2

### ISSUE THREAD

**Issue by cherinyy** [xiaomlove/nexusphp#241]
Does it already support or plans to support [The BitTorrent Protocol Specification v2 (BEP 52)](https://www.bittorrent.org/beps/bep_0052.html)?

**Comment by cherinyy** [comment]
https://github.com/xiaomlove/nexusphp/blob/20804bee0a1abecfe04ceacbb140851a83b7ff82/public/takeupload.php#L132

It doesn't seem to be supported at the moment, so... any plans?

**Comment by xiaomlove** [comment]
no plan now
