### ISSUE TITLE
关于时区设置问题

### ISSUE THREAD

**Issue by bestzyq** [xiaomlove/nexusphp#242]
如果在安装时未选择正确时区，后续应该怎么做补救？
我尝试将include/core.php ini_set('date.timezone', nexus_config('nexus.timezone'));改成了ini_set('8', nexus_config('nexus.timezone'));但是出现了时魔为负数的问题，又尝试修改.env文件，似乎无效
期待您的帮助，不胜感激！

**Comment by bestzyq** [comment]
时魔为负数的问题，貌似是使用了未release的代码导致的，退回了1.8.8，打扰了，谢谢！

**Comment by xiaomlove** [comment]
未 release 代码怎么会导致时魔为负，请具体描述。

**Comment by bestzyq** [comment]
可能需要再次实验以复现，需要一段时间才能回复

**Comment by bestzyq** [comment]
经实验，没有问题，非常感谢
