### ISSUE TITLE
Not connectable

### ISSUE THREAD

**Issue by Martzy303** [xiaomlove/nexusphp#246]
Have installed this instance on 2 servers, one on AWS Lightsail and one on my local machine.
On both I've tried seeding/leeching from my local machine and a seedbox, from different accounts, both peers say "No".
From my local machine I know I am connectable, I have port forward and have tested on other trackers, works just fine. The seedbox also should be ok, just got it to test from 2 IPs.
What remains is the server, is there something to be done that isn't in the documentation or that I've missed it?

**Comment by xiaomlove** [comment]
There's no need to be overly concerned about this, being able to upload and download normally is fine

**Comment by Martzy303** [comment]
@xiaomlove That's the thing, have left them overnight, not a byte went through, yet they show as peers.
Have looked in the announce.php to see how it checks for connectable, have run it from both ends and it says yes.

`php -r "\$sockres = @fsockopen('xx.xx.xx.xx', 55223, \$errno, \$errstr, 1); echo (is_resource(\$sockres) ? 'yes' : 'no'); if (is_resource(\$sockres)) { fclose(\$sockres); }"`

9 hours, no flow: https://i.imgur.com/M2tzZ48.png

**Comment by xiaomlove** [comment]
So what exactly is your problem?

**Comment by Martzy303** [comment]
@xiaomlove Peers show on the site but the traffic not working at all between them.
I'm trying between 2 seedboxes, one seeding one leeching, no traffic flows at all.

**Comment by xiaomlove** [comment]
As long as the IP and port are correct, everything else is a network issue and has nothing to do with this program.
