### ISSUE TITLE
Contents of shoutbox can be accessed without logging in

### ISSUE THREAD

**Issue by hauntedrows** [xiaomlove/nexusphp#247]
It appears that the shoutbox.php URI is not secured by a check to ensure that the user is logged in.

By editing the URL, any user can bring up the current contents of the tracker's shoutbox in a browser window.

This would appear to be a serious security hole.

**Comment by xiaomlove** [comment]
Fixed, see [here](https://github.com/xiaomlove/nexusphp/commit/9fe932e2443db6a14d7e1de7bf26957fab9ae198)
