### ISSUE TITLE
tracker连接了，但是无法下载

### ISSUE THREAD

**Issue by Flxshin** [xiaomlove/nexusphp#248]
![image](https://github.com/xiaomlove/nexusphp/assets/106539404/e4051f36-82a7-4aa8-b677-addfaba39d89)
已经在工作了，但是无法下载，大佬们有懂的吗

**Comment by xiaomlove** [comment]
只要返回的 IP 和端口正确，就跟本程序无关。这里只讨论与程序相关的功能需求或反馈 Bug，不要在这里提问此类问题，可以到相关群组或论坛请教交流。

**Comment by blanexie** [comment]
从界面看，你这个是只有两个用户做种， 并且你还没有连接上这两个用户，所以无法下载。
