### ISSUE TITLE
更正下载时mutli-tracker的情况

### ISSUE THREAD

**Issue by Rhilip** [xiaomlove/nexusphp#26]
直接引入 Rhilip\Bencode 的patch后，此处下载种子多tracker的情况并不与 NexusPHP 默认等效。 NexusPHP 默认实现其实是被注释掉的 L112-L113。

https://github.com/xiaomlove/nexusphp/blob/19d7e048df1450c1afda1aa771a943c12529a971/public/download.php#L107-L115

具体说明见 BEP0012 或本人之前的解读文章 ： [漫谈PT（6）：Multitracker and client behaviour - R酱小窝 ~ 个人博客](https://blog.rhilip.info/archives/1108/)

建议添加一个配置项，来对该功能进行管理。

> 题外话，目前是不推荐站点设置 Multitracker 的，因为 BEP007 的更新（ https://github.com/bittorrent/bittorrent.org/pull/101 ），会导致多次announce相同数据（视 tracker 数、peer的ip数以及不同tracker域名能解析出来的ip数 ，announce 次数倍乘，如果是  hybrid torrents 就更惨了）。而这点是目前NexusPHP的tracker没法较好处理的。

**Comment by xiaomlove** [comment]
目前只支持一个 tracker
