### ISSUE TITLE
部署文档是否可以增加FrankenPHP的教程？

### ISSUE THREAD

**Issue by Izumiko** [xiaomlove/nexusphp#262]
最近了解到[FrankenPHP](https://github.com/dunglas/frankenphp)的性能很好，是否可以试试用它来运行NexusPHP？

**Comment by xiaomlove** [comment]
没有必要。百万同伴单机都是没有问题的。95%以上的站点活不到百万同伴。

**Comment by Izumiko** [comment]
那倒也是，用户数到不了这么多🤣
