### ISSUE TITLE
重复发种检测功能

### ISSUE THREAD

**Issue by sagan** [xiaomlove/nexusphp#264]
目前在 takeupload.php 里，如果上传的种子生成的 infohash 在数据库里已存在，会直接报错退出。

能否增加这样的功能，如果重复的 infohash 是当前用户之前已经发布过的种子，那么就 302 到对应种子 id 页面，并在页面上显示提示例如：“您之前已经发布了本种子”。

之所以有这个需求是因为我做了一个 nexusphp 自动发种的程序。测试时发现由于网络问题，有时可能出现 post takeupad.php 结果返回超时，但实际上种子已经发布成功这种情形。这种情况下重试发种会因为 infohash 重复而失败，但无法获取到之前发布的种子 id，也就无法自动下载发布的种子然后做种。

**Comment by xiaomlove** [comment]
可以考虑

**Comment by xiaomlove** [comment]
最新[提交](https://github.com/xiaomlove/nexusphp/commit/36fef3e83486b5f052d03f90a9e1f380f2aa9abf)已添加此功能
