### ISSUE TITLE
英语界面签到的字样把bonus写成了bouns导致脚本不能签到

### ISSUE THREAD

**Issue by i990049** [xiaomlove/nexusphp#268]
试了最新的几个今年新开的站点，切换英文界面全部都是attend get bouns，懂英文的应该知道其实应该是bonus。某些外站缺少中文语言包，只能点击外语字样签到，希望把attend get bouns改成attend get bonus。
PS：下面这个魔力公式是不是最新版nexusphp代码包含的？至少需要保种多大体积才能拿到八成的时魔上限？谢谢。
![bonusformulaa](https://github.com/user-attachments/assets/ef22f06a-78f5-42a9-bcdf-2e592b4cfc00)

![bonusformulab](https://github.com/user-attachments/assets/6c10e135-84e3-4640-922d-c9b735682022)

**Comment by xiaomlove** [comment]
翻译问题已经修正。
那个公式并不是本程序包含的。
