### ISSUE TITLE
建议支持webp格式图片

### ISSUE THREAD

**Issue by i990049** [xiaomlove/nexusphp#269]
现在豆瓣和imdb有部分海报都是webp格式的，用ptgen发内容介绍的时候浏览器有缓存显示图片没问题，结果种子审核说图片不显示，闹了半天才知道站点不支持webp格式，现在国内就一个站点pttime支持上传webp格式图片，希望增加支持。

**Comment by xiaomlove** [comment]
浏览器支持就没问题，跟代码有什么关系。ptgen 获取的都是图片的地址。

**Comment by i990049** [comment]
> 浏览器支持就没问题，跟代码有什么关系。ptgen 获取的都是图片的地址。

浏览器也支持jpg，那有些站点就是不显示下面的链接你怎么说？
[img]https://img1.doubanio.com/view/photo/l_ratio_poster/public/p2906817350.jpg[/img]

**Comment by xiaomlove** [comment]
这是豆瓣的问题，跟本程序没关系。

**Comment by i990049** [comment]
> 这是豆瓣的问题，跟本程序没关系。

就是程序的问题，同一个图片代码，馒头和unit3都能显示，难不成豆瓣专门欺负你做的程序？

**Comment by xiaomlove** [comment]
哪里同一张图片馒头可以展示我这里不行，没有看到。

**Comment by i990049** [comment]
> 哪里同一张图片馒头可以展示我这里不行，没有看到。

另外给个链接和截图，我这里可以显示海报，转发去别的np站点不显示，出种了被锁帖作废全部上传
https://kp.m-team.cc/detail/820728
![Screenshot_20240911-204545](https://github.com/user-attachments/assets/751543fc-18a4-4ede-902f-ef6f735a79ea)

**Comment by xiaomlove** [comment]
![image](https://github.com/user-attachments/assets/ece3c507-983e-4507-bb4e-6ee4e67ba1df)

我电脑上 Windows Chrome 128.0.6613.120,，这个图片并不能显示

**Comment by abc123sm** [comment]
这是豆瓣问题，以前我得把1改成9，不然我自己看不见
网址的img1 => img9

**Comment by xiaomlove** [comment]
所以这跟程序没有关系

**Comment by i990049** [comment]
> 这是豆瓣问题，以前我得把1改成9，不然我自己看不见 网址的img1 => img9

你怎么知道要改成9的？为什么不是别的数字？

**Comment by i990049** [comment]
> 所以这跟程序没有关系

同一个豆瓣链接粘贴到馒头ptgen，海报自动变成webp格式了，好像是悦影天下的图床

**Comment by cddjr** [comment]
豆瓣有防盗链的，它判断了来源站。img后面的数字编号不同，防盗的程度也不同。有的是非豆瓣站直接报错，有的编号是限速10kb内。

**Comment by abc123sm** [comment]
> > 这是豆瓣问题，以前我得把1改成9，不然我自己看不见 网址的img1 => img9
> 
> 你怎么知道要改成9的？为什么不是别的数字？

有啥好知道不知道的……他这123456一看大概就能改啊……
