### ISSUE TITLE
已经出种的资源因为转发的海报不显示，被站点禁止，上传海报之后恢复资源上传数据全被作废

### ISSUE THREAD

**Issue by i990049** [xiaomlove/nexusphp#279]
请问这是现在nexusphp内置的惩罚功能吗？不管之前上传多少都要作废，这种站点的共同特点就是同伴列表都能显示ip地理中文位置。

**Comment by xiaomlove** [comment]
什么数据全部作废？

**Comment by i990049** [comment]
> 什么数据全部作废？

这种上传数据，已经出种了，因为图片链接不显示，被禁了，然后上传数据全被做废了，补传图片过审所有上传数据照样作废，这是你做出来的惩罚功能？因为海报不显示不过审把已经出种的上传数据全部作废？
![Image_1726042377373](https://github.com/user-attachments/assets/8f19e2d0-e38c-4b7d-a595-bdb9679ee848)

**Comment by xiaomlove** [comment]
> > 什么数据全部作废？
> 
> 这种上传数据，已经出种了，因为图片链接不显示，被禁了，然后上传数据全被做废了，补传图片过审所有上传数据照样作废，这是你做出来的惩罚功能？因为海报不显示不过审把已经出种的上传数据全部作废？ ![Image_1726042377373](https://private-user-images.githubusercontent.com/103364093/366359992-8f19e2d0-e38c-4b7d-a595-bdb9679ee848.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNDUwNDAsIm5iZiI6MTcyNjA0NDc0MCwicGF0aCI6Ii8xMDMzNjQwOTMvMzY2MzU5OTkyLThmMTllMmQwLWUzOGMtNGI3ZC1hNTk1LWJkYjk2NzllZTg0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMVQwODUyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODMzMzRmMzhhMDZmNWUxMGZlNTU2MzBiODQzNmVhY2UwZGU5MGQ4ZTY5NTk2ZTgzOTkwMThiN2I5ZDU4MDI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UI-5-sPd6zWy1SOIqKvIbAnSIYABPPGcoF_JyjWCAS4)

这图片是哪个页面的

**Comment by i990049** [comment]
> > > 什么数据全部作废？
> > 
> > 
> > 这种上传数据，已经出种了，因为图片链接不显示，被禁了，然后上传数据全被做废了，补传图片过审所有上传数据照样作废，这是你做出来的惩罚功能？因为海报不显示不过审把已经出种的上传数据全部作废？ ![Image_1726042377373](https://private-user-images.githubusercontent.com/103364093/366359992-8f19e2d0-e38c-4b7d-a595-bdb9679ee848.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNDUwNDAsIm5iZiI6MTcyNjA0NDc0MCwicGF0aCI6Ii8xMDMzNjQwOTMvMzY2MzU5OTkyLThmMTllMmQwLWUzOGMtNGI3ZC1hNTk1LWJkYjk2NzllZTg0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMVQwODUyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODMzMzRmMzhhMDZmNWUxMGZlNTU2MzBiODQzNmVhY2UwZGU5MGQ4ZTY5NTk2ZTgzOTkwMThiN2I5ZDU4MDI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UI-5-sPd6zWy1SOIqKvIbAnSIYABPPGcoF_JyjWCAS4)
> 
> 这图片是哪个页面的
pt站左上角用户名点进去，点已发种子，里面有每个种子的上传数据

**Comment by xiaomlove** [comment]
已经汇报成功的数据是没有清理的逻辑的。
如果种子被禁用，本次汇报是不成功的，本次汇报的数据不会被记录。

**Comment by i990049** [comment]
> 已经汇报成功的数据是没有清理的逻辑的。 如果种子被禁用，本次汇报是不成功的，本次汇报的数据不会被记录。

我已经说了已经出种了，当然就会有上传数据，海报链接不显示被锁帖，就算上传海报解锁帖子，上传数据还是全被作废。这种站点有个共同的特征，下载页面的同伴列表可以显示中文地理ip。

**Comment by xiaomlove** [comment]
1、我已经说过了，汇报成功的数据不会被清空，你试下能不能复现出来，可以再说。
2、同伴列表显示IP和位置是可以关闭的，而且可以设置有权限的用户可见。
