### ISSUE TITLE
Idea: an English-speaking place to talk about NexusPHP

### ISSUE THREAD

**Issue by Oha-you** [xiaomlove/nexusphp#28]
Hello friends. I wrote a comment at [Discuss](https://discuss.nexusphp.org/thread/comment/101821?threadId=1), but I'd like to mention it here as well, because I'm worried it might not get noticed.

I want to join the team of maintainers and help make NexusPHP better. My goal is to migrate a private tracker to this new engine. Maybe even two trackers. I have already contributed to [UNIT3D](https://github.com/HDInnovations/UNIT3D-Community-Edition/commits?author=Oha-you) engine in the past.
However, I couldn't join your QQ group and recently can't even login to QQ at all (I guess because of some new geo-block).

So could you please create an official Discord/Telegram/IRC/Matrix server where English speakers can ask questions, get answers and maybe even coordinate some coding work with you? I'd like to know what your priorities are, what can be worked on, etc.
Of course I can decide on the tasks by myself, but it would be much better if you could provide some guidance.

I noticed that the project became a bit stale (no updates since June), so I hope I can bring some fresh blood to it.

**Comment by maximuml** [comment]
+1
I also trying to migrate from old tbdev to this source.

**Comment by maximuml** [comment]
I guess the best way for you is to fork this repo and adds your commits. Will be nice to see your mods.

**Comment by Oha-you** [comment]
I created a **Matrix** space with two rooms (Talk and Dev). URL: https://matrix.to/#/#nexus:envs.net
If you don't have a Matrix account yet, create it here: https://element.envs.net/#/register
<details>
<summary>How it looks like</summary>

![2021-10-19_024559](https://user-images.githubusercontent.com/82098328/137821310-eb6ae25c-dbaa-48c1-a6a4-f4274f35c556.png)
</details>

You can use Web or Desktop/Mobile client: https://element.io/get-started#downloads
Email is optional, just login and password is enough. Be sure to save/backup your keys so that you can DM people easily.

I chose Matrix since it's not blocked in China, it doesn't require a phone number like Telegram and it has more features than IRC.
If you're not familiar with it, read some basic info [here](https://matrix-help.envs.net/) and [here](https://matrix.org/discover/). Envs.net is a reliable public homeserver.

Here's also my `config.json` with some recommended settings for Element Desktop: [config.zip](https://github.com/xiaomlove/nexusphp/files/7369053/config.zip)
It has Discord custom theme enabled by default. Place it to a [default location](https://github.com/vector-im/element-desktop#user-specified-configjson) depending on your OS.

@xiaomlove I really hope you can join this Matrix space 🙂 I will give you admin permissions right away.
I also invite all other contributors to join: @rabbitwit, @burpheart and @2502040155.
Can you please inform people in the [QQ group](https://github.com/xiaomlove/nexusphp#%E6%9B%B4%E5%A4%9A%E4%BF%A1%E6%81%AF) as well? Just a link to this issue will be fine. Thank you!

I can try to add a bot that will translate all messages to Chinese and English so we can communicate better, if needed.
If everyone ignores this message, I'll still work on NexusPHP and try to come up with useful PRs. I plan to start in ~10 days.

**Comment by Oha-you** [comment]
As I was told by a user who joined the QQ group:
> xiaomiao (the github owner) has been offline for a long time and the project is no longer in progress

I really hope the owner is in good health in these challenging times.

@Rhilip I'm sorry for the ping, but I think you know a lot about NexusPHP as well (from the issues you created).
And you even made your own tracker engine: https://github.com/Rhilip/RidPT (that's so cool!)
Would you be interested in continuing the work on NexusPHP? 🙏
And what do you think are the main problems that need to be fixed in the first place?

I think xiaomlove mentioned the future plans in this [Discuss post](https://discuss.nexusphp.org/thread/4). A rough DeepL translation:
> - [x]  H&R
> - [ ] Seed Claiming
> - [x] Seed Detail Page Magic Bonus
> - [x] Google Captcha
> - [x] IP Address Display
> - [ ] Magic Purchase Offer & Top
> - [ ] Magic Buy VIP
> - [ ] Magic name change
> - [ ] Seed list batch set preferences and top
> - [ ] Batch processing of cheater suspect pages
> - [ ] Split data table with large fields
> - [x] Introduce more efficient Bencode library
> - [ ] Navigation bar customization with secondary support
> - [x] Check-in optimization
> - [ ] Introduce seeding points

IMO, we should start by introducing some code style and formatting rules, adding pre- and post-commit hooks (for automated code checks) and GitHub actions. It will make the code more readable and pleasant to work with.

**Comment by Rhilip** [comment]
> @Rhilip I'm sorry for the ping, but I think you know a lot about NexusPHP as well (from the issues you created). And you even made your own tracker engine: [Rhilip/RidPT](https://github.com/Rhilip/RidPT) (that's so cool!) Would you be interested in continuing the work on NexusPHP? 🙏 And what do you think are the main problems that need to be fixed in the first place?

I'm sysop for a NexusPHP site over 4 years, 
At now, I still continus working with NexusPHP, but for the forked branch which My Site used (a private repo in Github )
But I don't want to join this project, some issue and advise are only things I can provided.
( I don't like Laravel anymore in a PHP Private Tracker, it's too heavy. )
and the development of RidPT is EOF ( But the wonderful tracker part engine in RidPT is now reused in Unit3D, thanks to @HDVinnie ).

The biggest problem for NexusPHP is torrent search, due to bad design of `torrents` table in MySQL, the `LIKE` search is a CPU killer, maybe using Eleasticsearch is a good advise.
Also, since legacy NexusPHP project is very old, Some design like:
 - wrapped Cache function to cache page (https://github.com/xiaomlove/nexusphp/blob/19d7e048df1450c1afda1aa771a943c12529a971/classes/class_cache_redis.php#L192-L265)
 - table css 
 - nfo column to store Blob data in torrents table

is very stupid, and can fix in furture.

**Comment by haig233** [comment]
@Oha-you It is recommended to use Telegram, matrix may be unfamiliar to many people.

**Comment by chenkeng** [comment]
I've  joined the group in [nexusphp](https://t.me/nexusphp)

**Comment by xiaomlove** [comment]
> I've joined the group in [nexusphp](https://t.me/nexusphp)

I've joined. maybe telegram is better。 @Oha-you
