### ISSUE TITLE
可以增加几个默认支持的客户端吗？

### ISSUE THREAD

**Issue by i990049** [xiaomlove/nexusphp#284]
Nexusphp本来就支持Azureus，Az在2017年停止更新后由辞职员工另外更新界面一模一样的跨平台的开源软件Bigly BT，多了RSS功能，可以按照文件大小过滤RSS，比正则表达过滤简单明了，馒头、HDarea、不可说长鼻子和很多外站、Unit3d站点都支持。
![屏幕截图(282)](https://github.com/user-attachments/assets/b3b3481e-7933-4d8b-a727-2fabedf4eb1f)
其他软件订阅RSS需要一个个站点设置，Tixati可以把全部站点的RSS复制粘贴到同一个框框里面，只用设置一次关键字过滤就行了，绿色版解压即可用，不像别的软件会在C盘留下文件，只要放在其他分区，就算重装系统，软件全部数据照样还在，配合中文补丁即可轻松使用，上传数据默认优先使用UDP，适合没有公网IP的用户使用，Unit3d站点都支持。
![屏幕截图(283)](https://github.com/user-attachments/assets/353aab59-b98d-457d-a2cc-ed7c7669b1c3)
手机上面唯一一个支持制作BT混合协议 V1 V2的软件LibreTorrent，手机可以直接发电子书、有声书、音乐到PT站，不需要重新传到电脑制作种子，以上软件如果新版Nexusphp默认支持，那会方便很多。
![3TmwogAyUQhGedX](https://github.com/user-attachments/assets/8d3c3fa8-71bb-421a-a8b4-24de1fcd504d)

**Comment by xiaomlove** [comment]
管理后台可以自行添加

**Comment by i990049** [comment]
> 管理后台可以自行添加



> 管理后台可以自行添加

我的意思是搞成np默认支持，开箱即用，不是每个站长都会代码的。

**Comment by xiaomlove** [comment]
我没有用过,你可以自己添加成功后,提供相关插入的语句过来,我加到新版中去.

**Comment by i990049** [comment]
麻烦告知具体在哪个界面设置，请发个截图上来，谢谢

**Comment by xiaomlove** [comment]
> 麻烦告知具体在哪个界面设置，请发个截图上来，谢谢

管理后台啊，允许客户端

**Comment by i990049** [comment]
确实不能设置，麻烦详细告知
<img width="553" alt="2024-09-24_125524" src="https://github.com/user-attachments/assets/a570a13a-0508-4f70-9983-23b0ddbc797d">

**Comment by xiaomlove** [comment]
你参考下博客相关文章, 就是在这里加的.

**Comment by i990049** [comment]
新增或禁用客户端 – NexusPHP
https://nexusphp.org/2024/03/06/%e6%96%b0%e5%a2%9e%e6%88%96%e7%a6%81%e7%94%a8%e5%ae%a2%e6%88%b7%e7%ab%af/#:~:text=%E6%96%B0%E5%A2%9E%E6%88%96%E7%A6%81%E7%94%A8%E5%AE%A2
确实找不到这个文章写的设置页面，我这里只有检测和删除客户端

<img width="597" alt="2024-09-24_202159" src="https://github.com/user-attachments/assets/0f07da4a-2f0c-4402-b7b7-237915b4474c">

**Comment by xiaomlove** [comment]
右上角有啊

**Comment by i990049** [comment]
右上角只有一个检测的按钮，我试过了不行，现在把客户端最新版给你尝试添加，以下软件Unit3D架构都支持，谢谢

软件名
LibreTorrent 3.5.2
peerid
-Lr3520-
软件名
Tixati/3.29
peerid
TIX0329-
中文语言包，下载后用鼠标右键点击系统托盘interface进去找到txt文件重启切换中文
https://tieba.baidu.com/p/9043653890
docker版
https://github.com/jlesage/docker-tixati

软件名
BiglyBT 3.7.0.0
peerid
-BI3700-
也有docker版，不装docker直接装JAVA也行

**Comment by i990049** [comment]
qbittorrent更新5.0.0了，一起集成到客户端新代码里面吧

**Comment by xiaomlove** [comment]
一般不会在升级中添加更多的客户端支持, 要加也是加到初始化的时候, 即全新安装默认会支持更多客户端.
使用过程中要新增或减少客户端, 后台自行添加或删除, 更新程序不会修改用户已有的数据.

**Comment by i990049** [comment]
那就请你加到初始化的代码里面去吧，我这里的添加客户端右上角确实只有‘检测’这个按钮，上面的软件根本加不了我要是能加就不会来这里麻烦你了，这些软件跟rutorrent和bitcomet一样可以在最新版unit3d升级过的站点使用的，是更新后可以使用，NP不能更新那就在初始状态支持也行。

**Comment by xiaomlove** [comment]
![image](https://github.com/user-attachments/assets/f1cf5d0d-e51c-4ec5-822b-bf01386dc56e)

一直都有新建按钮。不信你可以全新安装一下看看，看 readme 使用 docker 几分钟就安装好了。

**Comment by xiaomlove** [comment]
也可能是你们修改过代码，那谁修改的就让谁去加吧。升级过程是不会添加这类数据的，因为有的用户可能自已经添加过了。

**Comment by i990049** [comment]
客户端名称
Elementum/0.1.104
peerid
-LT1100-
也是跨平台软件，支持安卓、苹果机顶盒
https://github.com/elgatito/plugin.video.elementum/releases
希望以后更新代码集成到默认支持客户端里面，谢谢

**Comment by xiaomlove** [comment]
默认只支持大众使用公认可信赖的的 TR/QB，小众的东西站长想要支持就自己后台添加。

**Comment by i990049** [comment]
> 客户端名称 Elementum/0.1.104 peerid -LT1100- 也是跨平台软件，支持安卓、苹果机顶盒 https://github.com/elgatito/plugin.video.elementum/releases 希望以后更新代码集成到默认支持客户端里面，谢谢

https://nusantara.re
正在使用机顶盒观看上面的站点视频，为什么外国的nexusphp自动支持上面这些软件？因为没使用白名单功能？

**Comment by xiaomlove** [comment]
我都说了, 要支持任意软件都可以, 看站长心情, 管理后台自己添加!

**Comment by i990049** [comment]
这是前几天更新的软件，并且换了peerid，上面那个网站是很老旧的，应该没有特别适配就能支持新peerid，系统是不是有什么关闭白名单的设置，关闭白名单不论任何软件都能链接上来
