### ISSUE TITLE
strftime() 函数在 PHP 8.1 中已被弃用

### ISSUE THREAD

**Issue by bestzyq** [xiaomlove/nexusphp#285]
FastCGI sent in stderr: ＂/public/shoutbox.php on line 130PHP message: PHP Deprecated: Function strftime() is deprecated in /www/wwwroot/nexusphp/public/shoutbox.php on line 130PHP message: PHP Deprecated: Function strftime() is deprecated in /www/wwwroot/nexusphp/public/shoutbox.php on line 130＂ while reading upstream

$time = strftime("%m.%d %H:%M",$arr["date"]);

使用 DateTime 类来替代它

$time = (new DateTime())->setTimestamp($arr["date"])->format('m.d H:i');

**Comment by xiaomlove** [comment]
已合并相关 PR
