### ISSUE TITLE
请求修正论坛显示过宽问题

### ISSUE THREAD

**Issue by xusky0328** [xiaomlove/nexusphp#289]
论坛发帖，内容长了，页面变得超级宽，请求根据窗口自动适配宽度。
![photo_2024-10-06_22-37-39](https://github.com/user-attachments/assets/e59c9bae-72cc-491f-92e0-217cf61da506)

**Comment by xiaomlove** [comment]
你的内容是什么, 我测试了没有问题.

**Comment by xusky0328** [comment]
引用的base64编码

**Comment by xusky0328** [comment]
json的base64编码

**Comment by xiaomlove** [comment]
参考这个提交，修改下看看：https://github.com/xiaomlove/nexusphp/commit/2750059bea7c8459d628b149ff2b352ae01889cb

**Comment by xusky0328** [comment]
按此操作可解决，感想大佬。

**Comment by xusky0328** [comment]
大佬好，今天在求种去，也出现这个问题，还请帮忙看看怎么修复。
![image](https://github.com/user-attachments/assets/ff27efe5-0bb5-45a7-afb7-5f5a7bb58d5f)

**Comment by xiaomlove** [comment]
[按此](https://github.com/xiaomlove/nexusphp/commit/7a29366978cf7efff33499c99750cc5d396c3586)变更即可

**Comment by xiaomlove** [comment]
以最新为准。
