### ISSUE TITLE
username cards

### ISSUE THREAD

**Issue by PumpkinPounder** [xiaomlove/nexusphp#290]
where are username cards located as they done seem to work when bought from the points store or given by staff users cant find them

**Comment by xiaomlove** [comment]
screen shoot please, I don't understand what you are saying

**Comment by PumpkinPounder** [comment]
![Untitled](https://github.com/user-attachments/assets/97f63eed-59c6-4c46-801d-3dd66ea77864)
where do the name change cards go when we buy them as we cant find them

**Comment by xiaomlove** [comment]
at userdetails page.

![QQ_1728700132876](https://github.com/user-attachments/assets/908bd1bd-f6ae-465a-bc2b-99f581ba88de)

**Comment by PumpkinPounder** [comment]
if its not there we might need to upgrade thank you
