### ISSUE TITLE
Donor Points

### ISSUE THREAD

**Issue by PumpkinPounder** [xiaomlove/nexusphp#292]
Points visual bug for donors

when donors get the rank of 
![sssss](https://github.com/user-attachments/assets/514e25e1-8cf2-4835-a413-985dfd96a2fa)

the points here 
![ssssssssssssssssssssssssssssssssss](https://github.com/user-attachments/assets/c925c079-42ec-4515-81d0-ef45db5e7fdb)

they dont show the points total any fix for this?

**Comment by xiaomlove** [comment]
It's only a problem for doners, is it normal for regular users?

**Comment by PumpkinPounder** [comment]
yes when given donor rank the points stop showing
regular useers are fine

**Comment by xiaomlove** [comment]
Fixed, upgrade to latest, or modify by yourself reference to https://github.com/xiaomlove/nexusphp/compare/7a29366978cf7efff33499c99750cc5d396c3586...8dbf7986474d1f7a530383b9beee0c10fa0f89b8

**Comment by PumpkinPounder** [comment]
Thanks you :)
