### ISSUE TITLE
联系管理组点击提交后不显示成功页面，导致新人反复提交

### ISSUE THREAD

**Issue by i990049** [xiaomlove/nexusphp#293]
能不能像站点短信一样显示发送成功的页面？

**Comment by i990049** [comment]
另外HR系统能不能学unit3d每隔24小时用户不做种站内私信和注册邮箱各提醒一次？

**Comment by xiaomlove** [comment]
v1.8.15 已调整

**Comment by i990049** [comment]
以后HR超过24小时没做种都有站点短信PM和注册邮箱提醒吗？

**Comment by xiaomlove** [comment]
> 以后HR超过24小时没做种都有站点短信PM和注册邮箱提醒吗？

目前不予考虑. 一来每天邮件数量大多是有限的, 二来不关心的通不通知没区别, 靠自觉. 当前还有其他更重要的工作
