### ISSUE TITLE
部署域名后管理系统的样式总是域名的http协议

### ISSUE THREAD

**Issue by QYG2297248353** [xiaomlove/nexusphp#295]
![image](https://github.com/user-attachments/assets/5d56f64b-9cc0-42a6-ac36-9c0638a650c6)

域名也开启了强制http跳https，唯独，这几个样式死活不跳转

修改 APP_URL 也没有用。我实在不知如何解决

**Comment by QYG2297248353** [comment]
前台不受影响，都是相对地址
![image](https://github.com/user-attachments/assets/2ed780d4-da56-45ae-b26b-ab4cee9ecdd2)

**Comment by xiaomlove** [comment]
你是用的CF 代理吗?  SSL/TLS 加密模式选的什么? 你看一下 nginx 请求日志有没有记录 $scheme, 如果没有,可以按照以下操作来添加.

首先在 nginx 主配置 nginx.conf 中 http 模块添加一个 log_format, 命名为 main: 

```
log_format  main  '$remote_addr - $remote_user [$time_local] $scheme "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for" '
                      '"$request_body" "$http_cookie" "$request_id" $request_time';
```

然后在网站配置中使用这个格式, access_log 末尾指定使用 main

```
access_log  /www/wwwlogs/oxxx.com.log main;
```

重启 nginx 生效, 在网站请求日志中就能看到前端请求到服务器是 http 还是 https:

```
172.68.186.106 - - [08/Nov/2024:03:11:33 +0000] https ＂GET /userdetails.php?id=38621 HTTP/2.0＂ 200 ...
```

**Comment by QYG2297248353** [comment]
> 你是用的CF 代理吗? SSL/TLS 加密模式选的什么? 你看一下 nginx 请求日志有没有记录 $scheme, 如果没有,可以按照以下操作来添加.
> 
> 首先在 nginx 主配置 nginx.conf 中 http 模块添加一个 log_format, 命名为 main:
> 
> ```
> log_format  main  '$remote_addr - $remote_user [$time_local] $scheme "$request" '
>                       '$status $body_bytes_sent "$http_referer" '
>                       '"$http_user_agent" "$http_x_forwarded_for" '
>                       '"$request_body" "$http_cookie" "$request_id" $request_time';
> ```
> 
> 然后在网站配置中使用这个格式, access_log 末尾指定使用 main
> 
> ```
> access_log  /www/wwwlogs/oxxx.com.log main;
> ```
> 
> 重启 nginx 生效, 在网站请求日志中就能看到前端请求到服务器是 http 还是 https:
> 
> ```
> 172.68.186.106 - - [08/Nov/2024:03:11:33 +0000] https ＂GET /userdetails.php?id=38621 HTTP/2.0＂ 200 ...
> ```

我先试试，用的 1panel 反向代理 到 nexusphp 的 nginx 上

**Comment by QYG2297248353** [comment]
![image](https://github.com/user-attachments/assets/21749f6e-849a-456c-ac77-e22fe8c0e56e)


传递进来的的是http 唉，我在研究研究

**Comment by QYG2297248353** [comment]
解决不了，唉，即使如何传递
```
proxy_set_header X-Forwarded-Proto $scheme; 
```
scheme 传递到 下一级就变成了http

**Comment by xiaomlove** [comment]
我的日志格式中包含 cookie, 你的截图我删除了, 要注意.
如果数据重要, 请修改密码.

**Comment by QYG2297248353** [comment]
> 我的日志格式中包含 cookie, 你的截图我删除了, 要注意. 如果数据重要, 请修改密码.

谢谢，不过，没正式部署，还在解决 https的问题

**Comment by QYG2297248353** [comment]
![image](https://github.com/user-attachments/assets/a8d5840b-cc20-4498-a8eb-ae01015b48f4)

![image](https://github.com/user-attachments/assets/4c43a200-95bc-4bbd-ace0-588290f45b4f)

@xiaomlove 

所以 后台管理就无法 获取到 https
后台为什么不能使用相对地址呢
这样的话网站就不能强制开启https了，
还有其他办法解决吗

**Comment by xiaomlove** [comment]
不是没获取到时,是实际请求到NP就是http. 
你看下雷池的配置, 要启用 SSL/TLS 之类的, NP 这边的 nginx 也要使用 443, 并配置好证书

**Comment by QYG2297248353** [comment]
> 不是没获取到时,是实际请求到NP就是http. 你看下雷池的配置, 要启用 SSL/TLS 之类的, NP 这边的 nginx 也要使用 443, 并配置好证书

公网是 https 内网设备就没必要了吧，没有意义呀，内网的证书更新老麻烦了

**Comment by xiaomlove** [comment]
本身就要这么配置的, 一年不更新一次, 你按这个来配置就好了

**Comment by xiaomlove** [comment]
CF 提供的证书,有效期 20 年

**Comment by QYG2297248353** [comment]
> 本身就要这么配置的, 一年不更新一次, 你按这个来配置就好了

我大多数服务都是在内网，公网只是转发服务器，不好搞，
到时候我再看看吧

**Comment by xiaomlove** [comment]
你这种需求确实是有, 晚点我做点改动,看能不能解决这个问题吧.

**Comment by QYG2297248353** [comment]
> 你这种需求确实是有, 晚点我做点改动,看能不能解决这个问题吧.

主要是影响后台管理，正常访问前台不受影响，就算有http也能自动跳转https

内网管理员可以用ip直接访问，外网的就没办法了，访问也是没有样式

**Comment by xiaomlove** [comment]
你可以更新最新看看是否可以了

**Comment by QYG2297248353** [comment]
> 你可以更新最新看看是否可以了

好的，我试试看

**Comment by QYG2297248353** [comment]
> 你可以更新最新看看是否可以了

试过了，还是不行，管理系统还是没有样式

![image](https://github.com/user-attachments/assets/68d57a44-616f-4e7e-b5e8-b7b67a43c92e)

即使是开启 `使用SSL（网页）`
![image](https://github.com/user-attachments/assets/c98d28e6-bdae-4146-a65b-c17af1bbb375)

**Comment by xiaomlove** [comment]
你更新到最新, .env 添加以下配置试试
```
FORCE_SCHEME=https
```

**Comment by QYG2297248353** [comment]
> FORCE_SCHEME=https

使用此配置确实正常了，

但是本地IP就不行了，这也是坑定的

**Comment by QYG2297248353** [comment]
我想将其制作成docker不知道哪些目录应该做持久化，避免重建docker应用，又回到初始化界面
