### ISSUE TITLE
【咨询】将项目制作成Docker 哪些目录应该持久化

### ISSUE THREAD

**Issue by QYG2297248353** [xiaomlove/nexusphp#296]
将项目都进行持久化，哪些目录应该持久化，避免每次重建项目导致重新进行初始化

**Comment by xiaomlove** [comment]
你可以把整个代码目录持久化，也方便修改代码。PHP容器只是提供运行环境。当然，对于Mysql和Redis 数据是要持久化的。

**Comment by QYG2297248353** [comment]
> 你可以把整个代码目录持久化，也方便修改代码。PHP容器只是提供运行环境。当然，对于Mysql和Redis 数据是要持久化的。

整个目录持久化，后续升级就不行了，代码无法更新

现在已经做到代码目录持久化，如果进行升级，就不能通过镜像升级

我想知道，哪些目录是初始化后生成的，我将这些目录列入白名单，不进行覆盖，其他目录，在每次更新镜像，重启，重建都进行覆盖。

**Comment by xiaomlove** [comment]
如果你是原版, 分类图标之类也没有自已换过,以下目录持久化即可:
```
attachments
bitbucket
imdb
subs
torrents
```
如果你自己修改或添加过样式, 分类图标等, 再将以下目录持久化:
```
public/styles
public/pic
```

**Comment by xiaomlove** [comment]
这个升级是有脚本命令要执行的(重复执行不会有问题), 不是将代码更新了就可以, 具体你看文档.

**Comment by QYG2297248353** [comment]
好的谢谢，我研究研究
