### ISSUE TITLE
SQL Injection Vulnerability in User Lookup Function

### ISSUE THREAD

**Issue by shreethaar** [xiaomlove/nexusphp#297]
```php
$res = sql_query("SELECT * FROM users WHERE id = ".mysql_real_escape_string($id)) or sqlerr();
$user =  mysql_fetch_assoc($res);
```
- It is potential for unauthorized database access
-  Complete database compromise

**Priority**: High (Immediate action required)

**Comment by xiaomlove** [comment]
which file ?

**Comment by shreethaar** [comment]
> which file ?

at /public/invite.php, line 34

**Comment by xiaomlove** [comment]
have try?

**Comment by shreethaar** [comment]
> have try?

maybe use prepare statement, here is the reference:
https://stackoverflow.com/questions/134099/are-pdo-prepared-statements-sufficient-to-prevent-sql-injection
