### ISSUE TITLE
使用宝塔安装的时候好像报错.

### ISSUE THREAD

**Issue by Mr-ByeBye** [xiaomlove/nexusphp#3]
不知是不是我技术问题,我用宝塔安装的时候报502错,检查了下应该是配置文件问题,具体哪儿问题查半天没查出来.
另外宝塔Nginx下PHP默认配置好像是Unix Socket,你的安装教程fastcgi_pass监听好像是TCP Socket.
使用Unix Socket是否会效率更高一些?

**Comment by Mr-ByeBye** [comment]
@xiaomlove 另外感谢大佬的辛苦付出.这玩意好歹也是上古时期的产物了,能动手修修补补我也算是非常敬佩了.毕竟我这样上了年纪的伸手党动手能力是已经废了.

**Comment by xiaomlove** [comment]
宝塔面板我没有测试，待测试后反馈。 @bigcaibao

**Comment by Joyist2021** [comment]
宝塔没问题。
