### ISSUE TITLE
种子直接下载链接使用竖线|传递passkey不符合标http标准导致软件不能下载

### ISSUE THREAD

**Issue by i990049** [xiaomlove/nexusphp#301]
https://github.com/elgatito/plugin.video.elementum/issues/1091#issuecomment-2549198591
应该使用&或者=
;已经不被w3c推荐使用
另外现在有些人因为中木马导致passkey泄露导致分享率异常，可否借鉴馒头和野马那样的credential每个种子的passkey都是不一样的，就算泄露也只泄露一个种子？建议把这个做成选项，让每个站点可以手动选择切换到哪种模式，选择直接下载链接是全部都一样的passkey模式还是全部不一样的credential模式

**Comment by xiaomlove** [comment]
v1.8.15 已调整

**Comment by i990049** [comment]
我看了采用浙江大学np的新柠檬和pttime，它们的downhash里面都是用=和&表达passkey，为什么1.8.15版不用这两个符号要用.呢？单纯为了跟浙江大学np直链有区别？

**Comment by i990049** [comment]
能支持每个种子passkey都不一样的直链吗？

**Comment by xiaomlove** [comment]
区别不大, passkey 方便集中管理, 方便批量替换

**Comment by i990049** [comment]
同样的passkey盗号刷流也方便

**Comment by xiaomlove** [comment]
没有完美的方案, 都是取舍的结果. 盗了就重置
