### ISSUE TITLE
新种子上传邮件乱码

### ISSUE THREAD

**Issue by wangyan** [xiaomlove/nexusphp#302]
![微信图片_2024-12-18_225554_858](https://github.com/user-attachments/assets/ad48ca45-e55b-4e5b-81c7-4df22e5701f4)

其他注册邮件之类的通知都正常。

**Comment by xiaomlove** [comment]
很少人开启这个, 晚点我看看

**Comment by xiaomlove** [comment]
v1.8.15 已修复
