### ISSUE TITLE
Beta3新增加的發種標籤功能，標籤的預設選項要在哪裏修改呢？

### ISSUE THREAD

**Issue by myhenji** [xiaomlove/nexusphp#31]
求大神回覆，感激不盡。

**Comment by xiaomlove** [comment]
代码写死的，不支持后台修改。

**Comment by myhenji** [comment]
代碼也可以，請大佬告知在哪個文件裏修改，謝謝！

**Comment by xiaomlove** [comment]
[这里](https://github.com/xiaomlove/nexusphp/blob/php8/include/functions.php#L4720)
