### ISSUE TITLE
H&R bug

### ISSUE THREAD

**Issue by LuciuzHQ** [xiaomlove/nexusphp#32]
> **The hr.ban user when counts reach field is required.**

This message when I try to enable H&R in the admin dashboard.

Screenshot here : [https://imgur.com/FV8Rtf7](url)

**Comment by ghost** [comment]
Open console and type:
mysql - u root
use nexusphp;
INSERT INTO `settings` (`id`, `name`, `value`, `created_at`, `updated_at`) VALUES (NULL, 'hr.mode', 'disabled', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP); 

Done xD

**Comment by xiaomlove** [comment]
I can't reproduce it , you can try the answer above.

**Comment by xiaomlove** [comment]
v1.6.0-beta13 released!
