### ISSUE TITLE
关于邮件SMTP发送设置

### ISSUE THREAD

**Issue by oldking139** [xiaomlove/nexusphp#33]
### 故障：
源代码：
https://github.com/xiaomlove/nexusphp/blob/27ba9aec74e46199d65bb96b318b85cf5bd898f9/include/functions.php#L1424

在调用swiftmailer时，若要调整smtp tls 或 ssl 设置时，管理面板并没有这个选项。
同时，邮件无法发出，nexusPHP log 如下（使用Microsoft office 365 bussiness 邮件SMTP）：

> [2022-01-26 04:11:01] [cabc61f05950703a1370433418db373a] [1] [295aacdbb0a4ccf197bdd7a49190cbee] [1] [5.220] local.info /www/wwwroot/站点名称-已脱敏处理/include/functions.php:1447 sent_mail send email fail: Expected response code 250 but got code "451", with message "451 5.7.3 STARTTLS is required to send mail [HK2PR03CA0046.apcprd03.prod.outlook.com]

### 解决方案：
functions.php调整如下（请先在管理面板内设置好正确的smtp信息）（以 port 587 + STARTTLS 为例）：

`$transport = (new Swift_SmtpTransport($setting['smtpaddress'], $setting['smtpport'], $setting['smtpport'] == 587 ? 'tls' : true))`

使用 SSL 请直接将`'tls' : true`改成`'ssl' : true` （大概，我没试过）

**Comment by xiaomlove** [comment]
会考虑增加这些选项

**Comment by xiaomlove** [comment]
v1.6.0-beta13 已更新
