### ISSUE TITLE
添加广告后返回 HTTP 500

### ISSUE THREAD

**Issue by oldking139** [xiaomlove/nexusphp#34]
### 环境
NexusPHP 版本：NexusPHP v1.6.0-beta12
PHP 版本：PHP 8.0
Mysql 版本：5.7.34
Redis 版本：Redis 6.2.4

### 故障
尝试在 _管理组面板 -> ..:: 针对版主开放 ::.. -> 广告管理_ 中添加广告，添加位置选择任意皆会返回 HTTP 500 。

详情：
添加广告内容：
![chrome_3a4KBXiEZx](https://user-images.githubusercontent.com/45203648/151366455-b6183932-71ba-4f00-8900-5ad19fbd122e.png)
返回信息 & payload：
![chrome_DcQaANwCMO](https://user-images.githubusercontent.com/45203648/151366583-c51a25d1-0648-4c0b-931c-9e56a5e3eb6c.png)
![chrome_8F3ub0CQU7](https://user-images.githubusercontent.com/45203648/151366597-8d25a895-e239-4179-932b-5fadc439df32.png)

日志显示：
`[2022-01-27 21:13:59] [292561f29a9701680469419276513fb0] [1] [295aacdbb0a4ccf197bdd7a49190cbee] [0] [0.168] local.info /www/wwwroot/站点名称-已脱敏处理/nexus/Database/NexusDB.php:80 Nexus\Database\NexusDB->query Column 'starttime' cannot be null [INSERT INTO advertisements (`enabled`, `type`, `position`, `displayorder`, `name`, `parameters`, `code`, `starttime`, `endtime`) VALUES ('1', 'text', 'belownav', '1', '测试', 'a:3:{s:7:\"content\";s:12:\"测试广告\";s:4:\"link\";s:19:\"https://example.com\";s:4:\"size\";s:4:\"30pt\";}', '<a href=\"adredir.php?id=1&amp;url=https%3A%2F%2Fexample.com\" target=\"_blank\"><span style=\"font-size: 30pt\">测试广告</span></a>', NULL, NULL)] #0 /www/wwwroot/站点名称-已脱敏处理/nexus/Database/DBMysqli.php(28): mysqli->query()
#1 /www/wwwroot/站点名称-已脱敏处理/nexus/Database/NexusDB.php(78): Nexus\Database\DBMysqli->query()
#2 /www/wwwroot/站点名称-已脱敏处理/nexus/Database/helpers.php(21): Nexus\Database\NexusDB->query()
#3 /www/wwwroot/站点名称-已脱敏处理/include/globalfunctions.php(69): mysql_query()
#4 /www/wwwroot/站点名称-已脱敏处理/public/admanage.php(349): sql_query()
#5 {main}
`
### 解决方案

> 根据日志来看，starttime与endtime似乎不能留空，但管理面板却显示：
> ![image](https://user-images.githubusercontent.com/45203648/151367944-94a4993e-9a4f-4e8a-ade1-62b8b64d2cbe.png)

**_起始时间_** & **_终止时间_** 必须填写。（如果您使用的是 NexusPHP v1.6.0-beta12 或更早版本）
需要立即生效的话，请将 **_起始时间_** 设定为任意早于当前时间的时刻。
 **_终止时间_** 请自行酌情填写。不能留空。

**Comment by xiaomlove** [comment]
是必须填写生效时间的，原版一直有这个问题。下次更新加个较验。

**Comment by xiaomlove** [comment]
v1.6.0-beta13 已更新
