### ISSUE TITLE
游客注册时无法查看 [Rules-站点规则] 与 [faq-常见问题]

### ISSUE THREAD

**Issue by oldking139** [xiaomlove/nexusphp#36]
### 问题/故障
![image](https://user-images.githubusercontent.com/45203648/152632148-3602806d-acc5-430a-a30f-79675d30720c.png)

nexusPHP注册时要求勾选确认阅读rules，以及查看faq。
但游客身份（未登录/未注册）无法查看rules以及faq，并返回：
![image](https://user-images.githubusercontent.com/45203648/152632202-55eac3a4-d1dd-4285-b5f0-50291d4ce324.png)
并退回到登录界面。

### 寻求解决方案
请问 _站点设定_ 与 _管理组面板_ 与是否有特殊设置允许guest查看rules和faq？我仔细确认了全部选项，皆没有涉及到这部分的设定。
或者说，只能通过  _站点设定_ -> _安全设定_ -> _游客访问_ -> _展示指定静态页/展示自定义内容_ 进行设定？
这种方法的弊端是无法使用多语言页面，且无法根据rules与faq内容修改而自动更新。

**Comment by xiaomlove** [comment]
查看了几个其他仓库，把要求登录的代码去掉了，下次更新也会同样去掉。

**Comment by xiaomlove** [comment]
v1.6.0-beta13 已更新
