### ISSUE TITLE
无法触发自动清理未验证用户

### ISSUE THREAD

**Issue by oldking139** [xiaomlove/nexusphp#37]
NexusPHP 版本：NexusPHP v1.6.0-beta12
PHP 版本：PHP 8.0
Mysql 版本：5.7.34
Redis 版本：Redis 6.2.4
### 故障
https://github.com/xiaomlove/nexusphp/blob/c4697a7d89c3f380667a827b116049bf2639eccf/include/cleanup.php#L505
![image](https://user-images.githubusercontent.com/45203648/153099151-0e15c473-66fa-4624-9565-88755265739e.png)
站点启动几十天了，未验证用户无法被自动清理。（也许有可能是我自己的问题？）
自动清理配置：
![image](https://user-images.githubusercontent.com/45203648/153099230-5a47b528-b872-442d-8f30-97d236cded20.png)

不确定是哪出了问题。

**Comment by xiaomlove** [comment]
按原来的逻辑，这里的未验证用户只要未验证就会计算在内，即使被清理了。清理并不是物理删除，只是禁用了。
后续更新会把未清理用户的条件加上未禁用，这样就不会计算在内了。

**Comment by xiaomlove** [comment]
v1.6.0-beta13 已更新
