### ISSUE TITLE
宝塔面板安装NexusPHP1.6成功步骤

### ISSUE THREAD

**Issue by Joyist2021** [xiaomlove/nexusphp#4]
宝塔Nginx 1.18.0 + MySQL 5.6.50 + PHP-7.2 + redis 安装要点

安装准备
安装如下php扩展
redis扩展缓存器，需重启PHP-7.2
gmp扩展
fileinfo扩展

开启被禁用php函数
putenv()
proc_open

以下必须在 /www/wwwroot/192.168.1.118 下ssh执行：

_git clone -b v1.6.0-beta3  https://github.com/xiaomlove/nexusphp.git ./  克隆v1.6.0-beta3移动到根目录_     **开发版代码 内容提交会出错,不建议使用**

推荐发布版代码
wget https://github.com/xiaomlove/nexusphp/archive/v1.6.0-beta3.zip
unzip v1.6.0-beta3.zip  解压缩,
mv -R  nexusphp-1.6.0-beta3   /www/wwwroot/192.168.1.118  移动到根目录

composer install，安装依赖

composer update，更新可能会过时的依赖关系

cp -R nexus/Install/install public/，复制 nexus/Install/install 到 public/，保证最后 public/install/install.php 存在

chmod -R 0777 /www/wwwroot/192.168.1.118，设置根目录赋予 0777 权限
以上准备工作做完，打开网站ip/域名正常会跳转安装界面。

有问题可查阅安装日志：/tmp/nexus_install_20210305.log
安装日志包含敏感数据，不要泄露。

完成后，为安全起见，请删除以下 /www/wwwroot/192.168.1.118/public/install 目录。

宝塔nginx 站点配置如下（可能需重启nginx）
```

server {
    listen 80;
    listen [::]:80;
    server_name 192.168.1.118;
    index index.php index.html index.htm default.php default.htm default.html;
    # 以实际为准
    root /www/wwwroot/192.168.1.118/public;

    #PHP-INFO-START  PHP引用配置，可以注释或修改
    include enable-php-72.conf;
    #PHP-INFO-END
    
    location / {
        index index.html index.php;
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php {
        # 以实际为准
        fastcgi_pass 127.0.0.1:9000; 
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    access_log  /www/wwwlogs/192.168.1.118.log;
    error_log  /www/wwwlogs/192.168.1.118.error.log;
}

```

**Comment by xiaomlove** [comment]
克隆那里，可以指定到当前目录就不需要移动了
```
git clone https://github.com/xiaomlove/nexusphp.git ./
```
使用克隆的方式，克隆完成后，切换到最新 release tag 进行安装，不要用最新开发提交，可能会出错。

**Comment by Joyist2021** [comment]
谢谢指正

**Comment by Mr-ByeBye** [comment]
🙄还特意叫我来看..你说你这人!

**Comment by Joyist2021** [comment]
宝塔面板根目录中存在 .user.ini 文件执行，克隆./   报错 fatal: 目标路径 '.' 已经存在，并且不是一个空目录。
改为 git clone -b v1.6.0-beta3 git://github.com/xiaomlove/nexusphp.git ./aaa 
在手动移动 ./aaa ——> ./

**Comment by Ukenn2112** [comment]
在安装向导的第三步“创建数据表”出现错误

```

Error: Index column size too large. The maximum column size is 767 bytes. [CREATE TABLE `failed_jobs` (
`id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
`uuid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
`connection` text COLLATE utf8mb4_unicode_ci NOT NULL,
`queue` text COLLATE utf8mb4_unicode_ci NOT NULL,
`payload` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
`exception` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
`failed_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`id`),
UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;]

```
PHP版本：8.0
数据库版本：MySQL：5.6.50
发行版本：v1.6.0-beta7

貌似是数据库索引限制？

**Comment by xiaomlove** [comment]
@Ukenn2112 本人只在 Mysql 5.7.19 或以上测试过。你可以尝试手工改下数据库结构语句，指定下索引长度试下：
```
UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`(200))
```

**Comment by Ukenn2112** [comment]
> @Ukenn2112 本人只在 Mysql 5.7.19 或以上测试过。你可以尝试手工改下数据库结构语句，指定下索引长度试下：
> 
> ```
> UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`(200))
> ```

更换 Mysql 5.7.34 恢复正常，感谢

原来在Mysql 版本 <=5.7.6 则字段长度不应超过767字节。
而在Mysql 版本 >=5.7.7 字段长度加大到了3072字节

**Comment by whatmeans** [comment]
安装好其他都正常，就是admin界面进不去是什么问题，显示404 Not Found

**Comment by Mr-ByeBye** [comment]
> 

@whatmeans 仔细看一下安装文档,里面有说明.

**Comment by Joyist2021** [comment]
> 安装好其他都正常，就是admin界面进不去是什么问题，显示404 Not Found

这个安装说明已经过期。请参考官方安装文档
