### ISSUE TITLE
无法查看或编辑某些用户

### ISSUE THREAD

**Issue by oldking139** [xiaomlove/nexusphp#40]
NexusPHP 版本：NexusPHP v1.6.0-beta12
PHP 版本：PHP 8.0
Mysql 版本：5.7.34
Redis 版本：Redis 6.2.4

### 故障
UID 6 与 5 对比
![image](https://user-images.githubusercontent.com/45203648/153592063-0cb2da42-c8a5-4c7d-9aa0-3f042ec783e3.png)
以SysOp身份登录站点，想要编辑某些用户信息时，发生如上情况。部分用户无法查看或编辑详细信息。
### 排障尝试
已排除：个人隐私等级设置的影响<html>
<body>

隐私等级 | 普通  低(邮箱地址公开)  强(个人信息全部隐藏)
-- | --

</body>
</html>

-  赋予另一用户sysop权限
   结果：相同结果，同样部分用户无法查看/编辑

- 检查数据库 表 ：users
  未发现异常（也许有？没检查出来）

等待进一步排查。
若代码作者需要数据库dump文件或其他日志，请告诉我。

**Comment by xiaomlove** [comment]
原来代码中要求操作者的等级满足以下条件才能管理其他用户的基本信息：

- 等级不低于 站点设定->权限管理->管理用户基本档案 最低允许的等级，默认为总版主。即低于此等级是无法编辑其他用户的。
- 等级高于被查看者的等级。即只有高等级才能编辑低等级，sysop 无法编辑 sysop。

**Comment by oldking139** [comment]
抱歉未描述清楚。这是目前的设置（这应该是默认）

> 管理用户基本档案	最低允许等级：总版主
> 管理用户重要档案信息	最低允许等级：管理员

现在的情况是：尝试用sysop账号编辑低等级用户（user及power user），依旧出现上图的情况

**Comment by xiaomlove** [comment]
你看下php日志是否有报错

**Comment by oldking139** [comment]
查看 uid=6 用户（该用户 **可以** 在pt站后台编辑）：

> [2022-02-12 17:43:00] [6c8662078124a0a885287093409434cf] [1] [295aacdbb0a4ccf197bdd7a49190cbee] [0] [0.172] local.info /www/wwwroot/站点-脱敏/app/Repositories/ExamRepository.php:580 App\Repositories\ExamRepository->getUserExamProgress uid: 1, no examUser, query: select * from `exam_users` where `uid` = '1' and `status` = '0' order by `exam_id` desc
[2022-02-12 17:43:00] [6c8662078124a0a885287093409434cf] [1] [295aacdbb0a4ccf197bdd7a49190cbee] [1] [0.174] local.info /www/wwwroot/站点-脱敏/include/functions.php:5222 get_ip_location_from_geoip no geoip2 database.


查看 uid=4 用户（该用户 **无法** 在pt站后台编辑）：

> [2022-02-12 17:43:30] [6c86620781427a30b7000302095b702c] [1] [295aacdbb0a4ccf197bdd7a49190cbee] [0] [0.175] local.info /www/wwwroot/站点-脱敏/app/Repositories/ExamRepository.php:580 App\Repositories\ExamRepository->getUserExamProgress uid: 1, no examUser, query: select * from `exam_users` where `uid` = '1' and `status` = '0' order by `exam_id` desc
[2022-02-12 17:43:30] [6c86620781427a30b7000302095b702c] [1] [295aacdbb0a4ccf197bdd7a49190cbee] [1] [0.176] local.info /www/wwwroot/站点-脱敏/include/functions.php:5222 get_ip_location_from_geoip no geoip2 database.

似乎并没有什么区别。
PS: 此处的geoip数据库是否影响？

**Comment by xiaomlove** [comment]
不是这个日志，这个是运行日志，看 php 的。

**Comment by oldking139** [comment]
> Stack trace:
#0 {main}
  thrown in /www/wwwroot/站点-脱敏/public/userdetails.php on line 243" while reading upstream, client: 请求ip, server: 站点-脱敏, request: "GET /userdetails.php?id=4 HTTP/2.0", upstream: "fastcgi://unix:/tmp/php-cgi-80.sock:", host: "站点-脱敏"

fastcgi 配置 in Nginx （9000端口已开放）:

> location ~ \.php { # 以实际为准
        fastcgi_pass 本机ipv4:9000; 
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
       }

**Comment by xiaomlove** [comment]
关键信息呢？贴出来的是没用的那部分

**Comment by oldking139** [comment]
站点的error log里面关于 _userdetail_ 的只有这么一点。请问还需要什么具体的信息呢？
PS: 访问其他页面也会throw fastcgi的信息（错误？）。

**Comment by xiaomlove** [comment]
参考：https://doc.nexusphp.org/installation.html#%E9%97%AE%E9%A2%98%E6%8E%92%E6%9F%A5

**Comment by oldking139** [comment]
调整：

> ini_set('display_errors', 1);

结果：
![image](https://user-images.githubusercontent.com/45203648/153711410-0b0558d6-a203-4c51-a2f8-d4775b478492.png)

**Comment by oldking139** [comment]
>  fpm的设定都是默认已开启的状态。
catch_workers_out = yes
php_admin_flag[log_errors] = on

调整：
> ini_set('display_errors', 1);

结果：
![image](https://user-images.githubusercontent.com/45203648/153711439-76ea6641-b49d-4ee6-9207-b9f66ca48072.png)

**Comment by xiaomlove** [comment]
这是个已知问题，下个版本会修复。感谢

**Comment by xiaomlove** [comment]
v1.6.0-beta13 已更新
