### ISSUE TITLE
候选区无法查看评论

### ISSUE THREAD

**Issue by oldking139** [xiaomlove/nexusphp#41]
NexusPHP 版本：NexusPHP v1.6.0-beta12
PHP 版本：PHP 8.0
Mysql 版本：5.7.34
Redis 版本：Redis 6.2.4

该候选有一条评论。
![image](https://user-images.githubusercontent.com/45203648/153711683-b89e2a16-9050-4b81-a4ad-d5d1d1365081.png)
点击查看后，php报告如下错误：
![image](https://user-images.githubusercontent.com/45203648/153711739-47479c06-1d6e-4217-9797-bcc9d495762d.png)

> Fatal error: Uncaught Error: Undefined constant "lastpagedefault" in /www/wwwroot/站点-脱敏/public/offers.php:210 Stack trace: #0 {main} thrown in /www/wwwroot/站点-脱敏/public/offers.php on line 210

**Comment by xiaomlove** [comment]
Got it, thanks

**Comment by xiaomlove** [comment]
v1.6.0-beta13 已更新
