### ISSUE TITLE
Forum topic title bug " are treated wrongly

### ISSUE THREAD

**Issue by slrslr** [xiaomlove/nexusphp#42]
I have tried to enter this subject of the topic at /forums.php:
`Chyba "Abc" - 123456`

Topic was created.

Then i have clicked to edit topic, and seeing that it caused subject be reset to: `Chyba ` on topic editing page.

Seems like a bug. Thank you

**Comment by xiaomlove** [comment]
Thanks for the report

**Comment by xiaomlove** [comment]
v1.6.0-beta13 released!

**Comment by slrslr** [comment]
@xiaomlove in In https://github.com/xiaomlove/nexusphp/blob/php8/public/forums.php i do not see the modification. Please kindly add link where is shown the modification that fixes this, thank you in advance.

**Comment by slrslr** [comment]
@xiaomlove

**Comment by xiaomlove** [comment]
https://github.com/xiaomlove/nexusphp/blob/php8/include/functions.php#L1012
