### ISSUE TITLE
the torrent is not registered, this tracker error

### ISSUE THREAD

**Issue by salimrz** [xiaomlove/nexusphp#43]
Hi, when I upload a torrent, the torrent is not registered, I get this tracker error

https://img001.prntscr.com/file/img001/_2DJHoi_SUOHp5j9a8oA1g.png

**Comment by xiaomlove** [comment]
Please try again, or send me the torrent file to test it

**Comment by xiaomlove** [comment]
use bittorrent protocol v1 please
