### ISSUE TITLE
Tracker: [Failure reason "regular expression err for agent

### ISSUE THREAD

**Issue by LuciuzHQ** [xiaomlove/nexusphp#44]
Hi, I use rtorrent 0.9.8 / libtorrent 0.13.8 but I have this error message in ruTorrent:

> Tracker: [Failure reason "regular expression err for agent: tTorrent v1.0.0, please ask sysop to fix this"]

Also, when I delete tTorrent 1.0.0 from the agent_allowed_family table, ruTorrent returns another error, the client banned error message.

rtorrent is well added in the agent_allowed_family table and it working because all the other seedbox made with it don't have the problem. Do you have an idea about this error ?

**Comment by xiaomlove** [comment]
You are using the latest code under devlopment ? Try to upgrade to the latest commit.

**Comment by LuciuzHQ** [comment]
Yes I use this code. Ok I will do the upgrade and let you know, thanks.
EDIT: It's ok now, it was a problem due to some .torrent files, after deleted and created it again, it seems to work.
