### ISSUE TITLE
Beta 14 installation error

### ISSUE THREAD

**Issue by LuciuzHQ** [xiaomlove/nexusphp#45]
Hi,

I receive this error during the install process, in the step 4:

> Error: ["**************************************","* Application In Production! *","**************************************",""," Do you really wish to run this command? (yes\/no) [no]:"," > Command Canceled!"]

**Comment by xiaomlove** [comment]
Got it , Thanks!

**Comment by xiaomlove** [comment]
re-tagged, re-download and try again please.

**Comment by LuciuzHQ** [comment]
Done, and all is ok now, thanks !
