### ISSUE TITLE
Promote users error

### ISSUE THREAD

**Issue by ghost** [xiaomlove/nexusphp#47]
Hello xiaomlove, how are you?
I'm running your project on my tracker and I'm having a problem promoting users...

The default for poweruser is: '4', '50', '40000', '1.05'.

Could you explain to me what the 40000 is? Is there any test I can make???

**Comment by xiaomlove** [comment]
We call it do seeding points, it is obtained in the same way as do seeding bonus, only that bonus available for trading will be reduced, bonus is also obtained by attendance, giving, saying thank you, etc., while do seeding points only do seeding, only increase and not decrease.

**Comment by ghost** [comment]
Ohhhh, okay! But if I just want to base it on the ratio, can I set it to 0?

**Comment by xiaomlove** [comment]
Sorry, unsupported. 
promotion base on downloaded + seed points + ratio + register time
demotion base on ratio

**Comment by ghost** [comment]
Sure, i set '4', '50', '40', '1.05'

run php artisan schedule:run && php include/cleanup_cli.php, and users not promoted, exemple on image:
https://i.imgur.com/JUZkexS.png

**Comment by ghost** [comment]
do you have any idea what i can do?

**Comment by xiaomlove** [comment]
Does the cleanup run to the end？try add argument 1
` php include/cleanup_cli.php 1`

**Comment by ghost** [comment]
Yes, i run with argument 1 (see in image) and noting.

https://i.imgur.com/Fv0lfc9.png

**Comment by ghost** [comment]
it is solved! Thank u xiaomlove!

**Comment by xiaomlove** [comment]
> it is solved! Thank u xiaomlove!

My pleasure，close it please
