### ISSUE TITLE
数据库安装出错

### ISSUE THREAD

**Issue by chenchaohan** [xiaomlove/nexusphp#48]
The following tables will be created
torrent_tags
Error: ["Migrating: 2022_03_07_012545_create_tags_table",""," Illuminate\\Database\\QueryException",""," SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'tags' already exists (SQL: create table `tags` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `color` varchar(255) not null, `priority` int not null default '0', `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')",""," at D:\\classic-demo\\nexusphp\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:712"," 708\u2595 \/\/ If an exception occurs when attempting to run a query, we'll format the error"," 709\u2595 \/\/ message to include the bindings with SQL, which will make this exception a"," 710\u2595 \/\/ lot more helpful to the developer instead of just the database's errors."," 711\u2595 catch (Exception $e) {"," \u279c 712\u2595 throw new QueryException("," 713\u2595 $query, $this->prepareBindings($bindings), $e"," 714\u2595 );"," 715\u2595 }"," 716\u2595 }",""," 1 D:\\classic-demo\\nexusphp\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:501"," PDOException::(\"SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'tags' already exists\")",""," 2 D:\\classic-demo\\nexusphp\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:501"," PDOStatement::execute()"]

![Snipaste_2022-03-17_10-14-19](https://user-images.githubusercontent.com/19743236/158723017-a7537de5-63d6-457b-a7fb-cc70df6e6c4f.png)

**Comment by xiaomlove** [comment]
你数据库已经存在tags表，不是原版了，要把它先删了。升级后这部分是不保留的。

**Comment by xiaomlove** [comment]
如果解决了，请关闭此 issue.
