### ISSUE TITLE
选择性的佩戴兑换过的勋章

### ISSUE THREAD

**Issue by oldking139** [xiaomlove/nexusphp#49]
NexusPHP 版本：NexusPHP v1.6.0 正式版
PHP 版本：PHP 8.0
Mysql 版本：5.7.34
Redis 版本：Redis 6.2.4

![image](https://user-images.githubusercontent.com/45203648/159011270-bfb5eb15-8cf8-4750-861f-19d978211199.png)
![image](https://user-images.githubusercontent.com/45203648/159012294-859997a1-8cee-4b04-b67e-f670cfe82e2b.png)

当用户兑换了多个勋章后，用户id将会变得越来越长（特别是勋章图比较长条的时候），而目前版本并不支持选择性佩戴勋章。
望未来加入 “选择性佩戴兑换过的徽章” 功能。

**Comment by xiaomlove** [comment]
后续安排

**Comment by xiaomlove** [comment]
1.7.0 已添加此功能
