### ISSUE TITLE
"宣传链接“ - ”个性条“ 无法使用

### ISSUE THREAD

**Issue by oldking139** [xiaomlove/nexusphp#50]
NexusPHP 版本：NexusPHP v1.6.2
PHP 版本：PHP 8.0
Mysql 版本：5.7.34
Redis 版本：Redis 6.2.4
站点权限：777 by user:www
隐私等级：“普通” 或 ”低“

---
![image](https://user-images.githubusercontent.com/45203648/159116952-d88e2d3b-af17-44f8-b999-4ac330b15a50.png)
尝试直接访问该图片：
https://站点/mybar.php?userid=1.png

报告如下错误：
```
Warning: imagecreatefrompng(/www/wwwroot/站点/pic/userbar/0.png): Failed to open stream: No such file or directory in /www/wwwroot/站点/public/mybar.php on line 24

Fatal error: Uncaught TypeError: imagealphablending(): Argument #1 ($image) must be of type GdImage, bool given in /www/wwwroot/站点/public/mybar.php:25 Stack trace: #0 /www/wwwroot/站点/public/mybar.php(25): imagealphablending() #1 {main} thrown in /www/wwwroot/站点/public/mybar.php on line 25
```
https://github.com/xiaomlove/nexusphp/blob/69c6a6f6d63baeec0da8fdb3826269feb88c2299/public/mybar.php#L24

---
尝试访问另一图片：
https://站点/cc98bar.php/id1.png
```
Fatal error: Uncaught Exception: Serialization of 'GdImage' is not allowed in /www/wwwroot/站点/classes/class_cache_redis.php:327 Stack trace: #0 /www/wwwroot/站点/classes/class_cache_redis.php(327): serialize() #1 /www/wwwroot/站点/classes/class_cache_redis.php(214): class_cache_redis->serialize() #2 /www/wwwroot/站点/public/cc98bar.php(123): class_cache_redis->cache_value() #3 {main} thrown in /www/wwwroot/站点/classes/class_cache_redis.php on line 327
```
---
同时，```/站点/public/pic/userbar```目录下仅有一个```0.png```文件。

**Comment by oldking139** [comment]
![image](https://user-images.githubusercontent.com/45203648/159117511-45348f3d-6615-4447-88ae-4875d695666c.png)
```mybar.php```内有提到```bgpic```，但仅在此文件中使用了。请问是否需要在别处提前定义？
https://github.com/xiaomlove/nexusphp/blob/69c6a6f6d63baeec0da8fdb3826269feb88c2299/public/mybar.php#L5

---
同样，在```cc98bar.php```中也有类似的```$bg```，也仅在该文件中使用。

**Comment by xiaomlove** [comment]
这块用得少，看下

**Comment by xiaomlove** [comment]
最后另一种方式是搞不了的，等下更新第一种个性化的，修复了。

**Comment by xiaomlove** [comment]
这个应该用的不多，也不是关键问题，就不标签了，你可以自取

**Comment by oldking139** [comment]
![image](https://user-images.githubusercontent.com/45203648/159121412-06405dc3-e318-4d70-ba3d-9f8a1f02f66c.png)
修改过后的文件直接显示了站点logo而非用户的统计数据。请问这是您修改的本意嘛？
```mybar.php```内的内容大多都是计算用户数据的，我想，展示用户数据才是mybar-个性条的使用方法。

**Comment by oldking139** [comment]
同时，修改过后的```mybar.php```
当访问：https://站点/mybar.php?userid=1.png 时，依旧返回了issue先前提到的信息（mybar.php line24)

**Comment by xiaomlove** [comment]
路径还有点问题，Fixed

**Comment by oldking139** [comment]
修复验证成功。

**Comment by xiaomlove** [comment]
v1.6.3 已发布！
