### ISSUE TITLE
能增加个系统自动升级吗?

### ISSUE THREAD

**Issue by chenchaohan** [xiaomlove/nexusphp#51]
每次升级都是覆盖,
好希望有个自动升级

**Comment by xiaomlove** [comment]
在升级程序和依赖包没有变更的情况下，可以尝试勾选下边的 release 版本，会自动下载进行覆盖。
但如果升级程序本身和依赖有变，不行的。
要完全自动，后续再看吧。

你可以使用 git ，将代码克隆到隔壁，进入那个目录，更新拉取一下，合并，切换到那个标签，再进行覆盖就行了。
```
cp -rf ./* /www/wwwroots/xxxx
```
当然，记得把 favicon.ico 换回来。
