### ISSUE TITLE
Seed points stills to 0.0

### ISSUE THREAD

**Issue by LuciuzHQ** [xiaomlove/nexusphp#52]
Hello,

I use the v1.6.3 on Ubuntu 20.04 with nginx, PHP 8.0, MySQL 8. Redis is installed and I have added the cronjobs.

All seems to work, except the seed points, it stills to zero (0.0).

It's a new installation, no update.

Do you have an idea why this doesn’t work?

Thanks.

**Comment by xiaomlove** [comment]
is cleanup runs well ? How about seed bonus ?

**Comment by LuciuzHQ** [comment]
Yes cleanup runs well and no error.
But now seed points work well also (already before the cleanup) !

Do you have an idea after how many time to have the first seed are the seed points begin to increase ?

**Comment by LuciuzHQ** [comment]
Ok all is good, it was a problem from my install. Great mod, thanks !
