### ISSUE TITLE
Sticky colors don't change

### ISSUE THREAD

**Issue by LuciuzHQ** [xiaomlove/nexusphp#53]
Hello,

I try to change the sticky first and second colors, but that changes nothing.
I put #57017b in first, and #555f64 in second.

With the beta 12 it worked but now with the 1.6.3 it doesn't work.

Do you have an idea why ?

**Comment by xiaomlove** [comment]
Did not find this problem。press F12, check if  rendered OK or not.
![image](https://user-images.githubusercontent.com/8530353/161386034-dd192847-bf9b-4ff9-89e8-9dcb291953a0.png)

**Comment by LuciuzHQ** [comment]
With the beta 12, I have this :

![beta12](https://user-images.githubusercontent.com/90622803/161389587-76c72abf-8b83-4cc3-9973-2b9e853cbbcf.PNG)

With the new 1.6.3 on another server, I have this :

![new](https://user-images.githubusercontent.com/90622803/161389578-822c695d-b3b1-411d-92ee-98216097add4.PNG)

**Comment by xiaomlove** [comment]
looks like the torrent has not set to sticky

**Comment by LuciuzHQ** [comment]
Here are the 3 first torrents:
![listing](https://user-images.githubusercontent.com/90622803/161390588-d95577f8-9115-47c4-ae58-5bf4067b87b0.PNG)

You can see, the first torrent has the first and second sticky, the second torrent has the second sticky only, and the third torrent has no sticky. But there is no background color difference.

EDIT: Ok, it seems to be only with the DarkPassion theme. The other themes have the color changes.
I will try to find the difference.

**Comment by xiaomlove** [comment]
It is estimated that the black theme color is too deep to cover the color you set

**Comment by LuciuzHQ** [comment]
All is good now, it was well a problem due to the black theme.
Thanks !
