### ISSUE TITLE
Shoutbox smilies

### ISSUE THREAD

**Issue by LuciuzHQ** [xiaomlove/nexusphp#54]
Hello,

I have added smilies to the shoutbox, it's well showed under the shout:
![smilies](https://user-images.githubusercontent.com/90622803/161413676-9467d178-a9d0-45ba-ad5c-7cc4580cce4b.PNG)

But when I select it to show in the shoutbox, I have only the code and not the gif, so:
![em208](https://user-images.githubusercontent.com/90622803/161413761-cb026542-305c-4f5c-be38-647218ab4dfe.PNG)

I have only added it in "functions.php" file so:
![functions](https://user-images.githubusercontent.com/90622803/161413845-d2f04d64-7f35-4d34-bb7b-d5449c94872b.PNG)

Do I need to change another file ?
Thanks.

**Comment by xiaomlove** [comment]
Where do you get these smiles? Chang the file directly is not recommend, I can do some support for these function

**Comment by LuciuzHQ** [comment]
These smilies are in the public/pic/smilies folder, I have named so : 200.gif, 201.gif,...
Yes please, because at this moment I can't use it :-(

**Comment by xiaomlove** [comment]
This will available in the next release.

**Comment by LuciuzHQ** [comment]
Thanks !

**EDIT** : I have resolved it by change this line:
`            return $matches[1] < 192 ? '<img src="pic/smilies/' . $matches[1] . '.gif" alt="[em' . $matches[1] . ']" />' : '[em' . $matches[1] . ']';`

To this:
`            return $matches[1] < 384 ? '<img src="pic/smilies/' . $matches[1] . '.gif" alt="[em' . $matches[1] . ']" />' : '[em' . $matches[1] . ']';`
