### ISSUE TITLE
Minor / Median imdb infos

### ISSUE THREAD

**Issue by LuciuzHQ** [xiaomlove/nexusphp#55]
Hello,

When I select minor or median imdb infos tooltip, there is no action, nothing happens.
When it's off, I have well the torrent name in tooltip.

Do I need to install a javascript function or a php extension ?

**Comment by xiaomlove** [comment]
Haven't test this function yet...

**Comment by LuciuzHQ** [comment]
Ok, it’s probably not functional so.

**Comment by xiaomlove** [comment]
Will be fixed in the next release

**Comment by xiaomlove** [comment]
This feature was fixed in 1.7.0
