### ISSUE TITLE
NexusPHP v1.6.6 升级 v1.7.0 受阻 [Octane 相关]

### ISSUE THREAD

**Issue by oldking139** [xiaomlove/nexusphp#56]
目前该错误（Server Error 2）已在生产与测试环境复现。
按照文档：https://doc.nexusphp.org/update1.7.html 进行操作

---
### 前置
PHP已安装模块（文档中所需模块已安装）
<details> 

>  [PHP Modules]
bcmath
Core
ctype
curl
date
dom
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
_**pcntl**_
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
_**posix**_
redis
Reflection
session
shmop
SimpleXML
soap
_**sockets**_
sodium
SPL
sqlite3
standard
swoole
sysvsem
tokenizer
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib
[Zend Modules]
Zend OPcache
</details>

PHP所需解除禁用函数：已全部解除禁用

---
### 升级
已使用v1.7.0 release zip进行覆盖
已使用composer install进行组件安装
已使用update.php进行升级，升级模式选择为：manual/手动升级（本地文件覆盖）
升级后站点一切正常

---
### 配置 Octane 加速 （故障相关）
本环境使用 **_roadrunner_**
roadrunner已置于网站根目录，且赋予www用户运行的权限
Supervisor 已配置完成，且进程正常启动 （注：roadrunner 启动代码使用的ip是 127.0.0.1 而非文档中的 0.0.0.0）
![image](https://user-images.githubusercontent.com/45203648/162620539-36297465-c4b2-49db-9a90-f1823edf5427.png)

---
### 配置 nginx 转发 （故障）
已按照文档进行相关反代的配置，并已重启nginx
![image](https://user-images.githubusercontent.com/45203648/162620622-e8834f49-1bc2-4735-ab66-aeb44a8e6655.png)

---
> ### **_重启 Nginx 后登录管理后台，看是否工作正常。如果正常，可以进一步配置下边的旧 announce 转发。_**
登录管理后台这一步，无法实现。相关错误为：
![image](https://user-images.githubusercontent.com/45203648/162620746-02ccf693-d96c-4c3d-bb62-db07e2c5deba.png)

#### 注：由于并不了解admin面板的log文件存储位置，目前无法确切定位错误原因。

**Comment by xiaomlove** [comment]
默认日志统一在/tmp目录下。可以尝试把.env中debug打开，看返回值有无trace信息。

**Comment by oldking139** [comment]
是.env文件中的`APP_DEBUG=`该选项吗？

**Comment by xiaomlove** [comment]
> 是.env文件中的`APP_DEBUG=`该选项吗？

是

**Comment by oldking139** [comment]
nexus-2022-04-10.log 中未找到相关日志。
nexus.log中有相关Error log，但是并没有`Error(code: 2)`相关的条目。（都是Error(code: 0)相关）

**Comment by xiaomlove** [comment]
可以保持旧的try_files不注释掉，这样依然使用php_fpm处理看是否正常。

**Comment by oldking139** [comment]
排查出问题所在：
由于种种原因，/www/wwwrooot/站点/rr roadrunner文件权限被改为root，但supervisor中配置为www启动，因而导致启动失败。
感谢提供帮助。
（Error(code: 0)相关皆为权限相关）
