### ISSUE TITLE
在网站搭建第三步中出现了create tables的错误

### ISSUE THREAD

**Issue by PajamASO** [xiaomlove/nexusphp#59]
这是网站提示：
The following tables will be created
faq, files, forummods, forums, friends, fun, funds, funvotes, invites, iplog, isp, language, links, locations, loginattempts, magic, media, messages, modpanel, news, offers, offervotes, overforums, peers, pmboxes, pollanswers, polls, posts, processings, prolinkclicks, readposts, regimages, reports, requests, resreq, rules, schools, searchbox_fields, searchbox, secondicons, settings, shoutbox, sitelog, snatched, sources, staffmessages, standards, stylesheets, subs, suggest, sysoppanel, teams, thanks, topics, torrent_secrets, torrents_custom_field_values, torrents_custom_fields, torrents_state, torrents, uploadspeed, user_ban_logs, users, hit_and_runs, bonus_logs, medals, user_medals, tags, torrent_tags

这是报错信息：

Error: ["Migrating: 2021_06_08_113437_create_failed_jobs_table","Migrated: 2021_06_08_113437_create_failed_jobs_table (2.04ms)","Migrating: 2021_06_08_113437_create_faq_table","Migrated: 2021_06_08_113437_create_faq_table (37.57ms)","Migrating: 2021_06_08_113437_create_files_table","Migrated: 2021_06_08_113437_create_files_table (46.99ms)","Migrating: 2021_06_08_113437_create_forummods_table","Migrated: 2021_06_08_113437_create_forummods_table (39.99ms)","Migrating: 2021_06_08_113437_create_forums_table","Migrated: 2021_06_08_113437_create_forums_table (22.76ms)","Migrating: 2021_06_08_113437_create_friends_table","Migrated: 2021_06_08_113437_create_friends_table (72.19ms)","Migrating: 2021_06_08_113437_create_fun_table","Migrated: 2021_06_08_113437_create_fun_table (27.82ms)","Migrating: 2021_06_08_113437_create_funds_table","Migrated: 2021_06_08_113437_create_funds_table (30.64ms)","Migrating: 2021_06_08_113437_create_funvotes_table","Migrated: 2021_06_08_113437_create_funvotes_table (64.16ms)","Migrating: 2021_06_08_113437_create_invites_table","Migrated: 2021_06_08_113437_create_invites_table (60.96ms)","Migrating: 2021_06_08_113437_create_iplog_table","Migrated: 2021_06_08_113437_create_iplog_table (53.86ms)","Migrating: 2021_06_08_113437_create_isp_table","Migrated: 2021_06_08_113437_create_isp_table (25.19ms)","Migrating: 2021_06_08_113437_create_language_table","Migrated: 2021_06_08_113437_create_language_table (22.97ms)","Migrating: 2021_06_08_113437_create_links_table","Migrated: 2021_06_08_113437_create_links_table (22.61ms)","Migrating: 2021_06_08_113437_create_locations_table","Migrated: 2021_06_08_113437_create_locations_table (24.89ms)","Migrating: 2021_06_08_113437_create_loginattempts_table","Migrated: 2021_06_08_113437_create_loginattempts_table (26.44ms)","Migrating: 2021_06_08_113437_create_magic_table","Migrated: 2021_06_08_113437_create_magic_table (69.25ms)","Migrating: 2021_06_08_113437_create_media_table","Migrated: 2021_06_08_113437_create_media_table (25.20ms)","Migrating: 2021_06_08_113437_create_messages_table","Migrated: 2021_06_08_113437_create_messages_table (63.24ms)","Migrating: 2021_06_08_113437_create_modpanel_table","Migrated: 2021_06_08_113437_create_modpanel_table (33.78ms)","Migrating: 2021_06_08_113437_create_news_table","Migrated: 2021_06_08_113437_create_news_table (88.31ms)","Migrating: 2021_06_08_113437_create_offers_table","Migrated: 2021_06_08_113437_create_offers_table (48.68ms)","Migrating: 2021_06_08_113437_create_offervotes_table","Migrated: 2021_06_08_113437_create_offervotes_table (46.35ms)","Migrating: 2021_06_08_113437_create_overforums_table","Migrated: 2021_06_08_113437_create_overforums_table (36.95ms)","Migrating: 2021_06_08_113437_create_peers_table","Migrated: 2021_06_08_113437_create_peers_table (74.48ms)","Migrating: 2021_06_08_113437_create_pmboxes_table","Migrated: 2021_06_08_113437_create_pmboxes_table (41.81ms)","Migrating: 2021_06_08_113437_create_pollanswers_table","Migrated: 2021_06_08_113437_create_pollanswers_table (91.93ms)","Migrating: 2021_06_08_113437_create_polls_table","Migrated: 2021_06_08_113437_create_polls_table (33.26ms)","Migrating: 2021_06_08_113437_create_posts_table","Migrated: 2021_06_08_113437_create_posts_table (276.02ms)","Migrating: 2021_06_08_113437_create_processings_table","Migrated: 2021_06_08_113437_create_processings_table (30.62ms)","Migrating: 2021_06_08_113437_create_prolinkclicks_table","Migrated: 2021_06_08_113437_create_prolinkclicks_table (23.19ms)","Migrating: 2021_06_08_113437_create_readposts_table","Migrated: 2021_06_08_113437_create_readposts_table (69.07ms)","Migrating: 2021_06_08_113437_create_regimages_table","Migrated: 2021_06_08_113437_create_regimages_table (23.95ms)","Migrating: 2021_06_08_113437_create_reports_table","Migrated: 2021_06_08_113437_create_reports_table (27.70ms)","Migrating: 2021_06_08_113437_create_requests_table","Migrated: 2021_06_08_113437_create_requests_table (73.13ms)","Migrating: 2021_06_08_113437_create_resreq_table","Migrated: 2021_06_08_113437_create_resreq_table (43.85ms)","Migrating: 2021_06_08_113437_create_rules_table","Migrated: 2021_06_08_113437_create_rules_table (23.76ms)","Migrating: 2021_06_08_113437_create_schools_table","Migrated: 2021_06_08_113437_create_schools_table (24.12ms)","Migrating: 2021_06_08_113437_create_searchbox_fields_table",""," Illuminate\\Database\\QueryException",""," SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `searchbox_fields` add unique `uniq_searchbox_type_id`(`searchbox_id`, `field_type`, `field_id`))",""," at \/www\/wwwroot\/nexusphp-1.6.0\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connection.php:712"," 708\u2595 \/\/ If an exception occurs when attempting to run a query, we'll format the error"," 709\u2595 \/\/ message to include the bindings with SQL, which will make this exception a"," 710\u2595 \/\/ lot more helpful to the developer instead of just the database's errors."," 711\u2595 catch (Exception $e) {"," \u279c 712\u2595 throw new QueryException("," 713\u2595 $query, $this->prepareBindings($bindings), $e"," 714\u2595 );"," 715\u2595 }"," 716\u2595 }",""," \u001b[2m+9 vendor frames \u001b[22m"," 10 \/www\/wwwroot\/nexusphp-1.6.0\/database\/migrations\/2021_06_08_113437_create_searchbox_fields_table.php:27"," Illuminate\\Support\\Facades\\Facade::__callStatic()",""," \u001b[2m+21 vendor frames \u001b[22m"," 32 \/www\/wwwroot\/nexusphp-1.6.0\/artisan:37"," Illuminate\\Foundation\\Console\\Kernel::handle()"]

请问是在哪出现了问题

**Comment by xiaomlove** [comment]
MySQL尝试换高版本的
