### ISSUE TITLE
number_format() error

### ISSUE THREAD

**Issue by maximuml** [xiaomlove/nexusphp#60]
`2022/04/16 01:05:10 [error] 9043#0: *3618 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: number_format(): Argument #1 ($num) must be of type float, string given in /home/wwwroot/public/index.php:365
`
Just got this error on index page

**Comment by xiaomlove** [comment]
What version of php do you have?

**Comment by maximuml** [comment]
PHP 8.1.3

`~# php -v
PHP 8.1.3 (cli) (built: Apr  2 2022 04:55:04) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.3, Copyright (c) Zend Technologies`

**Comment by xiaomlove** [comment]
OK, got it.
