### ISSUE TITLE
[Request] add Country flag🚩 based on geoip

### ISSUE THREAD

**Issue by maximuml** [xiaomlove/nexusphp#61]
Hi. Is it possible to add country flag on userdetails.php in IP Address field? Also on iphistory.php. Thanks

P.S. [geoip-updater](https://crazymax.dev/geoip-updater/) is nice script to download and update GeoIP2 databases automatically!!!

**Comment by xiaomlove** [comment]
I'll take a look first

**Comment by xiaomlove** [comment]
Built-in display [location function](https://nexusphp.org/2022/07/20/show-location/), other temporarily do not consider
