### ISSUE TITLE
imdb infos language

### ISSUE THREAD

**Issue by LuciuzHQ** [xiaomlove/nexusphp#63]
Hello,

Is it possible to change the language in the imdb infos retriever (to have the infos in French) ?

Thanks.

**Comment by Stargaterom** [comment]
bonjour, 

pour passer les info imdb en français vous pouvais le faire en suivant cette redirection : 

/vendor/imdbphp/imdbphp/conf/900_localconf.sample

ensuite vous  éditer le fichier et changer  la langue ligne 14 : 

[sites]
; IMDB server to use.
; imdbsite = "www.imdb.com"
; Tell IMDB which is the preferred language (e.g. en-US, de-DE, pt-BR)
; language = fr-FR

cordialement

**Comment by xiaomlove** [comment]
I will take a look

**Comment by xiaomlove** [comment]
1.7.17 support this feature，change it from [site setting]->[main setting]

**Comment by Stargaterom** [comment]
thank you @xiaomlove
