### ISSUE TITLE
[Request] Shoutbox edit

### ISSUE THREAD

**Issue by LuciuzHQ** [xiaomlove/nexusphp#64]
Hello,

Could you add the possibility for users to edit their text in the shoutbox?

Thanks in advance.

**Comment by xiaomlove** [comment]
Do other sites do this?

**Comment by maximuml** [comment]
I think only admin or moderator should edit text in the shoutbox

**Comment by LuciuzHQ** [comment]
I don't know if other sites do this, my idea was to give the edit right to some user classes only, not to all classes.

**Comment by xiaomlove** [comment]
This is live chat, resend with errors, do not consider the editing function.
