### ISSUE TITLE
[BUG] RSS with only bookmarked torrents not update

### ISSUE THREAD

**Issue by luckyboy** [xiaomlove/nexusphp#78]
### **Issue duplication step:**
 1. Generate a rss link with bookmarked only and 10 item per page.
 2. Bookmark torrents more than 10.
### **Expected results:**
1. Newly bookmarked torrents should be updated from RSS
### **Actual Result:**
1. No RSS update on some bookmarked torrents.

**Comment by xiaomlove** [comment]
Got it, will be fixed in the next release.

**Comment by xiaomlove** [comment]
Fixed in 1.7.17
