### ISSUE TITLE
请求支持 

### ISSUE THREAD

**Issue by xqw8889** [xiaomlove/nexusphp#79]
1,请求支持MediaInfo填入生成的非完整info信息的直接呈现，完整info不改变原有呈现方式。
2,请求增加支持用户通过个人passkey登录方式。

**Comment by xiaomlove** [comment]
登录使用 passkey 与使用密码有何区别？

**Comment by xqw8889** [comment]
> 登录使用密码与使用密码区别？

总所周知 某些时候关闭游客登录时使用自己唯一登录方式

**Comment by xiaomlove** [comment]
账号 + 密码不是自己唯一的？有何区别

**Comment by xiaomlove** [comment]
MediaInfo 原样呈现已在 1.7.17 添加，passkey 登录后续再看。

**Comment by xqw8889** [comment]
> 账号 + 密码不是自己唯一的？有何区别

关闭游客登录后同时没有cookie 那么就可以通过/login.php?passskey=登录

**Comment by xiaomlove** [comment]
1.7.18 已支持 passkey 登录。
