### ISSUE TITLE
ptgen服务意见

### ISSUE THREAD

**Issue by Rhilip** [xiaomlove/nexusphp#8]
首先感谢能使用pt-gen服务。也很希望ptgen能服务更多站点。
但是我对直接将apiendpoint直接指向公开demo表示担忧，毕竟demo使用人数较多，且说明中也明确提及不要大批量请求demo站点而应该自建cfworker。

能否做以下改动？
1. 默认配置值改为空，而不是直接写成demo域名，由安装程序在安装时询问用户是否使用ptgen类似服务以及使用哪个endpoint，并写入配置文件中。毕竟由用户设定的行为和直接写入初始配置的行为造成的影响可能存在较大差异。
2. 改为数据库强缓存或者文件缓存（类似imdbphp那种实现），而不是redis的24小时过期。改由cleanup定期少量多次的对较老数据进行更新，或者和之前一样由用户触发retriver的形式进行更新。毕竟其实对于资源简介，其实更新并没有那么频繁。

**Comment by xiaomlove** [comment]
好的，后续会更改这一块的内容。

**Comment by xiaomlove** [comment]
`v1.6.0-beta4 ` 默认关闭 `pt-gen`
