### ISSUE TITLE
Can't install on fresh server

### ISSUE THREAD

**Issue by maximuml** [xiaomlove/nexusphp#80]
Hi. I get this error on fresh server install
![IMG_20220706_191148](https://user-images.githubusercontent.com/9083083/177596245-9cee151e-e862-4606-8fea-776ea4885a15.jpg)

**Comment by xiaomlove** [comment]
I just tried a fresh install of 1.7.17 without any problems

**Comment by maximuml** [comment]
And what could be the problem?

**Comment by xiaomlove** [comment]
I can't reproduce

**Comment by maximuml** [comment]
I have to install v1.7.4 and update to 1.7.17

**Comment by xiaomlove** [comment]
I reproduce it, you are using the development code，not the tag v1.7.17
