### ISSUE TITLE
[QUESTION] ftp backup

### ISSUE THREAD

**Issue by ghost** [xiaomlove/nexusphp#82]
hello xiamlove,
I'm trying to configure the backup via ftp, but it performs the backup and does not send it to ftp. What can I do?

**Comment by xiaomlove** [comment]
see the log first.

**Comment by ghost** [comment]
dont have info, i test conection with ftp in website helper, backup has been gerate but no have info in console (with php artisan backup:all) about ftp

**Comment by xiaomlove** [comment]
The nexusphp logs are located in the /tmp directory by default

**Comment by xiaomlove** [comment]
You should run:
```
php artisan backup:cronjob --force=1
```

**Comment by xiaomlove** [comment]
Do you have any more questions?
