### ISSUE TITLE
Issues With Installation

### ISSUE THREAD

**Issue by dinosaw** [xiaomlove/nexusphp#84]
I've gotten to the point below, and all that is generated is a blank error message:

![image](https://user-images.githubusercontent.com/10761500/179122122-89d10bbb-1084-4f44-85d0-3d241cf97c4e.png)

Without an error message, I have no idea how to troubleshoot. I've double checked all the MySQL database information.

The only thing I'm not 100% clear on is the redis information. I have already installed redis, and have it running and can access it via redis-cli. So I have the redis host and the redis port. But the installer asks for the DB and password. By default, I think the password can be left blank since redis doesn't use one, but what about the DB?

**Comment by xiaomlove** [comment]
The log will tell you. reference [here](https://doc.nexusphp.org/en/faq.html#how-to-see-the-logs)

**Comment by dinosaw** [comment]
Hello,

Thank you for that link. However I'm still running into issues. With deploying a completely new install from scratch, there are no NexusPHP logs being generated in the `tmp` directory. Additionally there are no helpful logs in the web server logs, web server error logs, or the php-fpm logs.

Is there possibly a way to skip using the web installer? For example, using `php artisan migrate --seed` to seed the database? Also is there a way to choose *not* to use redis? As I believe that is where the point of failure is in my particular scenario.

**Comment by xiaomlove** [comment]
What's your environment ? what scratch ?

**Comment by dinosaw** [comment]
> What's your environment ?

The environment is a Ubuntu 20.04.2 LTS webserver running Apache2. I have already confirmed all php modules and configurations are correct. I have attached a screenshot to confirm this.

> what scratch ?

Apologies, but "from scratch" is an English expression. I was trying to say that I wiped everything clean, and started a completely new install following the step by step guide just to make sure I had done everything 100% correct.

![image](https://user-images.githubusercontent.com/10761500/180261771-870349df-5808-471b-8bf5-bd9223a70ba8.png)

**Comment by xiaomlove** [comment]
try nginx，doc is written base on nginx.
refer to doc , show error on the page

**Comment by dinosaw** [comment]
> try nginx，doc is written base on nginx

The fact that an error is not being generated on the web page, and the fact that there are no error logs in `tmp` being generated has nothing to do with Nginx vs Apache. The Apache configuration is correct with the correct PHP version and modules loaded, as proven by the above screenshot. As well as the fact that I can successfully even navigate to the web UI install proves this is not a problem between Nginx and Apache. Any web application will work on any web server software - web applications don't "just work on nginx but not Apache".

As I previously asked, is there a way to manually populate the information needed so I can skip the need for the web UI installer?

**Comment by xiaomlove** [comment]
the biggest problem is no error log. try to change php.ini  and nexus/Install/install_update_start.php to show errors, make sure /tmp and ROOT/storage is writeable by php，and try find error logs at their.

and just have a try nginx
