### ISSUE TITLE
[Request] Problem poster movies IMDB "hot" showcase

### ISSUE THREAD

**Issue by Skyline-007** [xiaomlove/nexusphp#87]
Hello 

I am having a problem with the "hot" showcase.

I have the first image of my torrent presentation appearing instead of the IMDB image appearing in the "hot" showcase

Your demo site (https://demo.nexusphp.org) does not have this problem, it takes the IMDB cover as a poster for the "hot" showcase

Do you have a solution to my problem ?

Here are my screenshots:
https://i.postimg.cc/7PnqJ8wz/posterbug.png
https://i.postimg.cc/zGvQFSjF/posterbughot.png

Thank you in advance for your answer

Best regards

Skyline-007

**Comment by xiaomlove** [comment]
The default is to take the first picture inside the description, no picture before taking the imdb cover. Next version switch this order.

**Comment by Skyline-007** [comment]
@xiaomlove OK

Thank you for your reply

If I understand correctly in the next version of NexusPHP that you are going to release this problem will be corrected ?

Thank you in advance for your answer

**Comment by xiaomlove** [comment]
1.7.19 fix this
