### ISSUE TITLE
database problem and version 1.7.19

### ISSUE THREAD

**Issue by Stargaterom** [xiaomlove/nexusphp#89]
hello @xiaomlove , since the 1.7.19 update,

the new addition link has seedbox tabs in the dashboard and always on
500
Server Error.

and in usercp seedbox is not showing either

my system which is currently where I do your auto updates, since my installation of the nexus 1.7.7 version

I'm working on another parallel install for the theme and setting the parameters.

unfortunately its 2 installs nexus on the same problem mentioned above because the database and the same for both

so I decided to create a new database and to recover your new package 1.7.19 and to redo a new complete installation from the beginning !!!!

and so I have more error: 500
Server Error when clicking on the seedbox tab (nexusphp/seed-box-records) in the my dashboard in ucercp the seedbox still does not display .

so if I understood correctly my database that I have since 1.7.7 and more compatible with your recent additions

if you had an idea to fix the problem because if each time you have to change the database, it will be very difficult to continue

knowing that if I am wrong by spanking myself the modifications its one thing my when its no longer works with update/update.php me I its no longer how to do thank you for your understanding I hope to hear from you without its my project will be finished and its sad .

**Comment by xiaomlove** [comment]
the first step: look at the error log please

**Comment by Stargaterom** [comment]
a priori the log report in tmp tells me that: [previous exception] [object] (PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxxxxx.seed_box_records' doesn't exist at /var/www/xxxxxx/vendor/laravel/framework/src/Illuminate/Database/Connection.php:413)

[2022-07-30 22:54:57] [4c1762e59aa10e12b278690548d2123b] production.ERROR: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nexusxxx.seed_box_records' doesn't exist (SQL: select count(*) as aggregate from `seed_box_records`) {"view":{"view":"/var/www/xxxxxx.xx/vendor/filament/tables/resources/views/index.blade.php","data":[]},"userId":1,"exception":"[object] (Spatie\\LaravelIgnition\\Exceptions\\ViewException(code: 0): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxxxxxx.seed_box_records' doesn't exist (SQL: select count(*) as aggregate from `seed_box_records`) at /var/www/xxxxxx/vendor/laravel/framework/src/Illuminate/Database/Connection.php:759)

I think I have a problem with my usual vendor I download yours my 1.7.19 and not offer and with the dial its not easy

**Comment by Stargaterom** [comment]
I had suspected a database problem but I hadn't thought that auto update hadn't added the table because it usually does it all by itself when it's put in migration

so indeed there was a problem with the msql database had a table with the names seedbox_records my the table had to be seed_box_records so I exported them from my new install and added to the database where it did not work and the seedbox page of the dashboard its display correctly, 

and therefore in setting/ seedbox
it is necessary to activate for which displays on the page usercp all and ok on my side


thank you for opening my eyes with the log I'm not looking in the right place I'm looking at the nginx log instead of the nexus log on tmp, I'm annoying hihihihi I love your project, 

so we can close the request thank you once again to give time and for the imdb tests would have the first result under can

**Comment by xiaomlove** [comment]
table not found? if you run the upgrade correctly, it will run the migrations and create the tables needed.

**Comment by Stargaterom** [comment]
No, it didn't work like I told you and I did the auto updates with a clean installation to see your work progress that I didn't touch and the migration wasn't done correctly because of adding the seedbox_record table before you had changed it to seed_box_record afterwards and the migration must have had a problem because nothing was added to my database and nothing was deleted either. Now I'll pay attention to it for the next time, so I suppose you can delete the seedbox_record table from the msql database?

**Comment by xiaomlove** [comment]
Maybe you updated before the official 1.7.19 release, you delete the migrations table migration = '2022_07_20_194152_create_seedbox_records_table' and the `seedbox_record` table, and perform the update again.

**Comment by Stargaterom** [comment]
hello, I exported the table from my new base and it solved my problem if you tell me who I need to delete in migration then restart auto update for who adds the table correctly I will try then. 

I come back to you because I deleted in the database and in migration and did update, its my addition in migration the table = 2022_07_20_194152_create_seedbox_records_table.php

my in the bdd its has not added the table so there would be a problem I think
