### ISSUE TITLE
Mediainfo parser

### ISSUE THREAD

**Issue by maximuml** [xiaomlove/nexusphp#9]
Is it any way to parse mediainfo on details.php? 
Like hdbits.org Thanks

**Comment by xiaomlove** [comment]
I don't have account on hdbits.org，would you please post a image here to show what it looks like ? I want to know where is media info from, `.torrent` file ? or just user upload it manually.

**Comment by maximuml** [comment]
It's from mediainfo log, not torrent file. You need to insert mediainfo log to upload page. And look like this
![34ttvj](https://user-images.githubusercontent.com/9083083/110596666-9f21d380-8190-11eb-9ed8-12eba9c8d1e2.png)
Technical info - mediainfo log

**Comment by xiaomlove** [comment]
where does the media info log come from ? @maximuml

**Comment by maximuml** [comment]
And upload.php look like this
![Akq11Ku (1)](https://user-images.githubusercontent.com/9083083/110598631-0476c400-8193-11eb-8ddc-05c595878192.png)

**Comment by xiaomlove** [comment]
parse  text from software [MediaInfo](https://mediaarea.net/en/MediaInfo)，display Runtime, Resolution, Audio etc. on detail page, right ? @maximuml

**Comment by maximuml** [comment]
yes!!!!

**Comment by xiaomlove** [comment]
OK, it will be added in the next few releases. Stay turned.

**Comment by maximuml** [comment]
Thanks!!!

**Comment by xiaomlove** [comment]
v1.6.0-beta4 add this feature, check it out!

**Comment by maximuml** [comment]
Thanks man!
Can I also suggest few more mods for this source?

**Comment by xiaomlove** [comment]
Yes, You can.

**Comment by maximuml** [comment]
+Upload 4 Images With Torrent (screenshots)
+Users Online (shows the online users, bots etc + count number of logins in last 24hrs)
+Avatar and edit on Shoutbox (shows avatar + edit function in shoutbox)
+New torrent showing in shoutbox
+Ajax search
+SCEditor as editor (Update BBcode & Preview Everywhere)

Thanks!

**Comment by maximuml** [comment]
+ Referral mod to figure out where the user is coming from
