### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by xqw8889** [xiaomlove/nexusphp#90]
1、建议消除hr放入myhr.php直接点击消除并提示花费值
2、建议后台用户详情加入考核信息和hr信息（原先旧后台有显示）
3、建议后台加入禁用下载or上传权限过滤条件
4、建议申诉功能加入申诉者和回复者是否通过邮箱通知的选项

**Comment by xiaomlove** [comment]
1、不错的建议，会添加。
2、考核列表 + hr 列表添加 uid 搜索，用户详情不添加相关信息展示了。
3、下载权限盒子规则会禁用，因此加上。上传权限只有管理员手动可以禁用，低频操作，不予考虑。
4、管理员回复通知申诉者，申诉者回复不通知。

**Comment by xiaomlove** [comment]
1.7.20 已完成相关功能
