### ISSUE TITLE
希望在新版本中增加一键更新按钮

### ISSUE THREAD

**Issue by asmydream** [xiaomlove/nexusphp#92]
请后台增加在线一键更新最新版本，或者到指定版本功能。

**Comment by xiaomlove** [comment]
暂时没有这个打算。如果没有修改过代码，可以进网站根目录执行以下命令进行更新（>=1.7.20）：
```
php artisan nexus:update --tag=v.xxx --include_composer
```
其中 v.xx 是具体版本号

**Comment by xiaomlove** [comment]
执行此命令，会下载指定版本的代码到 /tmp 目录，再覆盖到网站目录，并进行依赖更新，完成升级工作。
