### ISSUE TITLE
[Request] Add drop-down menu to "Torrents" menu header

### ISSUE THREAD

**Issue by Skyline-007** [xiaomlove/nexusphp#93]
Hello, I would like to know if it would be possible to add a drop-down menu to the header of the " Torrents " menu ?

Example : https://i.postimg.cc/bwZdYGtj/menu-d-roulant.png

" Torrents of the Day "

I would like to know if it would be possible to add " Torrents of the day " sorted by Categories ?
(Display the latest uploader torrents for 24 hours and after 24 hours the torrent disappears from the list of " Torrents of the day " )

" Torrents of the Week "

I would like to know if it would be possible to add " Torrents of the Week " sorted by Categories ?
( Display the latest uploader torrents for 1 week and after 1 week the torrents disappear from the list of " Torrents of the Week " )

" Torrents of the Month "

I would like to know if it would be possible to add " Torrents of the Month " sorted by Categories ?
( Display the latest uploader torrents for 1 month and after 1 month the torrents disappear from the list of " Torrents of the Month " )

" Most Shared Torrents "

I would like to know if it would be possible to add " Most Shared Torrents " sorted by categories ?
( Show most shared torrents in the " Most Shared Torrents " tab )

To be set automatically via nexusphp

Thank you in advance for your answer

Best regards

Skyline-007

**Comment by xiaomlove** [comment]
First of all, to torrent list to support these filtering conditions and sorting, the current support for all filtering conditions in the search box can be seen, filtered by time is currently not supported. Support the sorting look at the head of the torrent table, you see can meet?
Second, the original version of the menu editing function is not available, there is added plug-in support, is paid.

**Comment by Skyline-007** [comment]
@xiaomlove 

ok

thank you for your reply

And how much would this plug-in cost ?

**Comment by xiaomlove** [comment]
The custom menu plugin can add submenus of any link and cannot add other new features. If you need it, you can contact me via Telegram group chat on the reade page.

**Comment by Stargaterom** [comment]
it was not a bad idea skyline this torrent page of the day my time if its complicated to put in place I understand the developer

**Comment by Skyline-007** [comment]
@xiaomlove Ok thank you for your answer

Sorry but I don't have telegram
