### ISSUE TITLE
[Request] Added YouTube link on the "Upload" page ?

### ISSUE THREAD

**Issue by Skyline-007** [xiaomlove/nexusphp#94]
Hello

I would like to know if it would be possible to add the option to put a YouTube link on the " Upload " page ?

Example : https://i.postimg.cc/SxbRCHmt/youtube.png

The YouTube video player is displayed at the end of the torrent presentation

Example : https://i.postimg.cc/HLhVcnnb/page.png

Thank you in advance for your answer

Best regards

Skyline-007

**Comment by xiaomlove** [comment]
[1.7.1](https://github.com/xiaomlove/nexusphp/releases/tag/v1.7.1) add youtube tag, you can use it in any position support bbcode. see `/tags.php` at your site for more infomation.

**Comment by Stargaterom** [comment]
Hello @xiaomlove , I think that skyline meant its who would like to have as for imdb, add a link and when you validate upload the video displayed in the descyption above imdb info and below the description it avoids having to add the youtube bbcode for every upload hehehe

**Comment by xiaomlove** [comment]
It's more flexible to insert a tag in the description, like imdb, on its own.

**Comment by Stargaterom** [comment]
hello @xiaomlove,  I thought to myself it would be possible to add to the bbcode this way to add the youtube

[url=https://www.youtube.com/watch?v=-RGSe3YVijk][b]Bande Annonce[/b][/url]

because on some prez generator the code is written like this and its would avoid modifying each time.

thank you in advance

**Comment by xiaomlove** [comment]
[url] and [youtube] are two different bbcdoe, there is no need to combine them

**Comment by Stargaterom** [comment]
yes indeed its different unfortunately the youtube video does not display with this code

[url=https://www.youtube.com/watch?v=-RGSe3YVijk][b]Bande Annonce[/b][/url]

currently it only works with the beacon 

[youtube]https://www.youtube.com/watch?v=-RGSe3YVijk[/youtube]

**Comment by Stargaterom** [comment]
with this url = [url=https://www.youtube.com/watch?v=rnS20usFqYs][b]Bande Annonce[/b][/url]
this is what it looks like on another site:
https://prnt.sc/6pyqZkeCsYiz

if it can give you a little idea to add to the code if you wish thank you in advance

**Comment by xiaomlove** [comment]
You can achieve this effect by looking like this.
[center]This is the title[/center]
[youtube]https://www.youtube.com/watch?v=rnS20usFqYs[/youtube]

This is more flexible, not considering combining the two tags at the moment

**Comment by Stargaterom** [comment]
thank you for your return and your model write the tags and yes indeed its what I already do in my presentation after it might be good if you could add the youtube button here

we would just have the link to fill in

Cordially

![ajout bouton youtube](https://user-images.githubusercontent.com/107837857/185939153-d89450c1-48ee-4fda-9f8f-3904524650db.png)

**Comment by xiaomlove** [comment]
Adding buttons here has not been tried, I guess there is a certain amount of work, follow up to see it

**Comment by Stargaterom** [comment]
ok so it may happen in the future you have to wait thank you for this information

**Comment by Skyline-007** [comment]
@xiaomlove Ok thanks for your answer
