### ISSUE TITLE
problem or incomplete user_can ?

### ISSUE THREAD

**Issue by Stargaterom** [xiaomlove/nexusphp#95]
cc @xiaomlove have a small question related to your change in the class authorization system because I don't know where we set the authorizations for user_can unless you haven't finished or are working on the page to measure their authorizations? I noticed a file permissions.php in lang resource with precisely the tractuction which looks a lot like Authority Settings with torrent approval etc ... so I think it will be linked to the new class management thank you for your understanding of all my questions

**Comment by xiaomlove** [comment]
User Permissions = Class Permissions + Role Permissions + Direct Permissions, Class Permissions is build in by defaults.

**Comment by Stargaterom** [comment]
so there is not a place to settle this if I understood the problem correctly its that the moderator on the detail page cannot manage the pending (approved) and many other places which no longer have the most access despite whom and configure as staff

**Comment by Stargaterom** [comment]
I'm really sorry to have bothered you there is approval in the settings setting authorization permission I'm tired pfffff

good job
