### ISSUE TITLE
problem class user fonction.php  and permission

### ISSUE THREAD

**Issue by Stargaterom** [xiaomlove/nexusphp#96]
hello @xiaomlove , I noticed a difference order of class in function and drop down permission seting or change class a user .

the drop-down list to change the class in Authority Settings :
![index](https://user-images.githubusercontent.com/107837857/185940024-cd5d5d58-c8cf-4e5a-94e3-3a30f1388b10.png)

file function.php:
![fonctionp php](https://user-images.githubusercontent.com/107837857/185940334-ff92e4d0-52bb-4bdc-9f30-412ff1aa7ea4.png)

userdetail.php
![2](https://user-images.githubusercontent.com/107837857/185940471-f3dd8c6f-0a1d-427e-981c-d11447dac115.png)

here is my problem in my example I want to give permission to the uploader to approve his torrents and be part of the staff so I choose:
![permission uploader](https://user-images.githubusercontent.com/107837857/185940661-22520620-0fa5-45b7-8722-5ec4500dfbc5.png)

![staff uploader](https://user-images.githubusercontent.com/107837857/185940800-7e088fb4-efff-4dff-903a-cefa61c615a7.png)

so in the logic on the page of an upload I should be able to approve the torrents and edited knowing that I am from the staff !!
here is a capture that shows that it does not work by choosing the uploader class of its respective grade in the permissions. 

![resultat1](https://user-images.githubusercontent.com/107837857/185941003-bb66520e-3207-4cf8-a016-c02b80a0d3bc.png)

if I set the same thing as my capture and Torrent Management on class retiree.
![approval torrent retiree](https://user-images.githubusercontent.com/107837857/185941142-e17cea1e-5142-489f-8a33-fb8971674dc6.png)

![staff retiree](https://user-images.githubusercontent.com/107837857/185941265-dcb6f8a2-b2d9-43cc-bf07-98cc54cded14.png)

![torrent manage retiree](https://user-images.githubusercontent.com/107837857/185941503-4dd0c64a-8374-462f-b209-e8f2f1dc6ac4.png)

here is what is displayed : 
![resulat 2](https://user-images.githubusercontent.com/107837857/185941698-b26c3c68-96b0-4973-9d4b-757fde79d96f.png)

so use a user who and class uploader color red except that to give him the permissions I have to meter the class removed for that uploader and the permissions so there is a problem

I looked for where the problem could come from, my I don't know where to configure all of them, he must have an inversion with retired and upload to a user config file

thank you if you can tell me if it comes from me or there is a problem with the class user because
here is the raw site of the update.php no modification and brought by me to this version

**Comment by xiaomlove** [comment]
Github allows direct upload of images, which looks delicious

**Comment by Stargaterom** [comment]
@xiaomlove  I have modified and made the images appear. I am waiting for your return to my problem cordially

**Comment by xiaomlove** [comment]
what version you are using ?

**Comment by Stargaterom** [comment]
I installed the site and since then I only do update/update.php to see the evolution of the project

this is the version i am updating with the update.php was made on the following github date.

Commits on Aug 21, 2022
![update](https://user-images.githubusercontent.com/107837857/185996666-dc4abd70-75f6-4bad-b012-8fd3c16bdd0d.png)
![info version](https://user-images.githubusercontent.com/107837857/185997033-e2c3b401-3965-497f-a941-8ff861070966.png)

**Comment by xiaomlove** [comment]
This is the code under development, you merge the latest commit to see.

**Comment by Stargaterom** [comment]
hello, yes on update this morning of 08/22 it seems to me that its return to order and that the permissions are associated with the good class indeed that this party and under development and therefore I make my requests very quickly as a thing I'm not going to try to temporize before annoying you hihih at least you had a fan club which follows your development

**Comment by Stargaterom** [comment]
one last little thing I did update this morning which added a new database table add_permission_to_staffmessages_table.php , it does not display in my phpmyadmin its normal ?
![table manquante](https://user-images.githubusercontent.com/107837857/186119346-f899141a-97b6-4560-9978-a231a5d80259.png)

**Comment by xiaomlove** [comment]
It's normal, just add a field

**Comment by Stargaterom** [comment]
added a field? I don't know how we do it or I don't understand what you're telling me!!! because the table adds auto as it is placed in database migration

**Comment by xiaomlove** [comment]
You don't need to care about that.

**Comment by Stargaterom** [comment]
ok thanks for the answer
