### ISSUE TITLE
Uncaught Error: Call to a member function doAction()

### ISSUE THREAD

**Issue by maximuml** [xiaomlove/nexusphp#97]
Hi, I get this error
`Fatal error: Uncaught Error: Call to a member function doAction() on null in /home/wwwroot/include/globalfunctions.php:817 Stack trace: #0 /home/wwwroot/include/functions.php(5105): do_action() #1 /home/wwwroot/nexus/Install/Install.php(554): saveSetting() #2 /home/wwwroot/public/install/install.php(113): Nexus\Install\Install->saveSettings() #3 {main} thrown in /home/wwwroot/include/globalfunctions.php on line 817`

Latest version from gihub. Need help!!

**Comment by xiaomlove** [comment]
OK, Got it!

**Comment by xiaomlove** [comment]
Just pull the latest commit, Fix it.
